babplus-algorithm-study/daily-algorithm

Kang/202409/24 BAJ 여행.md
https://www.acmicpc.net/problem/2157
90분
dp를 2차원으로 관리해야하는데 또 메모리 초과는 안나게 잘 해야하는 전형적인 2차원 dp 문제
변기에 앉아서도 풀이방법 생각하기
문제이름이 여행인데 여행은 무슨 취업이나 하자ㅜ
=> [20240924] BAJ / 골드4 / 여행 / 강경민

ShinHeeEul/202409/24 동전1.md
- [링크](https://www.acmicpc.net/problem/2293)
- 실패
- n가지 종류의 동전을 갖고 K원을 만들 수 있는 경우의 수를 구하라.
- 단, 사용한 동전 구성이 달라야 한다.
```java
dp[i] = dp[i] + dp[i - coin]
```
n가지 동전을 바로바로 dp 테이블에 반영하는 것이 핵심 포인트이다.
예를 들어 1,2,5인 동전이 있다 하면,
1로 만들 수 있는 동전의 가짓수를 반영하고,
위의 dp 테이블에 2로 만들 수 있는 동전의 가짓수를 반영하고,
위의 dp 테이블에 5로 만들 수 있는 동전의 가짓수를 반영하면
자연스럽게 동전 구성이 다른 갯수를 구할 수 있다.
- 진짜 dp는 너무 어렵다. 이런 생각 어떻게 하는거지 진짜..
=> [20240924] BAJ / 골드4 / 동전1 / 신희을

JaeIn/202409/24 BAJ 상자넣기.md
30분
* 가장 긴 증가하는 수열인 LIS문제였습니다.
* 현재값을 기준 이전의 모든 요소를 확인하여, 현재 요소가 이전 요소보다 큰지 비교
* 현재값이 이전 요소 값보다 클 경우, DP 배열을 업데이트하여 현재 요소의 DP 값을 계산
* 어떤 알고리즘인지는 생각이 났는데 쉽게 코드가 떠오르지 않았습니다.
=> [20240924] BAJ / 실버2 / 상자넣기 / 이재인

JinHyeok/202409/24 BAJ 스티커.md
https://www.acmicpc.net/problem/9465
50분
변을 공유 하지 않으면서 가중치의 최대값을 구하는 문제
DP배열에 최대값을 누적시키면서 가면 됨
패턴 찾는데 매우 오래걸림 하..
구현은 금방함..
=> [20240924] BAJ / 실버1 / 스티커 / 양진혁

Ho/202409/25 PRG 이모티콘 할인행사.md
70분
문제에서 제시한 최적의 조건 찾기
백트래킹을 사용한 완전탐색
백트래킹 구현 연습을 많이 해야할것 같다
=> [20240925] PRG  /lv2/이모티콘 할인행사/김득호

JinHyeok/202409/25 PRG 이모티콘 할인행사.md
https://school.programmers.co.kr/learn/courses/30/lessons/150368
100분이상
특정 비율 이상 할인하는 이모티콘을 전부 구매하는 유저들이 있다.
유저들은 특정 금액 이상으로 이모티콘을 구매하면 다 취소하고 이모티콘 플러스에 가입한다.
이때 이모티콘 플러스 가입자 수가 1순위, 이모티콘 판매 비용이 2순위가 되도록 해서 최대값 구하기
백트래킹
내가 생각했던 방향으로 푸니까 3개의 테스트케이스가 계속 틀렸다.
아무리해도 고쳐지지가 않아서 정답을 봤는데
정답도 나랑 비슷하게 풀어서 정답과 코드를 똑같게 고쳐가면서 계속 제출해봤다
결국은 이모티콘의 가격을
나는 
```
이모티콘 가격 X ( 1 - (할인 퍼센트 * 0.01))
```
로 계산을 했지만
정답코드는
```
(100 - 할인 퍼센트) * 이모티콘 가격 / 100
```
으로 계산을 해서 차이가 났던 것이다.
아직도 확실히 무슨 차이인지는 모르겠지만 다음에는 이런 부분도 조심해야 될 것 같다.
그리고 구현 속도 확실히 올려야 할 것 같다.
=> [20240925] PRG / lv2 / 이모티콘 할인행사 / 양진혁

JaeIn/202409/25 BAJ 이모티콘 할인행사.md
https://school.programmers.co.kr/learn/courses/30/lessons/150368
70분
* 각 이모티콘 별로 할인율은 [10 , 20 , 30 , 40]퍼가 가능하고
* 각 유저는 본인 기준에 맞는 이모티콘을 할인 받아서 사거나 , 특정 가격을 넘을 경우 플러스 서비스에 가입되는 문제
* 할인율에 대한 모든 케이스를 구한 뒤
* 각 케이스 별 모든 유저에 대해서 계산을 한 뒤
* 플러스 서비스 및 이득에 대해서 구하고 답을 계속 갱신한다.
* 할인율에 대해서 케이스를 구하고 접근하는 방향은 맞았지만 구현이 어려웠습니다..
* 접근 방향을 빨리 캐치하고 구현 능력을 길러야 할 듯ㅜ
=> [20240925] PRG /lv2/이모티콘 할인행사/이재인

JaeIn/202409/26 BAJ 트리의 부모 찾기.md
https://www.acmicpc.net/problem/11725
20분
* 부모 노드를 저장하여 순차적으로 출력하는 문제
* bfs를 사용하여 각 노드를 방문 후 부모 노드를 배열에 저장
* bfs도 가물가물하네.. 열심히 해야겠습니다..
=> [20240926] BAJ / 실버2 / 트리의 부모 찾기 / 이재인

Ho/202409/26 PRG 합승 택시 요금.md
분
다익스트라 알고리즘을 활용하여 최소 비용 찾기
1. 시작지점부터 다익스트라를 이용해 모든 정점의 최소 비용을 구한다.
2. 각 정점별로 하나씩 이동하면서 다익스트라 적용 
해당 정점 비용 + A로 가는 비용 + B로 가는 비용
을 총 n 번 하면서 min 값 구하기
기본적인 다익스트라 문제랑은 조금 다르게 합승해서 가야하는 구간이 있었다.
이걸 분리해서 생각하고 다익스트라 알고리즘을 여러번 사용하면 해결할 수 있음
근데 다익스트라 구현 연습이 필요함 (스스로 구현했어야 했는데 과거 다익스트라 구현코드 참고함...) :(
=> [20240926] PRG/lv3/합습 택시 요금/김득호

JinHyeok/202409/26 BAJ 단지번호붙이기 .md
https://www.acmicpc.net/problem/2667
25분
2차원 배열에서 단지수와 단지에 있는 집의 수를 출력
BFS
걍 단순한 BFS 문제여서 쉬운문제
=> [20240926] BAJ / 실버1 / 단지번호붙이기  / 양진혁

JaeIn/202409/27 BAJ 잃어버린 괄호.md
https://www.acmicpc.net/problem/1541
10분
* 식에 괄호를 추가하여 최소의 값을 구하는 문제
* -를 기준으로 분리 후 계산하는 문제
* 지금까지 푼 것중에 제일 간단.
* 다른 문제 하나 더 풀겠습니다..
=> [20240927] BAJ / 실버2 / 잃어버린 괄호 / 이재인

JaeIn/202409/27 BAJ A와B.md
https://www.acmicpc.net/problem/12904
50분
* 문자열의 뒤에 A를 추가한다.
* 문자열을 뒤집고 뒤에 B를 추가한다.
* 이 두 조건을 지키면서 해당 문자열을 만들 수 있는지 판별하는 문제
* T에 대해 마지막 문자를 제거한게 현재 문자열과 일치하는지 판별하고
* 마지막 글자가 A , B일 때를 구분해서 다르게 체크
* 처음에는 단순하게 dfs로 문제를 풀었으나 시간 초과..
* 다시 읽어보니 dfs로 풀지 말라는 것처럼 보이네요..
* 시간 복잡도 생각해서 알고리즘 생각하는 연습이 필요할듯 ㅜ
=> [20240927] BAJ / 골드5 / A와B / 이재인

ShinHeeEul/202409/27 BAJ 크게 만들기.md
40 분
- N자리 수에서 K개 숫자를 제거해서 제일 큰 수를 구하라.
- 현재 자리와 그 다음 자리를 비교하면서 풀었다.
- 현재 자리(current)보다 다음 자리(next)가 크다면?
- 이제껏 비교했던 애들 중에 next보다 작은 애들 전부 지워주기
- 그리디라는 것을 알고도 머리를 많이 써야 하는 문제였다. 
- 풀고 나서 시간 복잡도가 너무 느리게 나왔다. 다른 사람 코드를 보니, Stack을 안쓰고 풀면 훨씬 빠르더라.
=> [20240927] BAJ / 골드3 / 크게 만들기 / 신희을

JinHyeok/202409/27 BAJ A와 B.md
https://www.acmicpc.net/problem/12904
20분
두가지 방법에 따라 A에서 B로 문자열이 만들어 질 수 있는지 없는지
A와 B의 길이 차만큼 for문 돌려서
B의 문자열을 잘라 A가 되는지 확인
처음엔 A에서 B로 가는걸 생각했다가 딱봐도 안되는게 보여서
B에서 A로 가는걸 생각했더니 바로 풀림
=> [20240927] BAJ / 골드5 / A와B / 양진혁

Ho/202409/26 PRG 합승 택시 요금.md, Ho/202409/27 BAJ  배.md
50분
박스를 옮길 수 있는 최적의 방법 찾기 
박스랑 크레인을 정렬하고 가장 무거운 박스부터 가장 높은 무게의 크레인에 
효율적으로 배당 단순 for문으로는 안된다. 사용한건 리스트에서 삭제하면서
담에 구현이 귀찮아서 포기한 이분탐색으로 풀어보자
=> [20240927] BAJ/골드5/베/김득호

Ho/202409/28 BAJ 마법사 상어와 파이어볼.md
https://www.acmicpc.net/problem/20056
150분
문제 조건에 맞게 시뮬레이션 돌리는 문제
...딱히 없음 진짜 구현하라는거 하면된다.
근데 ArrayList가 아니라 Queue를 사용하면 더 좋은 성능을 기대할 수 있을듯
정말 구현력이 매우 심각하다.
열심히 해야겠다..
=> [20240928] BAJ/골드4/마법사 상어와 파이어볼

Ho/202409/30 BAJ 톱니바퀴.md
120분
- [x ] 중
톱니를 돌리고 옆에 조건이랑 비교해서 연쇄 작용으로 돌린다.
그냥 빡구현했다.
문제를 잘 못이해하고 돌리고 나서 비교하느라 오류를 찾는데 오래 걸렸다.
=> [20240930] BAJ/골드5/톱니바퀴

ShinHeeEul/202409/30 BAJ 톱니바퀴.md
[링크](https://www.acmicpc.net/problem/14891)
60 분
- 4개의 톱니바퀴의 각 돌기(?)에는 자성이 있다.
-  톱니바퀴가 돌아갈 때 옆에 있는 톱니바퀴가 다른 자성인 경우 같이 붙어서 돌아간다.
- 이때 맨 위를 바라보는 돌기가 N극일 때 공식에 따른 점수를 합산해라.
- 구현
- 문제 이해를 잘못하고 풀고 있었다. 득호형이 말 안 해줬으면 훨씬 오래 삽질할 뻔 했다. 캄사해요 득호 킴
=> [20240930] BAJ / 골드5 / 톱니바퀴 / 신희을

Kang/202409/30 BAJ 주사위 윷놀이.md
https://www.acmicpc.net/problem/17825
12\0분
말판의 분기별로 말을 다르게 체크해야하는데 그부분을 그래프로 처리하면 된다는 생각을 못해서 굉장히 헤맴.
말판의 분기 노드에 다음 분기의 index값을 넣어줌으로써 해결
굉장히 어려운 구현 문제다. 이런 어려운 구현문제가 나올까? 라는 생각..
=> [20240930] BAJ / 골드2 / 주사위 윷놀이 / 강경민

kmj-99/202409/30 연산자끼워넣기.md
https://www.acmicpc.net/problem/14888
30분
수열과 연산자가 주어지는데, 수열 사이에 연산자를 끼워넣어서 만들 수 있는 연산값의 최대 값, 최소 값을 구하는 문제
모든 경우의 수를 탐색해도 100만개의 경우의 수이기에 dfs를 활용하여 완전탐색으로 풀이
koltin 자식 쉽지 않군
=> [20240930] BAJ / 실버1 / 연산자 끼워넣기 / 김민중

Ho/202410/1 BAJ 벽장문의 이동.md
https://www.acmicpc.net/problem/2666
90분
벽을 움직이는 최소 값 구하기
DFS 를 이용한 완전탐색? 인데 DP?
DP 카테고리라고해서 들어갔지만 
풀이가 DP 풀이 인지 모르겠다. DFS로도 충분히 잘 풀림
검색해서 풀이를 참고했는데 이런것도 DP라고 보는건지 잘 모르겠다.
=> [20241001] BAJ/골드5/벽장문의 이동/김득호

JinHyeok/202410/01 BAJ 동물원.md
https://www.acmicpc.net/problem/1309
20분
배치 경우의 수를 구하는 문제
DP
쉬운 문제 였다. 기본적인 DP 문제인듯
=> [20241001] BAJ / 실버 1 / 동물원 / 양진혁

JaeIn/202410/01 BAJ 스티커.md
https://www.acmicpc.net/problem/9465
40분
* 스터커의 점수 합 중 가장 높은 점수를 구하는 문제
* 이전값까지의 값과 현재 값을 더해 업데이트 시키는 문제
* 나름 규칙은 빨리 찾았는데 구현이 좀 걸렸슴다.. 연습 ㅜㅜ
=> [20241001] BAJ / 실버 1 / 스티커 / 이재인

ShinHeeEul/202410/01 BAJ 타일 채우기
[링크](https://www.acmicpc.net/problem/2133)
60 분
- 3×N 크기의 벽을 2×1, 1×2 크기의 타일로 채우는 경우의 수를 구해보자.
- arr[n][m] = n번째 블록을 채울 때 m개의 블록이 튀어나오게 채워진다.
- arr[n][0]일 때
- arr[n+2][0] += arr[n][0]
- arr[n+1][0] += 2 * arr[n][0]
- arr[n][1] 일 때
- arr[n+1][0] += arr[n][1]
- arr[n+1][2] += arr[n][1]
- arr[n][2] 일 때
- arr[n+1][1] += arr[n][2];
- 더 간단한 방법이 있더라.
```java
import java.util.*;
import java.lang.*;
import java.io.*;
// The main method must be in a class named "Main".
class Main {
public static int N;
public static int[] arr;
public static void main(String[] args) throws IOException {
BufferedReader br = new BufferedReader(new InputStreamReader(System.in));
N =Integer.parseInt(br.readLine());
arr =new int[N+1];
arr[0]=0;
// 홀수이면 무조건 0이다
if (N % 2 != 0) {
System.out.println(0);
return;
}
arr[2] = …
```
=> [20241001] BAJ / 골드4 / 타일 채우기 / 신희을

kmj-99/202410/1 동전1
https://www.acmicpc.net/problem/2293
30분
주어진 가치를 만들 수 있는 동전의 경우의 수를 구하는 것
0부터 주어진 가치까지의 수들을 n으로 하고 dp[n]은 n을 만들 수 있는 경우의 수로 생각하고 풀이
DP의 기준을 잡는 건 역시 어렵다
=> [20241001] BAJ / 골드4 / 동전1 / 김민중

ShinHeeEul/202410/02 PRG 주차 요금 계산.md
[20241002](https://school.programmers.co.kr/learn/courses/30/lessons/92341)
60 분
- 주차 요금 계산하는 문제
- 닥 구현
- 문제 좀 제대로 읽자. 이게 아니야? 이게 아니야? 계속 하게 되네
=> [20241002] PRG / lv2 / 주차 요금 계산 / 신희을

JinHyeok/202410/02 PRG 주차 요금 계산.md
https://school.programmers.co.kr/learn/courses/30/lessons/92341
60분
IN OUT에 따라서 주차 시간에 따른 요금 구하기
빡구현
빡구현으로 풀었지만 더 좋은 방법이 있지 않을까 라는 생각을 해보았다.
=> [20241002] PRG / LV2 / 주차 요금 계산 / 양진혁

kmj-99/202410/3 택배배달과수거하기.md
https://school.programmers.co.kr/learn/courses/30/lessons/150369
40분
물류창고에서 트럭이 택배를 싣고 집에다가 택배를 배달하고, 수거하고 다시 물류창고로 오는 최소의 경로를 구하여라
누적합을 적용해서 풀이
처음 보는 유형이라 초반에 어떻게 막막했는데, 누적합이라는 방법을 알고 보니까 문제 자체는 쉬운 거 같다
=> [20241003] 프로그래머스 / 레벨2 / 택배배달과수거하기 / 김민중

JinHyeok/202410/03 BAJ 미로탐색.md
https://www.acmicpc.net/problem/2178
30분
최단거리 길이 구하기
BFS
간단한 BFS 문제
=> [20241003] BAJ / 실버1 / 미로탐색 / 양진혁

ShinHeeEul/202410/03 BAJ 인구이동.md
[링크](https://www.acmicpc.net/problem/16234)
50 분
- 인구 이동을 며칠 동안할 수 있을 지 계산해라
- BFS로 계산
- 시간 복잡도가 안된다.. 조금만 더 줄여서 해결해야겠다.
=> [20241002] BAJ / 골드4 / 인구 이동 / 신희을

JinHyeok/202410/04 BAJ AB.md
https://www.acmicpc.net/problem/12970
40분
조건에 맞는 문자열 출력
그리디
어려운듯 쉬운듯..
=> [20241004] BAJ / 골드4 / AB / 양진혁

Ho/202410/2 PRG 주차 요금 계산.md, Ho/202410/3 PRG 가장 먼 노드.md, Ho/202410/4 BAJ 멀티탭 스케줄링.md, Ho/202410/7 BAJ 마법사 상어와 토네이도.md
120분
빙글빙글 돌면서 모래를 뿌린다.
...빡구현... 
빙글 도는거는 2번마다 1씩 증가하는 규칙사용함
나머지는 빡구현
문제이해를 너무 못한다 ...
=> [20241007] BAJ / 골드3 / 마법사 상어와 토네이도/ 김득호

ShinHeeEul/202410/05 마법사 상어와 토네이도.md
[링크](https://www.acmicpc.net/problem/20057)
180 분
- 개같은 토네이도
- 빡 구현
- %를 /로 해서 1시간 넘게 걸렸다.. 고마워 득호형
=> [20241007] BAJ / 골드3 / 마법사 상어와 토네이도 / 신희을

JaeIn/202410/06 BAJ AB.md
https://www.acmicpc.net/problem/12970
70분
* B로 만든 문자열을 만들고
* A를 뒤에부터 채우면서 해결
그리디의 생각이 너무 어렵다.. 구현도 연습이 필요 ㅜ
=> [20241006] BAJ / 골드4 / AB / 이재인

kmj-99/202410/7 치킨배달.md
https://www.acmicpc.net/problem/15686
50분
2차원 맵에 집, 치킨집, 빈집이 있는데 집과 가장 가까운 치킨집의 거리를 모든 집을 대상으로 구해서 합을 구하는 문제
집 <-> 치킨의 모든 경우의 수를 구해서 전수조사 하는 식으로 풀이
조합을 구하는 건 역시 쉽지 않다.
=> [20241007] BAJ / 골드5 / 치킨배달 / 김민중

JinHyeok/202410/07 BAJ 치킨 배달.md
https://www.acmicpc.net/problem/15686
60분
치킨 거리를 구하는 문제
백트래킹으로 하면 될 것 같다
처음에 문제를 잘못이해해서 치킨집을 기준으로 거리를 다구했더니
집을 기준으로 치킨거리를 구하는거여서 뒤늦게 고쳐봤지만 실패하고 시간초과
=> [20241007] BAJ / 골드5 / 치킨 배달 / 양진혁

JaeIn/202410/07 스타크와 링크.md
https://www.acmicpc.net/problem/14889
40분
* 조합으로 경우의 수를 먼저 구하고
* 각 조합마다 점수를 계산해서 해결
* 조합으로 풀긴했는데 정답에 백트래킹도 있어서 다시 풀어봐야겠다
=> [20241007] BAJ / 실버1 / 스타크와 링크 / 이재인

Kang/202410/7 BAJ 톱니 바퀴.md
https://www.acmicpc.net/problem/14891
90분
톱니를 돌리는걸 큐로 구현했는데 시간초과가 계속 남
덱에 rotate함수를 써서 하면 되는데 왜 시간초과 나는지 모르겠음 다시 풀 예정
구현이 젤 어려운 것 같기도..
=> [20241007] BAJ / 골드5 / 톱니바퀴 / 강경민

JaeIn/202410/07 스타크와 링크.md, JaeIn/202410/08 동물원.md
https://www.acmicpc.net/source/84911658
65분
* 사자들을 가둘 때 경우를 계산하여 해결
* 뭔가 dp의 기본문제 같은데 너무 어렵게 느껴진다.. 기본문제 풀어보면서 느낌을 알아야겠다 ㅜ
=> [20241008] BAJ / 실버1 / 동물원 / 이재인

kmj-99/8 스티커.md
https://www.acmicpc.net/problem/9465
30분
- [] 상
첫 째칸, 두 번째  칸으로 나누어서 최대 합을 구하는 식으로 접근
DP는 역시 어렵다
=> [20241008] BAJ / 실버1 / 스티커 / 김민중

JinHyeok/202410/08 BAJ 점프.md
https://www.acmicpc.net/problem/1890
50분
시작점부터 끝점까지 경로의 개수 구하는 문제
DP
기본적인 DP 문제인듯
=> [20241008] BAJ / 실버1 / 점프 / 양진혁

ShinHeeEul/202410/09 PRG 메뉴 리뉴얼.md
[링크](https://school.programmers.co.kr/learn/courses/30/lessons/72411)
70 분
- 가장 많이 나오는 주어진 길이 만큼의 문자열 패턴을 구하라.
- 단 등장 빈도는 최소 2 이상
- 백트래킹 + 비트마스킹
- 문제를 너무 어렵게 적어놨다. 처음에 가장 많이 나오는 길이가 아니라 2 이상인 거 다 출력하는 줄 알았다
=> [20241009] PRG / lv2 / 줄 세우기 / 신희을

Ho/202410/9 PRG 메뉴리뉴얼.md
분
가장 많은 사람을 만족시킬수 있는 코스요리를 만들기
백트래킹을 사용해서 완전탐색
문제좀 제대로 읽고 한번에 풀 수 있기를...
=> [20241009] PRG/Lv2/메뉴 리뉴얼/김득호

kmj-99/202410/9 메뉴리뉴얼.md
https://school.programmers.co.kr/learn/courses/30/lessons/72411
30분
단품 요리의 조합으로 가장 많이 주무된 코스요리의 경우의 수를 구하는 문제
주어진 order를 기준으로 사용자들이 주문한 단품 요리의 조합 경우의 수를 만들고, 주문한 사용자가 제일 많은 지를 확인하면서 접근
문제가 헷갈려서 이해하는 데 쉽지 않았다.
=> [20241009] 프로그래머스 / 레벨2 / 메뉴리뉴얼 / 김민중

JinHyeok/202410/09 PRG 메뉴리뉴얼.md
https://school.programmers.co.kr/learn/courses/30/lessons/72411
60분이상
가장 많이 나온 메뉴 조합을 구하는 문제
백트래킹
문제 이해좀 잘하자;
=> [20241009] PRG / LV2 / 메뉴리뉴얼 / 양진혁

JaeIn/202410/09 PRG 메뉴 리니얼.md
https://school.programmers.co.kr/learn/courses/30/lessons/72411
70분
코스별 메뉴의 개수마다 가장 많이 나온 메뉴의 조합을 찾는 문제
코스의 요리 개수마다 모든 조합을 구한 뒤 , 개수를 카운트해서 가장 많이 나온 조합이 정답
파이썬 조합에 조금더 익숙했다면 풀었을지도..
=> [20241009] PRG / LV2 / 메뉴 리뉴얼 / 이재인

Kang/202410/9 PRG 메뉴 리뉴얼.md
https://school.programmers.co.kr/learn/courses/30/lessons/72411
90분
구현 왤캐 빡세니
=> [20241009] PRG / LV2 / 메뉴 리뉴얼 / 강경민

JaeIn/202410/09 PRG 메뉴 리니얼.md, JaeIn/202410/10 BAJ 영역 구하기.md
https://www.acmicpc.net/problem/2583
30분
갈 수 있는 영역과 영역의 칸을 카운트하는 문제
bfs로 탐색하여 영역의 개수를 구했음
bfs 기본문제 같네요 구현만 더 빨리..
=> [20241010] BAJ / 실버1 / 영역 구하기 / 이재인

Ho/202410/10 BAJ 물통.md
150분
물통 1이 비어있을때 3이 가질 수 있는 물의 양 
DFS를 이용한 완전탐색
...진짜 심각하게 못함...
=> [20241010] BAJ / 골드5/물통/김득호

ShinHeeEul/202410/10 BAJ 물통
[링크](https://www.acmicpc.net/problem/2251)
30 분
- 물통끼리 서로 물을 옮겨담았을 때 A 물통이 비어있을 때 C 물통에 남아있는 물의 양 경우의 수
- bfs, 해시 코드
- 재미가 있었다.
=> [20241010] BAJ / 골드5 / 물통 / 신희을

JinHyeok/202410/10 BAJ 나이트의 이동.md
https://www.acmicpc.net/problem/7562
40분
시작점과 끝점 주고 나이트를 이동시키는 문제
BFS
무난한 BFS 문제인듯
=> [20241010]  BAJ / 실버1 / 나이트의 이동 / 양진혁

Ho/202410/11 BAJ 빵집.md
55분
왼쪽 열에서 오른쪽열로 
우상, 우, 우하로 움직이면서 도달하기
가장 윗길로 가는게 최적의 방법인 
그리디랑 dfs를 합치자
contains 메소드는 진짜 시간복잡도가 별로다..
편할수록 쓰지말자
=> [20241011] BAJ / 골드2 / 빵집/ 김득호

JinHyeok/202410/11 BAJ 수 묶기.md
https://www.acmicpc.net/problem/1744
30분
수를 묶으면 곱해야되고 아니면 합을해서 최대값 구하기
양수와 0,음수를 다른 배열에 담아서
값을 구해줌
난이도에 비해 쉬웠음
=> [20241011] BAJ / 골드4 / 수 묶기 / 양진혁

JaeIn/202410/11 BAJ 수 묶기.md
https://www.acmicpc.net/problem/1744
65분
수를 2개씩 묶거나 묶지 않아서 최대값을 만드는 문제
음수를 저장할 배열 , 양수를 저장할 배열을 각각 만들어서 처리
방법은 동일했지만 케이스 몇개만 통과가 안되는거같았다..
시간안에 구현 능력이 부족.. 연습 필요..
=> [20241011] BAJ / 골드4 / 수 묶기 / 이재인

ShinHeeEul/202410/14 BAJ 나룻배.md
[링크](https://www.acmicpc.net/problem/2065)
60 분
- 사람 항구에 도착하는 순서대로 반대로  보내줘라
- 그리고 항구에 내린 순서대로 출력해라
- 구현 + pq
- 득호형이 반례줘서 풀 수 있었다. 아니였음 한참 헛손질 할 뻔 했네
=> [20241014] BAJ / 골드2 / 나룻배 / 신희을

Ho/202410/14 BAJ 나룻배.md
70분
배를 옮기는 단순 구현문제
단순 빡구현
문제 테스트케이스를 보고 정확히 이해하고 풀이를하자
=> [20241014] BAJ / 골드2 / 나룻배/ 김득호

kmj-99/202410/14 BJ14888.md
https://www.acmicpc.net/problem/14888
30분
수열 사이에 연산자를 넣어서 최소, 최대값을 구하는 문제
연산자의 개수가 최대 11개라서 DFS를 활요하여 모든 경우의 수를 찾고 비교하는 식으로 접근
쏘쏘한 문제인 거 같다
=> [20241014] BAJ / 실버1 / 연산자 끼워넣기 / 김민중

JinHyeok/202410/15 BAJ  상자넣기.md
https://www.acmicpc.net/problem/1965
20분
##✏️ 문제 설명
작은 크기의 상자가 앞에 있으면 상자를 넣을 수 있고
최대로 넣을 수 있는 값을 구하는 문제
DP
간단한 DP문제
=> [20241015] BAJ / 실버2 / 상자넣기 / 양진혁

ShinHeeEul/202410/15 BAJ 합분해.md
[링크](https://www.acmicpc.net/problem/2225)
50 분
- 0부터 N까지의 정수 K개를 더해서 그 합이 N이 되는 경우의 수를 구하는 프로그램을 작성하시오.
- 덧셈의 순서가 바뀐 경우는 다른 경우로 센다(1+2와 2+1은 서로 다른 경우). 또한 한 개의 수를 여러 번 쓸 수도 있다.
- 이차원 배열 dp
- 골드 5문제는 아닌듯.. dp인걸 알았으니까 생각했지. 아니면 생각도 못했다.
=> [20241015] BAJ / 골드5 / 합분해 / 신희을

Ho/202410/15 BAJ 합분해.md
120분
값 N을 0~N 까지의 수를 K번 더해서 만들수있는 경우의 수
이전 경우를 고려해서 더 한다.
하... DP 풀이 여러 방면으로 생각해보기
=> [20241015] BAJ / 골드5 /합분해 / 김득호

Kang/202410/15 BAJ 점프.md
https://www.acmicpc.net/problem/2253
90분
2차원 dp
2차원으로 생각하는것과 등차수열의 합을 구해야하는 부분에서 막혔음
2차원 dp 더 풀어 보자
=> [20241015] BAJ / 골드4 / 점프 / 강경민

ShinHeeEul/202410/16 PRG 택배 배달과 수거하기.md
[링크](https://school.programmers.co.kr/learn/courses/30/lessons/150369)
70 분
- 택배 왔다갔다 하면서 택배주고, 빈 상자 수거해라
- 이때 다 수거하고 다 배달해야하는 움직일 수 있는 최소 거리
- PQ + 구현
- 이거 또 득호형 아니면 알고리즘 생각 못했다.
=> [20241016] PRG / lv2 / 택배 배달과 수거하기 / 신희을

Ho/202410/16 PRG 택배 배달 수거하기.md
70분
가장 빠르게 문제에서 제시한 택배를 배송하고
수거하는 시간을 구하기
PQ를 사용해서 가장 먼 배열부터 배송하고 수거했다.
PQ 까지 사용할 필요없고 맨뒤에서 포인터로 잡고 오면
더 빠르고 쉽게 구현 가능할 것 같다.
=> [20241016] PRG / lv2 / 택배 배달과 수거하기 /김득호

JinHyeok/202410/16 PRG 택배 배달과 수거하기.md
https://school.programmers.co.kr/learn/courses/30/lessons/150369
60분이상
택배 배달과 수거하는 최소한의 거리를 구하는 문제
구현?
풀이를 보며 어떻게 이런 생각을 했지라는 궁금증부터 떠올랐고
여러문제를 많이 풀어 봐야 겠다
=> [20241016] PRG / LV2 / 택배 배달과 수거하기 / 양진혁

kmj-99/202410/16 택배배달과수거하기.md
https://school.programmers.co.kr/learn/courses/30/lessons/150369
50분
트럭이 각 집을 방문하면서 택배를 배달 및 수거 하는 최소 경로를 구하라
누적합을 사용하여 가장 먼집에서 부터 물류창고로 돌아오면서 최소경로를 구함
예전에 풀어봤던 거 같은데 다시 푸니까 못품,,
=> [20241016] PRG / lv2 / 택배 배달과 수거하기 /김민중

ShinHeeEul/202410/17 보물섬.md
[링크](https://www.acmicpc.net/problem/2589)
20 분
- 갈 수 있는 최소 거리 중 가장 먼 곳 양 끝에 보물이 놓여있다. 보물간의 거리 구하기
- 그냥 만나는 애들 땅 전부 bfs돌면서 제일 먼 거리 구하기
bfs 살짝 변형 형태
=> [20241017] BAJ / 골드5 / 보물섬 / 신희을

JaeIn/202410/16 PRG 택배 배달과 수거하기.md
https://school.programmers.co.kr/learn/courses/30/lessons/150369
65분
택배 배달 및 수거를 최단 경로로 하도록 만드는 문제
구현으로 푼듯??
쉽지 않네.. 너무 어렵슴다..
=> [20241016] PRG / LV2 / 택배 배달과 수거하기 / 이재인

JinHyeok/202410/17 BAJ 유기농 배추.md
https://www.acmicpc.net/problem/1012
40분
배추밭에서 필요한 배추흰지렁이의 마릿수를 구하는 문제
BFS
좀 더 빨리 풀어야되는데 쉽지않네..
=> [20241017] BAJ / 실버2 / 유기농 배추 / 양진혁

kmj-99/17 주차요금계산하기.md
https://school.programmers.co.kr/learn/courses/30/lessons/92341
30분
입차, 출차를 기반으로 주차요금 계산
요구사항 대로 구현
특별한 알고리즘이 사용되지 않았다
=> [20241017] / 프로그래머스 / LV2 / 주차요금계산하기 / 김민중

kmj-99/202410/18 AB.md
https://www.acmicpc.net/problem/12970
30분
n만큼의 길이의 문자열이 있는데 A,B만 들어간다. i번째가 A이고, j 번째가 B인 문자열을 찾는 문제
알고리즘 자체가 생각이 안났는데, 구글링을 하니까 어차피 A는 B뒤에 있을 수 없기에 뒤에서 부턴 하나씩 B로 설정하면서 살펴보는 식으로 접근했다.
쉽게 쉽게 생각하자!
=> [20241018]/BJ/AB/골드4/김민중

JaeIn/202410/19 BAJ 주식.md
https://www.acmicpc.net/problem/11501
25분
당일마다 주식 가격이 주어지는데
최대 이익을 낼 수 있는 액수를 구하는 문제
뒤에서부터 확인하면서 max값을 갱신
처음에는 2중for문을 사용해서 시간 초과가 발생... 구현 실력이 너무 부족합니다,,
=> [20241018] BAJ / 실버2 / 주식 / 이재인

kmj-99/202410/19 전화번호 목록.md
https://school.programmers.co.kr/learn/courses/30/lessons/42577?language=java
30분
전화번호 목록중에 하나의 전화번호가 다른 전화번호의 접두사가 되는 지 안되는지 판다하는 문제
해시맵에 전화번호 목록을 다 담고 전화번호 목록을 for문을 돌리면서 각 전화번호의 문자열들을 해시맵에 일치하는 게 있는지 확인하는 식으로 접근
풀이방법 보니까 쉬운 문제인 거 같은데 풀이방법이 생각이 안났다,,, 열심히 하자!
=> [20241019]/PRG/LV2/전화번호 목록/김민중

kmj-99/202410/20 기능개발.md
https://school.programmers.co.kr/learn/courses/30/lessons/42586
50분
배포 할 때 몇개의 기능이 배포되는 지 개수를 구하는 문제
stack에 배포된 기능을 관리하는 식으로 접근
문제는 쉬웠는데, 구현이 좀 걸렸다,
=> [20241020]/PGM/LV2/기능개발/김민중

kmj-99/202410/21 14889.md
=> [20241021]/BJ/실버1/14889/김민중

JinHyeok/202410/22 BAJ 동전1.md
https://www.acmicpc.net/problem/2293
40분
K원이 되는 경우의수 구하기
DP
기본 DP 문제
=> [20241022] BAJ / 골드4 / 동전1 / 양진혁

JinHyeok/202410/24 BAJ 숨바꼭질.md
https://www.acmicpc.net/problem/1697
40분
출발지점에서 도착지점까지 도착하는 짧은 시간 구하기
BFS
구현자체는 빠르게 했는데
if 조건문에서
cur + 1 <= 100000 && cur + 1 >= 0 && !visited[cur + 1] 이렇게 해야되는데
!visited[cur + 1] 이걸 먼저 작성했어서 outofbound 에러때문에 시간좀 잡아먹었다..
다음엔 이런부분 체크하자
=> [20241024] BAJ / 실버1 / 숨바꼭질 / 양진혁

kmj-99/202410/24 양궁대회
https://school.programmers.co.kr/learn/courses/30/lessons/92342?language=kotlin
30분
어피치보다 양궁 점수를 최대한 많이 얻을 수 있는 경우를 찾는것
모든 경우의 수를 살펴봐야 하니 백트랙킹으로 접근
백트랙킹 조건 찾는 게 어렵다.
=> [20241024]/PGM/LV2/양궁대회/김민중

Kang/202410/16 PRG 택배 배달과 수거하기.md
https://school.programmers.co.kr/learn/courses/30/lessons/150369?language=python3
90분
택배 배달 수거 동시에 하는 문제
회수가 뒤에 있어도 상관이 없다. 회수할 집까지 올때 택배를 뿌리고 오면 되는거니깐
이런 알고리즘을 적용해야할 때가 꽤 있던것같은데 로직을 외워두면 잘 쓸 것 같다.
=> Create 16 PRG 택배 배달과 수거하기.md

Kang/202410/25 BAJ AB.md
https://www.acmicpc.net/problem/12970
60분
K개의 AB쌍으로 만들 수 있는 문자열을 출력하는 문제
규칙성을 찾았지만 구현하는게 어려움
내일 다시 무조건 풀어야함 (안풀면 다음에 만나면 못품)
=> [20241025] BAJ / 골드4 / AB / 강경민

JaeIn/202410/24 BAJ 숨바꼭질.md, JaeIn/202410/test.py
https://www.acmicpc.net/problem/1697
35분
목표 숫자까지 최단 시간을 구하는 문제
bfs
그리디 문제 같은 느낌이라 해봤지만 실패.. 문제를 보고 빠르게 알고리즘 파악하는 연습이 필요..
=> [20241024] BAJ / 실버1 / 숨바꼭질 / 이재인

JaeIn/202410/25 PRG 큰 수 만들기.md
https://school.programmers.co.kr/learn/courses/30/lessons/42883
40분
가장 큰 수를 만드는 문제
스택을 이용하여 해결
처음에는 문제를 잘못 읽어 조합으로 시작했고 실패..
스택인거를 알고나니 금방 구현
=> [20241025] / PGM / LV2 / 큰 수 만들기 / 이재인

JinHyeok/202410/25 BAJ 회의실 배정.md
https://www.acmicpc.net/problem/1931
30분
회의실 배정
끝나는 시간으로 정렬해서 카운트 세면됨
대표적인 그리디 문제임
=> [20241025] BAJ / 실버1 / 회의실 배정 / 양진혁

kmj-99/202410/25 12904.md
https://www.acmicpc.net/problem/12904
30분
문자열 S를 문자열 T로 변환하는 방법
그리디로 접근
쉽지 다.
=> [20241025]/BJ/골드5/12094/김민중

Kang/202410/24 BAJ 벽 부수고 이동하기 2.md
https://www.acmicpc.net/problem/14442
90분
벽을 부술 수 있는 기회가 K 번 주어진다.
2차원으로도 3차원으로도 풀 수 있지만 python3로는 어차피 시간 초과가 나서
bytearray 를 쓰거나 pypy 로 채점 해봐야함
신투 코테 생각이 나서 다시 한번 풀어봄
=> [20241024] BAJ / 골드3 / 벽 부수고 이동하기 2 / 강경민

Kang/202410/28 BAJ 마법사 상어와 파이어볼.md
https://www.acmicpc.net/problem/20056
90분
마법사가 불을 쏘면 불이 사방으로 이동하는데 불이 겹치면 4개의 방향으로 나눠지는 게임을 구현하면 된다.
불이 겹치면 불이 나눠만 지고 그 칸에 존재하는 것이지 이동을 하는것이 아니다. 이동은 다음 회차에 하는 것
문제를 잘 읽자.
=> [20241028] BAJ / 골드4 / 마법사 상어와 파이어볼 / 강경민

JinHyeok/202410/28 BAJ 절댓값 힙.md, JinHyeok/202410/28 BAJ 최대힙.md, JinHyeok/202410/28 BAJ 최소힙.md
https://www.acmicpc.net/problem/11279
https://www.acmicpc.net/problem/1927
https://www.acmicpc.net/problem/11286
30분
최소, 최대, 절댓값 힙을 구현하는 문제
구현
직접 구현하지 않고 라이브러리를 사용했고 (굳이 직접구현까지 해봐야하나? 생각이 들었다)
최소힙과 절댓값 힙은 비교함수를 사용하여 만들었다.
우선순위 큐 파트가 있어서 한번 해봤음
=> [20241028] BAJ / 실버1 / 절댓값 힙 / 양진혁

kmj-99/202410/28 14890.md
https://www.acmicpc.net/problem/14890
30분
갈수 있는 길의 경우의 수를 구하는 문제
그냥 빡구현
하 역시 구현인 쉽지 않아
=> [20241028]/BJ/골드3/경사로/김민중

Kang/202410/29 BAJ 구간 나누기.md
https://www.acmicpc.net/problem/2228
120분
걍 개어려움
떠돌아다니는 풀이들을 이해하지못해 나만의 방식으로 코드를 짬
역대급 어려운 DP
=> [20241029] BAJ / 골드3 / 구간 나누기 / 강경민

JaeIn/202410/29 PGM N으로 표현.md
https://school.programmers.co.kr/learn/courses/30/lessons/42895
65분
N으로 묙표 숫자를 만들기 위한 최소의 숫자 개수를 구하는 문제
dp
역시 dp는 쉽지 않네요..
해설을 봐도 이해하는데 좀 걸렸습니다 ㅜ
기초를 더 해야할듯
=> [20241029] / PGM / LV3 / N으로 표현 / 이재인

kmj-99/202410/31 도넛과막대그래프.md
https://school.programmers.co.kr/learn/courses/30/lessons/258711
60분
임의의 정점을 구하고 도넛,막대,8자 그래프 개수를 구하는 문제
나가는 간선이 2개 이상이고, 들어오는 간선이 없는 정점을 임의의 정점으로 정한다. 그리고 임의의 정점에서 나가는 간선을 bfs를 통해 그래프의 모양을 구한다. 도넛은 자기 자신으로 다시 돌아올때, 8자는 하나의 정점이 2개 이상 간선이 있을때, 막대는 도넛과 8자가 아닐때로 해서 구함
그래프 모양을 판단하는 게 쉽지 않았다.
=> [20241031]/PGM/LV2/도넛과막대그래프/김민중

Ho/202410/31 BAJ 미로만들기.md, Ho/202410/31 BAJ 서강그라운드.md
https://www.acmicpc.net/problem/2665
서강그라운드 : 50분
미로만들기 : 40분
서강그라운드 : 최소거리 구하기 다익스트라 대표유형
미로만들기 : 최소로 벽을 지우고 목적지에 도달하기
서강그라운드 : 다익스트라 구현 가능하면 모든 정점에서 사용하기
미로만들기 : 큐에 지울거 벽을 부수고 이동하는 방식으로 해결
문제를 풀었지만 분명 반례가 있을거 같은데 문제가 풀렸다? 아닐수도?
다익스트라도 오랜 만에 풀어봄 지속적으로 풀어보기
=> [20241031]/BAJ/골드4/미로만들기,서강그라운드/김득호

JinHyeok/202410/31 BAJ 공유기 설치.md
https://www.acmicpc.net/problem/2110
60분
공유기간의 거리가 최대가되는 방법을 찾고 그 최대거리를 출력
이분 탐색
오랜만에 이분 탐색을해서 오래걸렸던것 같다.
=> [20241031] BAJ / 골드4 / 공유기 설치 / 양진혁

kmj-99/202411/1 큰수만들기.md
https://school.programmers.co.kr/learn/courses/30/lessons/42883?language=python3
60분
주어진 수에서 k개 만큼 수를 빼서 가장 큰 수를 구하는 문제
주어진 수를 for문을 돌면서 스택에 수를 담고, 스택 가장 위에 있는 수와 주어진 수의 숫자와 비교했을 때 스택 가장 위에 있는 수가 더 작으면 스택을 갱신하는 방식으로 풀이
코딩테스트 제발 kotlin 지원 좀 해줘라ㅠ , 그리디는 약간 감으로 푸는 느낌이라 어렵다.
=> [20241101]/PGM/LV2/큰수만들기/김민중

JinHyeok/202411/01 BAJ 미로만들기.md
https://www.acmicpc.net/problem/2665
60분
시점부터 종점까지 도달할 수 있는 최소한의 벽의 개수
BFS
비슷하게 생각했지만 자세한 조건을 잘못 작성했다.
아쉽다.
=> [20241101] BAJ / 골드4 / 미로 만들기 / 양진혁

JaeIn/202411/01 BAJ 흙길 보수하기.md
https://www.acmicpc.net/problem/1911
45분
널빤지들로 웅덩이를 모두 덮는 문제
그리디
시간 복잡도의 문제가 나올 때 계속 시간 초과에 걸린다.. 비효율적으로 계속 풀고 있는듯
쉽지 않구만 ㅜ
=> [20241101] BAJ / 골드5 / 흙길 보수하기 / 이재인

Ho/202411/1 BAJ 최소 스패닝 트리.md
https://www.acmicpc.net/problem/1197
60분
최소스패닝트리 문제
pq랑 그리디?
처음 풀어보는 유형이라 공부하면서 학습하기
=> [20241101] BAJ/골드4/최소스패닝트리/김득호

ShinHeeEul/202411/02 PRG 여행경로.md
[링크](https://school.programmers.co.kr/learn/courses/30/lessons/43164?language=java)
30 분
여행 경로 중 모든 경로를 다 가는 경로를 찾아라. 중복된 게 있으면 가장 문자열이 앞순인 순서로 찾아라
dfs + 문자열
문자열 순으로 정렬하는 부분이 고민이 많았음.
=> [20241102] PRG / lv2 / 여행경로 / 신희을

Ho/202411/4 BAJ 빗물.md
https://www.acmicpc.net/problem/14719
15분
빗물이 고인 양을 계산한다.
그냥 단순 구현
문제에서 주어진 맵을 그리고
빗물이 들어 갈 수 있는 구역의 개수를 센다.
왜 빨리 풀었지? ㄷㄷ
=> [20241104] BAJ/골드5/빗물/김득호

ShinHeeEul/202411/04 BAJ 로봇청소기.md
[링크](https://www.acmicpc.net/problem/14503)
60 분
로봇 청소기가 더러운 지역 몇군데까지 돌아갈 수 있나 체크
구현
피곤해서 그런지 문제가 안읽힌다..
=> [20241104] BAJ / 골드5 / 로봇 청소기 / 신희을

JinHyeok/202411/04 BAG 주사위 굴리기.md
https://www.acmicpc.net/problem/14499
70분
주사위를 굴릴때 마다 윗면의 숫자를 나오게하는법
정육면체를 어떻게 표현해야 될 지 몰라서 
방향 별로 함수를 만들어서 직접 숫자를 재배치 했다.
다른 방법이 있을 거 같긴한데 구현문제니까 이것도 맞지않을까..?
=> [20241104] BAJ / 골드4 / 주사위 굴리기 / 양진혁

JaeIn/202411/05 BAJ 가장 긴 감소하는 부분 수열.md, JaeIn/202411/05 BAJ 가장 긴 증가하는 부분 수열.md
https://www.acmicpc.net/problem/11053
15분
가장 긴 감소하는 부분 수열의 길이 구하는 문제
dp
dp 기본 문제 , 한문제 더 하겠습니다.
=> [20241105] BAJ / 실버2 / 가장 긴 감소하는 부분 수열 / 이재인

ShinHeeEul/202411/05 BAJ 암호코드.md
[링크](https://www.acmicpc.net/problem/2011)
40 분
상근이와 선영이가 다른 사람들이 남매간의 대화를 듣는 것을 방지하기 위해서 대화를 서로 암호화 하기로 했다. 그래서 다음과 같은 대화를 했다.
상근: 그냥 간단히 암호화 하자. A를 1이라고 하고, B는 2로, 그리고 Z는 26으로 하는거야.
선영: 그럼 안돼. 만약, "BEAN"을 암호화하면 25114가 나오는데, 이걸 다시 글자로 바꾸는 방법은 여러 가지가 있어.
상근: 그렇네. 25114를 다시 영어로 바꾸면, "BEAAD", "YAAD", "YAN", "YKD", "BEKD", "BEAN" 총 6가지가 나오는데, BEAN이 맞는 단어라는건 쉽게 알수 있잖아?
선영: 예가 적절하지 않았네 ㅠㅠ 만약 내가 500자리 글자를 암호화 했다고 해봐. 그 때는 나올 수 있는 해석이 정말 많은데, 그걸 언제 다해봐?
상근: 얼마나 많은데?
선영: 구해보자!
어떤 암호가 주어졌을 때, 그 암호의 해석이 몇 가지가 나올 수 있는지 구하는 프로그램을 작성하시오.
이차원 dp - 현재 위치 값을 사용했냐? 아니면 현재 위치 값을 사용 안했냐로 나누었음.
암호가 안될 경우 0을 출력해야 하는데 어떤 경우 0이 나와야 하는지 고민헀음.
=> [20241105] BAJ / 골드5 / 암호코드 / 신희을

ShinHeeEul/202411/07 BAJ 가로등.md
[링크](https://www.acmicpc.net/problem/32069)
30 분
군데군데 가로등이 위치해있다. 가장 밝은 부분의 값부터  K개 만큼 출력하라.
BFS
약간 머리를 써야하는 BFS 문제
=> [20241107] BAJ / 골드5 / 가로등 / 신희을

JaeIn/202411/07 BAJ 창고 다각형.md
https://www.acmicpc.net/problem/2304
60분
가장 최소의 지붕 넓이를 구하는 문제
누적합
누적합이라는걸 알고도 구현을 못함..  언제 늘지
=> [20241107] BAJ / 실버2 / 창고 다각형 / 이재인

kmj-99/202411/7 12904.md
https://www.acmicpc.net/problem/12904
40분
- [] 중
임의의 문자열 S, T가 주어지는 데 문제에서 주어진 규칙을 준수하여 S를 T로 변화할 수 있는지 확인하는 문제
T에서 문자를 하나씩 빼서 S가 되는지 확인하는 방식으로 접근 
그리디라기 보단 창의적으로 생각하면 풀리는 문제인 거 같다.
=> [20241107]/BJ/골드5/12904/김민중

JinHyeok/202411/08 BAJ 포도주 시식.md
https://www.acmicpc.net/problem/2156
60분
3연속으로 마시지 않으면서 포도주를 최대한 마실 수 있는 양 출력
dp
조건 한가지를 생각 못해서 끙끙댔는데 그 외에는 기본적인 문제다..
dp 문제를 더 풀어야할듯
=> [20241108] BAJ / 실버1 / 포도주 시식 / 양진혁

Ho/202411/5 BAJ 점프.md, Ho/202411/8 BAJ 센서.md
https://www.acmicpc.net/problem/2212
50분
최적의 기지국 위치를 찾는다.
1. 정렬
2. 자신의 오른쪽의 위치한 곳과 거리를 구한다.
3. 내림차순 정렬
4. k - 1 부터 값을 다 더한다.
자신의 오른쪽까지 거리를 gap을 구하면 모두 더하면 직선 거리가 나옴
근데 기지국이 2개 이상부터면 가장 긴거는 버리를 수 있음 
그래서 k-1 개부터 남은거 다 더함 
어려움 ;;
=> [20241108] BAJ/골드5/센서/김득호

kmj-99/202411/11 14891.md
https://www.acmicpc.net/problem/14891
60분
4개의 각 톱니바퀴의 12방향에 어떤 극이 오는지 구하는 문제
각 경우의 수를 재귀함수를 이용해서 다 구하는 식으로 접근
톱니바퀴를 돌릴때 다른 톱니바퀴 돌아가는 것을 재귀로 하니까 딱 들어맞는 해결법인 거 같다.
=> [20241111]/BJ/골드5/14891/김민중

JinHyeok/202411/11 BAJ 암호 만들기.md
https://www.acmicpc.net/problem/1759
60분
사전순으로 암호 만들기
구현
구현이라서 모든 조합을 다만들어주고 최소 모음이랑 최소 자음 조건을 걸러서 직접 다 빼주었는데
굳이 이렇게 할 필요가 없을 것 같다;;
백트래킹으로하면 훨씬 쉬울듯?
=> [20241111] BAJ / 골드5 / 암호 만들기 / 양진혁

Ho/202411/11 BAJ 사다리조작.md
https://www.acmicpc.net/problem/15684
100분
i번째로 출발하면 i번째로 나가게 구현
백트래킹...
왜 구현을 못하노 ,..
=> [20241111] BAJ/골드3/사다리조작/김득호

Kang/202411/11 BAJ 사다리 조작.md
https://www.acmicpc.net/problem/15684
90분
우삼홀 좌삼짝
백트는 dfs라서 도중에 찾아서 다 리턴 시켜버리면 depth가 낮은 곳에서 정답이 있는경우를 못찾아버리는 수가 있다.
토토를 하지 말자
=> [20241111] BAJ / 골드3 / 사다리 조작 / 강경민

JaeIn/202411/12 BAJ 합분해.md
https://www.acmicpc.net/problem/2225
60분
0부터 N까지의 정수 K개를 더해서 그 합이 N이 되는 경우의 수 구하는 문제
dp
다들 천재인가..
dp는 너무 어렵슴다..
=> [20241112] BAJ / 골드5 / 합분해 / 이재인

kmj-99/202411/12 2225.md
https://www.acmicpc.net/problem/2225
60분
0~n의 숫자에서 k만큼 뽑아서 n을 만들 수 있는 경우의 수를 구하는 문제
DP를 이용해서 접근. 모든 경우의 수를 구해보고 규칙을 발견하는 식으로 점화식을 세움
정말 감이 1도 안잡힐때는 경우의수를 어느정도 구해놓고 규칙을 찾는 게 좋은 거 같다.
=> [20241112]/BJ/골드5/2225/김민중

JinHyeok/202411/12 BAJ 접두사.md
https://www.acmicpc.net/problem/1141
30분
접두사를 걸러내는 문제
문자열들을 정렬해서 비교하였다.
쉬운 문제인듯
=> [20241112] BAJ / 실버1 / 접두사 / 양진혁

Kang/202411/12 BAJ RGB 거리 2.md
https://www.acmicpc.net/problem/17404
90분
내일 다시 풀거임
=> [20241112] BAJ / 골드4 / RGB 거리 2 / 강경민

ShinHeeEul/202411/13 PRG 두 큐 합 같게 만들기.md
[링크](https://school.programmers.co.kr/learn/courses/30/lessons/118667)
30 분
두 큐에 여러 개 값이 들어있다. 두 큐를 빼고 넣고 하다가 두 큐 합이 같아지는 경우까지 몇번 하면 될지 구해라.
- 큐 두 개 쓰고
- max * 2보다 더 많이 돌면 return -1
- 같아지면 -1
- 예외에 걸리면 -1
이왜2?
=> [20241113] PRG / lv2 / 두 큐 합 같게 만들기 / 신희을

ShinHeeEul/202411/14 BAJ 이분 그래프.md
[링크](https://www.acmicpc.net/problem/1707)
90 분
그래프가 있다. 정점을 두 개의 그룹으로 나누었을 때, 한 그룹 내에 서로 인접하지 않은 노드들로만 구성할 수 있는지 없는지 판단하라.
BFS로 인접 노드들을 현재 노드 그룹의 반대 그룹으로 판정시킨다. 만약 이미 방문한 노드면 현재 그룹과 같은 그룹인지 판단한다.
같은 그룹이라면 NO를 출력한다.
되게 어렵다.. 이거 골드4 아님
=> [20241114] BAJ / 골드4 / 이분 그래프 / 신희을

JinHyeok/202411/14 감소하는수.md
https://www.acmicpc.net/problem/1038
60분
n번째 감소하는 수를 찾는 문제
BFS
처음 접근을 처음부터 감소하는 수인지 아닌지를 판별하는것으로 갔는데
도저히 안되서 해설을 보니
감소하는 수를 0부터 판별하는 것이 아닌 만드는 식으로 접근을 하였다.
어떻게 이렇게 접근을 할까;;
=> [20241114] BAJ / 골드5 / 감소하는수 / 양진혁

kmj-99/202411/14 양궁대회.md
https://school.programmers.co.kr/learn/courses/30/lessons/92342?language=python3
60분
라이온이 화살을 쏠 때 아파치 보다 점수가 잘 나오는 경우의 수 중 가장 큰 값 구하기
dfs를 사용해서 전체를 돌아보고 최적을 찾았다.
SOSO
=> [20241114]/PGM/LV2/양궁대회/김민중

ShinHeeEul/202411/15 BAJ 배.md
[링크](https://www.acmicpc.net/problem/1092)
60 분
크레인들 마다 각각 최대 중량이 정해져있다. 박스들을 배에 실는데 드는 최소 시간을 구해라.
그리디로 가장 무거운 박스를 가장 무거운거 들 수 있는 크레인에 할당
인덱스 옮겨주고 반복
생각보다 어려웠음. 암 생각없이 하니까 시간초과 나더라
=> [20241115] BAJ / 골드5 / 배 / 신희을

Ho/202411/15 BAJ 문자열게임.md
https://www.acmicpc.net/problem/20437
50분
K개를 만족하는 최소 길이 단어와 최장길이 단어 찾기
슬라이딩 윈도우를 사용함.
하나가 아니라 여러개를 관리해야했기에 
큐 배열을 만들어서 관리함
처음부터 푸는 사람들은 대단함.. 리스펙
=> [20241115] BAJ/골드5/문자열 게임2/김득호

JaeIn/202411/18 PGM 과제 진행하기.md
https://school.programmers.co.kr/learn/courses/30/lessons/176962
60분
과제를 끝낸 순서대로 이름을 배열에 담아 리턴
구현
구현력이 아주 처참합니다.. 연습..
=> [20241118] PGM / LV2 / 과제 진행하기 / 이재인

ShinHeeEul/202411/20 PRG 문자열 압축.md
[링크](https://school.programmers.co.kr/learn/courses/30/lessons/60057)
60 분
특정 길이만큼 문자열을 잘라서 압축해랴.
단순 구현 + 문자열
문제를 복잡하게 적어놔서 한참동안 헷갈렸다.
=> [20241120] PRG / lv2 / 문자열 압축 / 신희을

Ho/202411/21 BAJ 사이클 게임.md
https://www.acmicpc.net/problem/20040
45분
간선을 연결하면서 사이클을 형성하는 최소 턴 찾기
union - find를 사용해서 같은 집단에서 처음으로 간선이
추가되는 경우가 사이클이 생성되는 상황으로 판단
문제 분류를 union-find 라는 것을 몰랐다면 
풀이 방법을 생각하지 못 했을 가능성이 매우 높다.
문제를 풀면서 사이클을 찾는 효율적인 방법을 배울 수 
있어서 좋은 문제
=> [20241121] BAJ/골드4/사이클 게임/김득호

kmj-99/202411/21 문자열 압축.md
https://school.programmers.co.kr/learn/courses/30/lessons/60057
60분
문자열 압축을 가장 많이 하는 경우를 구하는 문제
문제 요구사항 대로 문자열 길이의 절반을 for문 돌리면서 하나씩 비교하는 식으로 접근
어렵다기 보단 되게 성가신 문제이다.
=> [20241121]/PGM/LV2/문자열 압축/김민중

JaeIn/202411/21 PGM 광물 캐기.md
https://school.programmers.co.kr/learn/courses/30/lessons/172927
60분
최소한의 피로도로 광물을 캐는 문제
구현..?
구현은 너무 어려워,.,. 연습,,,.제발..
=> [20241121] PGM / LV2 / 광물 캐기 / 이재인

Ho/202411/22 BAJ 수 묶기.md
https://www.acmicpc.net/problem/1744
40분
주어진 수열에서 임의로 2개를 묶거나 한가지 수를 사용해서 
최대 값을 구하는 문제
음수는 묶어서 곱하고
음수 하나남으면 0이랑 곱해서 상쇄
1은 곱하는 것보다 더하는게 좋음
양수는 큰거끼리 곱해서 처리
1을 생각하는데 좀 걸림
=> [20241122] BAJ/골드4/수 묶기/김득호

JaeIn/202411/22 PGM 리코쳇 로봇.md
https://school.programmers.co.kr/learn/courses/30/lessons/169199
65분
시작 위치에서 출발한 뒤 목표 위치에 정확하게 멈추기 위해 최소 몇 번의 이동이 필요한지 말하는 게임
bfs
한칸씩 이동하고 큐에 넣는거만 익숙해서 당황..
구현에서 그냥 부족한듯 ㅜ
=> [20241122] PGM / LV2 / 리코쳇 로봇/ 이재인

JinHyeok/202411/22 BAJ 줄어드는수.md
https://www.acmicpc.net/problem/1174
30분
N이 주어지고 N번째 줄어드는 수를 구하는문제
BFS
감소하는 수와 똑같은 문제였다.
=> [20241122] BAJ / 골드5 / 줄어드는 수 / 양진혁

Ho/202411/25 BAJ 경사로.md
https://www.acmicpc.net/problem/14890
60분
문제에서 제시하는 경사로를 구현
문제에서 제시한 조건대로 경사로 배치하면서 
가능여부 판단.
더 빨리 풀 수 있으면 좋겠다.
=> [20241125] BAJ/골드 3/경사로/김득호

JaeIn/202411/25 PGM 미로 탈출.md
https://school.programmers.co.kr/learn/courses/30/lessons/159993
30분
레버를 가지고 미로의 문을 여는 문제
bfs
일단 구현은 하긴했는데 코드가 좀 난잡한거같아서..
다시 한 번 풀어봐야겠슴다
=> [20241125] PGM / LV2 / 미로 탈출 / 이재인

JaeIn/202411/28 PGM 호텔 대실.md
https://school.programmers.co.kr/learn/courses/30/lessons/155651#
40분
최소 객실의 수를 return 하는 solution 함수
구현..?
다른 분들의 코드를 보니 현타가 옵니다..
다시 풀어보겠슴다..
=> [20241128] PGM / LV2 / 호텔 대실 / 이재인

JinHyeok/202411/29 BAJ Z.md
https://www.acmicpc.net/problem/1074
60분
Z방향으로 가면서 주어진 행과 열을 몇번째로 방문하는지 출력
분할정복
분할정복 문제를 진짜 엄청 오랜만에 본거같은데 처음보자마자도 안떠올랐다.
연습해야될듯
=> [20241129] BAJ / 골드5 / Z/ 양진혁

ShinHeeEul/202411/29 BAJ 공항.md
[링크](https://www.acmicpc.net/problem/10775)
90 분
공항에는 G개의 게이트가 있으며 각각은 1에서 G까지의 번호를 가지고 있다.
공항에는 P개의 비행기가 순서대로 도착할 예정이며, 당신은 i번째 비행기를 1번부터 gi (1 ≤ gi ≤ G) 번째 게이트중 하나에 영구적으로 도킹하려 한다. 비행기가 어느 게이트에도 도킹할 수 없다면 공항이 폐쇄되고, 이후 어떤 비행기도 도착할 수 없다.
이때 도킹할 수 있는 가장 많은 비행기 수는 몇 개인가?
세그먼트 트리..
그리디로 풀어야 하는데 어떻게 풀어야 할 지 감이 안오더라.. 나중에 해설 봐야겠다.
=> [20241129] BAJ / 골드2 / 공항 / 신희을

JinHyeok/202412/02 BAJ 빗물.md
https://www.acmicpc.net/problem/14719
50분
빗물이 담기는 수를 출력
구현
노가다로 문제를 풀었는데 너무 노가다인거 같아서
해설도 보았는데 진짜 생각할법하지만 진짜 간단한 방법으로 풀었길래 신기했다.
해설 코드를 올릴테니 볼 사람은 보길바람
=> [20241202] BAJ / 골드5 / 빗물 / 양진혁

Ho/202412/2 BAJ 배열 돌리기4.md
https://www.acmicpc.net/problem/17406
80분
2차원 배열 시계방향 돌기기 
+ 백트래킹
바깥쪽 배열부터 돌리고 
백트래킹으로 2차원 배열 기억하면서 돌리기
오랜만에 배열돌리기 하니까 오래걸림
2차원 배열 깊은 복사하는 stream 문 기억하기
=> [20241202] BAJ/골드4/배열 돌리기4/김득호

Ho/202412/3 BAJ 암호코드.md
https://www.acmicpc.net/problem/2011
120  + @ 분
문제에서 제시한 경우의 수 구하기
앞에서부터 확인하면서 뒤에 오는 값 예외처리하면서 DP 적용하기
무슨 반례인지 결국 못찾음 답답함....
허허
=> [20241203] BAJ/골드5/암호해독/김득호

JinHyeok/202412/03 BAJ 암호코드.md
https://www.acmicpc.net/problem/2011
60분
암호의 해석 가짓수 구하기
DP
노가다로 패턴찾아서 구했는데
반례가 많아서 반례정도는 찾아봤음
=> [20241203] BAJ / 골드5 / 암호코드 / 양진혁

kmj-99/202412/2225.md
https://www.acmicpc.net/problem/2225
30분
0부터 n개의 정수 에서 k개 수를 더해서 n을 만들 수 있는 경우의 수를 구하는 문제
n,k를 표로 만들어서 값을 채우면 (n-1,k) + (n,k-1)를 더한 값이 (n,k)가 된다.
점화식 세우는 건 역시 힘들다.
=> [20241203]/BJ/골드5/2225/김민중

kmj-99/202412/양궁대회
https://school.programmers.co.kr/learn/courses/30/lessons/92342
30분
라이언이 어피치를 가장 큰 점수차이로 이기는 경우의 수를 구하는 문제
화살의 개수가 10개가 최대이기에 모든 경우의 수를 dfs를 통해 돌면서 최적의 수를 찾는 식으로 접근
옛날에 했던 문제인데 다시 풀어보니까 쉽지 않았다. 역시 알고리즘은 꾸준히 해야하는 게 중요하다
=> [20241205]/PGM/LV2/양궁대회

Ho/202412/9 BAJ 마법사 상어와 비바라기.md
https://www.acmicpc.net/problem/21610
60분
상어시리즈 문제 
문제에서 제시하는대로 구현
단순 구현
더 빠르게 풀기
=> [20241209] BAJ/골드5/마법사 상어와 비바라기/김득호

kmj-99/202401/6 BJ2138.md
https://www.acmicpc.net/problem/2138
60분
0과 1로 이루어진 target, expect라는 두개의 숫자가 주어지는데 양쪽과 본인 숫자가 바뀌는 스위치를 클릭해서 target에서 expect로 변환할 때 클릭해야 하는 스위치 수를 구하는 문제
완전탐색으로 접근하기에는 경우의 수가 100000!라서 불가능 했다. 그래서 i번째 스위치를 클릭하냐 안하냐의 기준은 target의 i-1번째의 자리수가 expect의 i-1번째의 자리수와 일치하냐이다. 따라서 첫번째부터 순차적으로 돌면서  i-1 번째의 자리수를 비교하여 클릭할지 말지만 선택하면 된다. 이때 첫 번째 스위치를 클릭할때와 안할때 2가지 경우의 수만 고려하면 된다. 그래서 1000000 + 1000000수 안으로 시간복잡도를 지킬 수 있다.
그리디는 역시 어렵다.
=> [20250106]/BJ/골드4/2138

ShinHeeEul/202501/06 SWEA 파핑파핑 지뢰찾기.md
[링크](https://swexpertacademy.com/main/code/problem/problemDetail.do?contestProbId=AV5LwsHaD1MDFAXc&categoryId=AV5LwsHaD1MDFAXc&categoryType=CODE&problemTitle=%EC%A7%80%EB%A2%B0%EC%B0%BE%EA%B8%B0&orderBy=FIRST_REG_DATETIME&selectCodeLang=ALL&select-1=&pageSize=10&pageIndex=1&&&&&&&&&)
30 분
지뢰 찾기에 지뢰가 있는 위치를 안다고 했을 때, 최소 몇번 눌러야 지뢰 뺴고 모든 칸을 열 수 있는가.
bfs로 주변 0개인 공간들 연쇄 오픈 시켜주고, 숫자인 부분들 하나씩 열어주기
전형적인 탐색 문제
=> [20250116] SWEA / D4 / 파핑파핑 지뢰찾기 / 신희을

ShinHeeEul/202501/07 SWEA D4 장훈이의 높은 선반.md
[링크](https://swexpertacademy.com/main/code/problem/problemDetail.do?contestProbId=AV2b7Yf6ABcBBASw)
60 분
주어진 사람들 키를 합쳐서 선반의 높이보다 높으면서도 가장 선반에 가깝게 만들어라.
백트래킹
득호형이 말 안해줬으면 백트 생각도 못했다. 문제가 아~ 이분 탐색 될 것 같은데~ 아 그리디 될 것 같은데~ 하는 문제라 보고 바로 백트라고 생각나지 않더라
=> [20250107] SWEA / D4 / 장훈이의 높은 선반 / 신희을

Ho/202501/7 SEA D4 장훈이의 높은 선반.md
https://swexpertacademy.com/main/code/problem/problemDetail.do?contestProbId=AV2b7Yf6ABcBBASw
20분
문제에서 제시하는 수와 
주어진 수의 조합을 만들어서 가장 제시한 수보다는 높으면서 
가장 가까운 수를 찾는 문제
백트래킹, 완전탐색
자바로 구현하는 것보다 단순 모든 조합을 보는 문제라고 생각해서
오랜만에 파이썬으로 날먹
=> [20250107] SEA/D4/장훈이의 높은 선반/김득호

JinHyeok/202501/08 BAJ 캠프준비.md
https://www.acmicpc.net/problem/16938
30분
문제를 고르는 경우의를 구하는문제
백트래킹
진짜 오랜만에 풀어서 감잡을겸 쉬운문제로 풀어봤다
=> [20250108] BAJ / 골드5 / 캠프준비 / 양진혁

Ho/202501/8 SEA D5 숫자 게임.md
https://swexpertacademy.com/main/code/userProblem/userProblemDetail.do?contestProbId=AWlGyBQqaEgDFASG
120분
최대 길이 5인 숫자를 적절히 쪼개서
곱한 값이 10 미만으로 만들 때 최대한
많이 쪼갤 수 있는 경우 구하기
백트 + DP
어렵다.
백트 디피 둘다 부족하다.
=> [20250108] SEA/D5/숫자게임/김득호

kmj-99/202501/8 14891.md
https://www.acmicpc.net/problem/14891
60분
톱니바퀴를 돌려서 12시 방향이 S극인지 N극인지 판단하는 문제
이전에 풀었던 구현 문제를 DFS를 이용해서 풀어보았다.
dfs를 이용하니까 테스트 케이스 1개가 통과가 안되었다. 분명 로직도 맞는데 왜 그런건지 아직도 이유를 모르겠다.
=> [20250108]/BJ/골드5/14891

JaeIn/202501/08 PGM 무인도 여행.md
https://school.programmers.co.kr/learn/courses/30/lessons/154540
50분
각 섬에서 최대 며칠씩 머무를 수 있는지 구하는 문제
dfs
어렵네..  유형별로 다시 풀어봐야겠습니다..
=> [20250108] PGM / LV2 / 무인도 여행 / 이재인

ShinHeeEul/202501/08 SWEA D5 숫자 게임.md
[링크](https://swexpertacademy.com/main/code/userProblem/userProblemDetail.do?contestProbId=AWlGyBQqaEgDFASG&)
120 분
한 숫자를 여러 개의 수열로 나누고, 이들끼리 곱한다. (ex. 12345 -> 12, 345 or 1, 23, 45 이런 식으로) 그리고 이를 반복한다. 이렇게 했을 때 최대 몇번까지 반복할 수 있는가?
백트래킹 + DP
개어렵다 이거. 처음에 완탐으로 접근했다 시초 났다. 비트마스킹으로 푼 사람도 있는 거보니, 풀이 방법이 정말 다양한 것 같더라.
=> [20250108] SWEA / D5 /  숫자 게임 / 신희을

kmj-99/202501/9 완주하지못한선수.md
https://school.programmers.co.kr/learn/courses/30/lessons/42576
30분
전체 마라톤 참가중에서 완주하지 못한 선수 1명을 구하는 문제
해시를 이용해서 20만 시간복잡도로 해결했다.
전체 탐색으로 안되면 해시를 고려해보자
=> [20250109]/PGM/LV1/완주하지 못한선수

JinHyeok/202501/09 BAJ 돌게임6.md
https://www.acmicpc.net/problem/9660
30분
게임을 이기는 사람을 출력하는 문제
패턴 찾기
다른 문제들은 범위가 작아서 dp로 푸는데
이 문제는 N의 범위가 1조까지 주어지기 때문에
dp로 못풀어서 패턴을 찾았다.
=> [20250110] BAJ / 골드5 / 돌 게임6 / 양진혁

JinHyeok/202501/13 BAJ 신기한소수.md
https://www.acmicpc.net/problem/2023
40분
신기한 소수를 찾는 문제
DFS
문제는 풀었지만 시간초과가 나서 해답을 봤는데
애초에 한자리수 소수는 2 3 5 7밖에 없기 때문에
2 3 5 7로 DFS를 시작하는 방법이 참 신기했다;;
=> [20250113] BAJ / 골드5 / 신기한 소수 / 양진혁

ShinHeeEul/202501/13 SWEA D5 오! 나의 여신님.md
[링크](https://swexpertacademy.com/main/code/problem/problemDetail.do?contestProbId=AWsBQpPqMNMDFARG)
120 분
악마의 손아귀를 피해 여신이 있는 곳까지 도달할 수 있는 최소 시간을 구하라. 악마의 손아귀는 1초마다 주변으로 퍼지고, 여신이 있는 곳과 벽이 있는 곳은 뚫을 수 없다. 도달하지 못할 시 GAME OVER를 출력해라.
내가 여신으로 가는 BFS 중, count 값이 증가할 때 악마 손아귀도 bfs 돌면서 퍼뜨려줬다.
하 악마 손아귀 방문 배열 잘못 처리해서 시간 초과 오질나게 겪었다. 제발 이런 간단한 실수 하지 말자. 1시간 정도 걸려서 코드짜고 이거 찾는데 하루 왠 종일 썼네. 꼼꼼히 검토하고 평상시에도 최적화해서 짜는 습관을 들이자
=> [20250113] SWEA / D5 / 오! 나의 여신님 / 신희을

JaeIn/202501/13 PGM 프로세스.md
30분
프로세스의 중요도가 있고 해당 프로세스가 몇 번째로 실행되는지 구하는 문제
큐
큐는 그래도 기억은 나네요..
=> [20250113] PGM / LV2 / 프로세스 / 이재인

ShinHeeEul/202501/14 BAJ P5 속타는 저녁 메뉴.md
[링크](https://www.acmicpc.net/problem/11585)
60 분
원판을 돌려서 12시부터 시계 방향으로 읽었을 때, 특정 패턴이 등장할 확률은 몇이나 되는가?
KMP + GCD
KMP를 연습하기 위해 도전했는데, KMP 어렵다. 항상 값이 틀려졌을 때, 현재 위치에서 뒤로 가지 않고 문자열 비교를 할 수 있는 방법임을 기억하자!
=> [20250114] BAJ / P5 / 속타는 저녁 메뉴 / 신희을

JinHyeok/202501/14 BAJ 다이어트md
https://www.acmicpc.net/problem/1484
40분
주어진 식에 만족하는 쌍을 찾는 문제
X^2 - Y^2 = G인 식에서 인수분해를 통해 
(X+Y)*(X-Y) = G 인 식을 활용하여
먼저 약수를 구해서 해당 식에 만족하는 X Y쌍을 찾았다.
재밌는 문제
=> [20250114] BAJ / 골드5 / 다이어트 / 양진혁

Ho/202501/14 속타는 저녁 메뉴.md
https://www.acmicpc.net/problem/11585
70분
원판을 돌려서 수원이가 먹고 싶은 음식을 먹을 수 있는 확률
KMP 사용
점점 무슨 알고리즘인지 알고 풀어도 생각하기 어려운 문제가 많다.
많이 풀면서 익숙해지기
=> [20250114] BAJ/플레5/속타는 저녁 메뉴/김득호

ShinHeeEul/202501/15 BAJ P4 광고.md
[링크](https://www.acmicpc.net/problem/1305)
60 분
세준이는 길 한가운데에서 전광판을 쳐다보고 있었다. 전광판에는 광고가 흘러나오고 있었다. 한참을 전광판을 쳐다본 세준이는 이 광고가 의미하는 것이 무엇인지 궁금해지기 시작했다.
전광판에는 같은 내용의 문구가 무한히 반복되어 나온다. 또, 전광판의 크기는 전광판에서 한번에 보이는 최대 문자수를 나타낸다. 만약 전광판의 크기가 L이라면, 한번에 L개의 문자를 표시할 수 있는 것이다.
광고업자는 최대한의 광고효과를 내기 위해서 길이가 N인 광고를 무한히 붙여서 광고한다.
예를 들어, 광고 업자 백은진이 광고하고 싶은 내용이 aaba 이고, 전광판의 크기가 6이라면 맨 처음에 보이는 내용은 aabaaa 이다. 시간이 1초가 지날 때마다, 문자는 한 칸씩 옆으로 이동한다. 따라서 처음에 aabaaa가 보였으면 그 다음에는 abaaab가 보인다. 그 다음에는 baaaba가 보인다.
세준이가 어느 순간 전광판을 쳐다봤을 때, 그 때 쓰여 있는 문자가 입력으로 주어졌을 때, 가능한 광고의 길이중 가장 짧은 것을 출력하는 프로그램을 작성하시오.
kmp
접두사와 접미사가 같은 경우, 해당 부분은 재활용할 수 있다. 즉, 광고판 길이 - 접두사 길이가 정답이 된다.
kmp라고 생각하고 보니 잘 보이는 것 같다. 더 많은 문제 풀어서 더 익숙해지자.
=> [20250115] BAJ / 플레4 / 광고 / 신희을

kmj-99/202501/15 의상.md
https://school.programmers.co.kr/learn/courses/30/lessons/42578
60분
서로 다른 의상의 조합을 구하는 문제
해시를 적용하여 품
쏘쏘한 문제
=> [20250115]/PGM/LV2/의상

ShinHeeEul/202501/15 BAJ G1 할 일 정하기 1.md
[젤다](https://www.acmicpc.net/problem/1311)
120 분
N명의 사람과 N개의 일이 있다. 모든 사람이 N개의 일을 할 수 있는데, 각자 걸리는 시간이 다 다르다. 각 사람이 1개의 일을 나눠 담당한다 했을 때, 가장 효율적으로 할 수 있는 방법을  구해라.
비트 마스킹 + DP
비트 마스킹 개 어렵다. 득호 형이 아이디어 안줬으면 구현 못했고, 옆에 사람이 안도와줬으면 최적화 못했다. 더 숙련되서 척척 나왔으면 좋겠다.
=> [20250117] BAJ / G1 / 할 일 정하기1 / 신희을

kmj-99/202501/19 A와B 2.md
https://www.acmicpc.net/problem/12919
60분
수빈이는 A와 B로만 이루어진 영어 단어 존재한다는 사실에 놀랐다. 대표적인 예로 AB (Abdominal의 약자), BAA (양의 울음 소리), AA (용암의 종류), ABBA (스웨덴 팝 그룹)이 있다.
이런 사실에 놀란 수빈이는 간단한 게임을 만들기로 했다. 두 문자열 S와 T가 주어졌을 때, S를 T로 바꾸는 게임이다. 문자열을 바꿀 때는 다음과 같은 두 가지 연산만 가능하다.
문자열의 뒤에 A를 추가한다.
문자열의 뒤에 B를 추가하고 문자열을 뒤집는다.
주어진 조건을 이용해서 S를 T로 만들 수 있는지 없는지 알아내는 프로그램을 작성하시오. 
s -> t가 아닌 t -> s로의 방향으로 변환하는 식으로 풀었다. s -> t로 가는 건 모든 경우의 수를 탐색하므로 시간복잡도가 초과한다. 하지만 t -> s로 가면 모든 경우의 수를 탐색하는 것이 아닌 관련있는 경우의 수만 탐색하기에 시간복잡도를 준수할 수 있다.
쏘쏘
=> [20250119]/BJ/골드5/A와B 2

kmj-99/202501/20 의상.md
https://school.programmers.co.kr/learn/courses/30/lessons/42578
60분
코니가 가진 의상들이 담긴 2차원 배열 clothes가 주어질 때 서로 다른 옷의 조합의 수를 return 하도록 solution 함수를 작성해주세요.
해시를 사용하여 의상별 개수를 통해 전체 경우의 수를 구함
리스트로 잘 안풀리면 해시로 생각하기
=> [20250120]/PGM/LV2/의상

ShinHeeEul/202501/20 BAJ 외판원 순회.md
[젤다](https://www.acmicpc.net/problem/2098)
360 분
마을을 출발한 사람이 여러 마을을 돌고 다시 마을로 돌아온다. 이때 가장 효율적으로 갔다올 수 있는 방법을 구해라.
비트마스킹 + DP
비트마스킹 하는 템플릿을 외워야겠다. 안 외우니까 시간은 시간대로 쓰고 시간복잡도가 복잡한 코드가 나오더라.
=> [20250120] BAJ / G1 / 외판원 순회 / 신희을

Ho/202501/17 할 일 정하기 1.md, Ho/202501/20 외판원 순회.md
https://www.acmicpc.net/problem/1311
120분
2차원으로  사람마다 일을 처리하는데 걸리는 시간이 주어진다.
어떻게 최소 시간으로 일을 처리할 수 있는지 구하는 문제
비트마스킹과 DP를 사용하는데 이를 최적화해야한다.
정말 많이 접하고 비트마스킹이라는 것을 모르고도 풀 수 있는 실력을 갖고 싶다.
=> [20250117] BAJ/골드1/할 일 정하기1/김득호

Ho/202501/20 외판원 순회.md
https://www.acmicpc.net/problem/2098
240분
1번 노드에서 출발해서 모든 노드를 탐색하고 다시 1번 노드로 돌아오는 최소 비용 구하기
DP + 비트마스킹
DP + 비트마스킹 문제를 최근에 풀었다.
공부좀 해보려고 대표 문제를 풀려고 했는데 아직 너무 멀었다.
백트레킹 바이브로 DP 를 하는데 너무 어렵다. 
아직도 이해가 잘 안간다. 이런 유형을 많이 풀어봐야할 듯 하다.
똑같은 문제를 다시 이해하는것도 좋을듯
=> [20250120] BAJ/골드1/외판원순회/김득호

JaeIn/202501/20 PGM 숫자 변환하기.md
https://school.programmers.co.kr/learn/courses/30/lessons/154538
50분
자연수 x, y, n이 매개변수로 주어질 때, x를 y로 변환하기 위해 필요한 최소 연산 횟수
큐
bfs로 해봤지만 시간초과 , 시초를 잘 생각해야겠슴다
=> [20250120] PGM / LV2 / 숫자 변환하기 / 이재인

ShinHeeEul/202501/21 BAJ 수열과 쿼리 17.md
[젤다](https://www.acmicpc.net/problem/14438)
60 분
수열이 주어진다.
1 a b : a번째 인덱스의 값을 b로 바꾼다.
2 a b : 인덱스 a부터 b까지의 최솟값을 출력해라.
어쩔 세그~
세그 트리 오랜만에 하려니까 헷갈리더라. 중간 중간 이상하게 짠 코드도 많고. 안 까먹게 자주자주 해야겠다.
=> [20250121] BAJ / G1 / 수열과 쿼리 17 / 신희을

Ho/202501/21 수열과 쿼리 17.md
https://www.acmicpc.net/problem/14438
25분
문제에서 제시한 값을 임의로 업데이트를한다.
빠른 시간이내로 자료구조 내부에서 가장 작은 값 출력
세그먼트 트리
점점 익숙해져가는중 !!
=> [20250121] BAJ/G1/수열과 쿼리 17/김득호

kmj-99/202501/21 스카이라인쉬운거.md
https://www.acmicpc.net/problem/1863
60분
도시에서 태양이 질 때에 보이는 건물들의 윤곽을 스카이라인이라고 한다. 스카이라인만을 보고서 도시에 세워진 건물이 몇 채인지 알아 낼 수 있을까? 건물은 모두 직사각형 모양으로 밋밋하게 생겼다고 가정한다.
정확히 건물이 몇 개 있는지 알아내는 것은 대부분의 경우에 불가능하고, 건물이 최소한 몇 채 인지 알아내는 것은 가능해 보인다. 이를 알아내는 프로그램을 작성해 보자.
처음에는 해시를 통해서 접근했는데 잘 풀리지 않음. 그래서 Stack으로 접근해서 풀었다. 뭔가 이전에 값을 나중에도 쓰는 경우 Stack을 활용하면 쉽게 풀 수 있을듯
다양한 자료구조를 빠르게 접근해야겠다.
=> [20250121]/BJ/골드4/1863

JaeIn/202501/21 PGM 뒤에 있는 큰 수 찾기.md
https://school.programmers.co.kr/learn/courses/30/lessons/154539
30분
모든 원소에 대한 뒷 큰수들을 차례로 담은 배열을 return
스택
=> [20250121] PGM / LV2 / 뒤에 있는 큰 수 찾기 / 이재인

JinHyeok/202501/21 BAJ 팰린드롬?.md
https://www.acmicpc.net/problem/10942
40분
팰린드롬인지 구하는문제
DP
오랜만에 팰린드롬 문제풀어본듯
=> [20250121] BAJ / 골드4 / 팰린드롬? / 양진혁

ShinHeeEul/202501/22 BAJ 문자열 제곱.md
[젤다](https://www.acmicpc.net/problem/4354)
60 분
문자열 a * b = ab이다. 이를 응용해 a ^ 4 = aaaa이다. 이때  문자열 S가 주어졌을 때 a(변수) ^ N = S가 되는 N의 최대값을 구해라.
KMP..? 실패 함수 할 때, 일치하지 않을 경우 failure 배열을 참조하는게 아니라, 맨 처음으로 보내버리자.
하 질문 게시판 참고하지 말고 반례 좀 찾아야 되는데, 자꾸 참고하게 되네. 찝찝하다.
=> [20250122] BAJ / P5 / 문자열 제곱 / 신희을

Ho/202501/22 BAJ 문자열 제곱.md
https://www.acmicpc.net/problem/4354
120분
주어지는 문자열을 만들기 위해 내부에 패턴을 몇번 곱해서 만들 수 있는지
주어진 문자열에서 접두사와 동일한 패턴들로 연속되어있는지 확인
아직 구현을 너무 못한다.. 
그냥 멍청이인둣
=> [20250122] BAJ/P5/문자열 제곱/김득호

kmj-99/202501/22 비슷한단어.md
https://www.acmicpc.net/problem/2179
60분
N개의 영단어들이 주어졌을 때, 가장 비슷한 두 단어를 구해내는 프로그램을 작성하시오.
두 단어의 비슷한 정도는 두 단어의 접두사의 길이로 측정한다. 접두사란 두 단어의 앞부분에서 공통적으로 나타나는 부분문자열을 말한다. 즉, 두 단어의 앞에서부터 M개의 글자들이 같으면서 M이 최대인 경우를 구하는 것이다. "AHEHHEH", "AHAHEH"의 접두사는 "AH"가 되고, "AB", "CD"의 접두사는 ""(길이가 0)이 된다.
접두사의 길이가 최대인 경우가 여러 개일 때에는 입력되는 순서대로 제일 앞쪽에 있는 단어를 답으로 한다. 즉, 답으로 S라는 문자열과 T라는 문자열을 출력한다고 했을 때, 우선 S가 입력되는 순서대로 제일 앞쪽에 있는 단어인 경우를 출력하고, 그런 경우도 여러 개 있을 때에는 그 중에서 T가 입력되는 순서대로 제일 앞쪽에 있는 단어인 경우를 출력한다.
완전탐색으로 풀었다.
시간복잡도를 정확하게 계산하자!
=> [20250122]/BJ/골드4/비슷한단어

JinHyeok/202501/22 BAJ 카드정렬하기.md
https://www.acmicpc.net/problem/1715
40분
최소 카드 비교 횟수 구하기
그리디
비교를 할때마다 최고로 낮은 세트와 비교를 해야되기 때문에 pq를 사용하였다.
=> [20250122] BAJ / 골드4 / 카드 정렬하기 / 양진혁

ShinHeeEul/202501/23 LCA2.md
[젤다](https://www.acmicpc.net/problem/11438)
720 분
최소 공통 조상 찾아라. N = 10만이다.
LCA... 연습좀 하자.
희소 배열(Parent)는 [N][logN]이다 까먹지 말길. [N][N]으로 했다가 시초, 공초 겁나 겪었다.
=> [20250123] BAJ / P5 / LCA2 / 신희을

kmj-99/202501/23 하늘에서 별똥별이 빗발친.md
https://www.acmicpc.net/problem/14658
120분
“오빠! 나 얼마만큼 사랑해?”
“널 위해서라면 저기 저 하늘의 별이라도 따다 줄 수 있어. 지금 따줄까?”
“에이, 거짓말!”
“정말이야. 한 번 봐봐!”
욱제는 하늘을 발로 차버렸다. 그랬더니 정말 별이 떨어졌다. 그런데, 정말로 별이 지구로 떨어지기 시작했다. 욱제는 지구를 지키는 정의의 용사가 되기로 결심했다.
“자기야, 나 세계를 지키고 올게. 꼭 돌아올 테니 조금만 기다려줘.”
지구의 파괴를 막기 위해서는 지표면에 떨어지는 별똥별의 수를 최소화해야 한다. 욱제는 커다란 네모난 L*L 크기의 트램펄린을 준비했다. 별똥별이 어디로 떨어질지는 이미 알고 있기 때문에, 욱제는 이 트램펄린으로 최대한 많은 별똥별을 우주로 튕겨낼 계획이다. 하지만 학교 예산으로 트램펄린을 구매하는 욱제는 이 긴급한 와중에도 예산 심의 통과를 기다리느라 바쁘다!
욱제를 도와 세계를 구하자. 최대한 많은 별똥별을 튕겨내도록 트램펄린을 배치했을 때, 지구에는 몇 개의 별똥별이 부딪히게 될까? (별똥별이 떨어지는 위치는 겹치지 않으며 별똥별은 트램펄린의 모서리에 부딪혀도 튕겨나간다!) 트램펄린은 비스듬하게 배치 할 수 없다.
모든 좌표를 돌리면 시간초과가 난다. 그래서 점을 기준으로 저의 개수만큼 사각형을 만들어야한다. 점인 사각형의 변에 있거나 꼭짓점에 있을때 최대 범위의 사각형을 만들 수 있기에 점을 기준으로 사각형을 돌리는 식으로 접근했다.
SOSO
=> [20250123]/BJ/골드3/하늘에서 별똥별이 빗발친다

Ho/202501/24 도로 네트워크.md
https://www.acmicpc.net/problem/3176
180분
문제에서 간선이 주어진다. 
이후 두 노드를 연결할 때 가장 비용이 비싼 간선과 가장 저렴한 간선의
비용을 출력한다.
지수적으로 최소 공통 조상을 찾을 때 함께 문제에서 제시하는 
간선의 비용을 함께 기록하고 이를 이용한다.
질문 게시판 반례가 없었으면 못 품
코드도 너무 길고 지저분함
개선해야함.
=> [20250124] BAJ/P4/도로 네트워크/김득호

kmj-99/202501/16927.md
https://www.acmicpc.net/problem/16927
120분
크기가 N×M인 배열이 있을 때, 배열을 돌려보려고 한다. 배열은 다음과 같이 반시계 방향으로 돌려야 한다.
A[1][1] ← A[1][2] ← A[1][3] ← A[1][4] ← A[1][5]
↓                                       ↑
A[2][1]   A[2][2] ← A[2][3] ← A[2][4]   A[2][5]
↓         ↓                   ↑         ↑
A[3][1]   A[3][2] → A[3][3] → A[3][4]   A[3][5]
↓                                       ↑
A[4][1] → A[4][2] → A[4][3] → A[4][4] → A[4][5]
예를 들어, 아래와 같은 배열을 2번 회전시키면 다음과 같이 변하게 된다.
1 2 3 4       2 3 4 8       3 4 8 6
5 6 7 8       1 7 7 6       2 7 8 2
9 8 7 6   →   5 6 8 2   →   1 7 6 3
5 4 3 2       9 5 4 3       5 9 5 4
<시작>         <회전1>        <회전2>
배열과 정수 R이 주어졌을 때, 배열을 R번 회전시킨 결과를 구해보자.
그냥 쌩구현
Hard
=> [20250125]/BJ/골드5/배열돌리기2

Ho/202501/27 달려라 홍준.md, Ho/202501/28 보석 모으기.md
https://www.acmicpc.net/problem/1306
30분
홍준이가 이동하면서 해당 구간에 있는 가장  큰 수를 출력하기
슬라이딩 윈도우랑 최대힙을 사용했다.
왜 이 문제가 플레5인지 모르겠다.
세그먼트로도 풀 수 있지만 쉽게 슬라이딩으로도 가능한 문제
=> [20250127] BAJ/P5/달려라 홍준/김득호

Ho/202501/31 정점들의 거리.md
https://www.acmicpc.net/problem/1761
120분
문제에서 주어진 트리를 구성하는 두 정점의 거리를 구하는 문제
두 정점의 LCA를 구해서 LCA까지 거리의 합
희소배열을 이용해서 빠르게 구하는 방법 연습중인데
매번하고 어색하고 구현이 어렵다.
=> [20250131] BAJ/P5/정점들의 거리/김득호

kmj-99/31 컨베이어벨트위에로봇.md
https://www.acmicpc.net/problem/20055
120분
벨트가 한 칸 회전하면 1번부터 2N-1번까지의 칸은 다음 번호의 칸이 있는 위치로 이동하고, 2N번 칸은 1번 칸의 위치로 이동한다. i번 칸의 내구도는 Ai이다. 위의 그림에서 1번 칸이 있는 위치를 "올리는 위치", N번 칸이 있는 위치를 "내리는 위치"라고 한다.
컨베이어 벨트에 박스 모양 로봇을 하나씩 올리려고 한다. 로봇은 올리는 위치에만 올릴 수 있다. 언제든지 로봇이 내리는 위치에 도달하면 그 즉시 내린다. 로봇은 컨베이어 벨트 위에서 스스로 이동할 수 있다. 로봇을 올리는 위치에 올리거나 로봇이 어떤 칸으로 이동하면 그 칸의 내구도는 즉시 1만큼 감소한다.
컨베이어 벨트를 이용해 로봇들을 건너편으로 옮기려고 한다. 로봇을 옮기는 과정에서는 아래와 같은 일이 순서대로 일어난다.
벨트가 각 칸 위에 있는 로봇과 함께 한 칸 회전한다.
가장 먼저 벨트에 올라간 로봇부터, 벨트가 회전하는 방향으로 한 칸 이동할 수 있다면 이동한다. 만약 이동할 수 없다면 가만히 있는다.
로봇이 이동하기 위해서는 이동하려는 칸에 로봇이 없으며, 그 칸의 내구도가 1 이상 남아 있어야 한다.
올리는 위치에 있는 칸의 내구도가 0이 아니면 올리는 위치에 로봇을 올린다.
내구도가 0인 칸의 개수가 K개 이상이라면 과정을 종료한다. 그렇지 않다면 1번으로 돌아간다.
종료되었을 때 몇 번째 단계가 진행 중이었는지 구해보자. 가장 처음 수행되는 단계는 1번째 단계이다.
요구사항대로 구현
SOSO
=> [20250131]/BJ/골드5/컨베이어벨트위에로봇

JinHyeok/202501/31 BAJ 운동.md
https://www.acmicpc.net/problem/1956
60분
사이클의 최소 길이를 구하는 문제
플로이드 워셜
플로이드 워셜 알고리즘을 처음봤는데 다음에 응용을 잘해봐야겠다
=> [20250131] BAJ / 골드4 / 운동 / 양진혁

kmj-99/202502/1 입국심사.md
https://school.programmers.co.kr/learn/courses/30/lessons/43238
100분
n명이 입국심사를 위해 줄을 서서 기다리고 있습니다. 각 입국심사대에 있는 심사관마다 심사하는데 걸리는 시간은 다릅니다.
처음에 모든 심사대는 비어있습니다. 한 심사대에서는 동시에 한 명만 심사를 할 수 있습니다. 가장 앞에 서 있는 사람은 비어 있는 심사대로 가서 심사를 받을 수 있습니다. 하지만 더 빨리 끝나는 심사대가 있으면 기다렸다가 그곳으로 가서 심사를 받을 수도 있습니다.
모든 사람이 심사를 받는데 걸리는 시간을 최소로 하고 싶습니다.
입국심사를 기다리는 사람 수 n, 각 심사관이 한 명을 심사하는데 걸리는 시간이 담긴 배열 times가 매개변수로 주어질 때, 모든 사람이 심사를 받는데 걸리는 시간의 최솟값을 return 하도록 solution 함수를 작성해주세요.
탐색해야할 인원이 10억명이 최대라서 이분탐색을 통해 탐색하여 시간복잡도를 줄이는 식으로 접근
이분탐색을 정말 오랜만에 풀어봐서 생각하기 빡셈
=> [20250201]/PGM/LV3/입국심사

JaeIn/202501/31 PGM 혼자서 하는 틱택토.md
https://school.programmers.co.kr/learn/courses/30/lessons/160585
50분
이 게임판이 규칙을 지켜서 틱택토를 진행했을 때 나올 수 있는 게임 상황이면 1을 아니라면 0을 return 하는 문제
구현
쉽지 않구만..
=> [20250131] PGM / LV2 / 혼자서 하는 틱택토 / 이재인

kmj-99/202502/2 24337.md
https://www.acmicpc.net/problem/24337
120분
일직선으로 다양한 높이의 건물들이 N개 존재합니다. 가희는 건물들의 왼쪽에, 단비는 건물들의 오른쪽에 있습니다. 일직선 상에 가희와 단비, 건물들은 아래와 같은 순서로 배치되어 있습니다.
가희의 오른쪽에는 1번 건물이 있습니다.
x가 1이상 N-1이하의 정수일 때, x번 건물의 오른쪽에는 x+1번 건물이 있습니다.
N번 건물의 오른쪽에는 단비가 있습니다.
가희와 단비가 볼 수 있는 건물은 아래와 같습니다.
가희는 1번 건물을 볼 수 있습니다.
k번 건물보다 왼쪽에 있는 건물들이 모두 k번 건물보다 높이가 낮다면, 가희는 k번 건물을 볼 수 있습니다.
단비는 N번 건물을 볼 수 있습니다.
k번 건물보다 오른쪽에 있는 건물들이 모두 k번 건물보다 높이가 낮다면, 단비는 k번 건물을 볼 수 있습니다.
예를 들어, N이 3이고, 1번 건물의 높이가 1, 2번 건물의 높이가 3, 3번 건물의 높이가 2라고 하겠습니다.
[그림 1] 가희와 단비, 그리고 건물들의 배치
가희가 볼 수 있는 건물과 단비가 볼 수 있는 건물의 수는 각각 2개입니다. 이를 각각 노란색, 연보라색으로 표시하겠습니다.
[좌] 가희가 볼 수 있는 건물 [우] 단비가 볼 수 있는 건물
가희가 3번 건물을 볼 수 없는 이유는 3번 건물 왼쪽에 있는 2번 건물의 높이가 3번 건물보다 높기 때문입니다. 그리고, 단비가 1번 건물을 볼 수 없는 이유는 1번 건물보다 오른쪽에 있는 2번 건물과 3번 건물이 1번 건물보다 높기 때문입니다.
가희와 단비 사이에 있는 건물의 개수 N과 …
=> [20250202]/BJ/골드3/24337

kmj-99/202502/3 15683.md
https://www.acmicpc.net/problem/15683
120분
<p style="box-sizing: border-box; border-radius: 0px !important; margin: 0px 0px 10px; color: rgb(85, 85, 85); font-family: &quot;Open Sans&quot;, -apple-system, &quot;system-ui&quot;, &quot;Segoe UI&quot;, &quot;Apple SD Gothic Neo&quot;, &quot;Noto Sans CJK KR&quot;, &quot;Noto Sans KR&quot;, 나눔바른고딕, 나눔고딕, 맑은고딕, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; …
=> [20250203]/BJ/골드3/15683

Ho/202502/1 로봇 청소기.md
https://www.acmicpc.net/problem/4991
150분
랜덤한 위치에 생성되는 먼지를 최소거리로 움직여서 청소하는 문제
BFS를 이용해서 각 정점을 이동하는 최소거리를 구한다.
구해진 정보를 이용해서 외판원 순회 ㄱㄱ
어려움...
=> [20250203] BAJ/G1/로봇 청소기/김득호

ShinHeeEul/202502/03 BAJ 골드1 로봇 청소기.md
[링크](https://www.acmicpc.net/problem/4991)
360 분
로봇 청소기가 돌아간다. 장애물은 건너뛸 수 없다. 여러 군데에 먼지가 흩뿌려져있는데 최단 거리로 이동해서 모든 먼지를 흡입해라.
BFS로 먼지들 간의 거리를 구하고 나면, 외판원 순회랑 같은 문제가 된다.
비트 마스킹 재귀로 하는 법좀 연습좀 하자. 이거 못해서 2시간 잡아먹혔다.
=> [20250203] BAJ / G1 / 로봇 청소기 / 신희을

JinHyeok/202502/03 BAJ 네트워크 연결.md
https://www.acmicpc.net/problem/1922
60분
모든 컴퓨터를 연결시키는 최소값
mst, kruskal, union find
MST, KRUSKAL, UNION FIND 문제를 처음봤는데
해설을 보니 되게 신기하고 어떻게 푸는 건지 감이 잡히긴했다.
=> [20250203] BAJ / 골드4 / 네트워크 연결 / 양진혁

ShinHeeEul/202502/04 BAJ P4 수열과 쿼리 21.md
[득호형 컷](https://www.acmicpc.net/problem/16975)
90 분
길이가 N인 수열 A1, A2, ..., AN이 주어진다. 이때, 다음 쿼리를 수행하는 프로그램을 작성하시오.
1 i j k: Ai, Ai+1, ..., Aj에 k를 더한다.
2 x: Ax 를 출력한다.
느리게 갱신되는 세그먼트 트리 기본 문제
오랜만에 다시 구현하려고 하니 잘 기억이 나지 않아 한참 해맸다. 나중에 코테에서 나와도 풀 수 있을 정도로 숙달시켜놓자.
=> [20250204] BAJ / P4 / 수열과 쿼리 21 / 신희을

JinHyeok/202502/05 BAJ 알고스팟.md
https://www.acmicpc.net/problem/1261
50분
좌표 끝까지 가기 위한 벽 부수는 개수
다익스트라
예전에는 못풀었던 문제
=> [20250205] BAJ / 골드4 / 알고스팟 / 양진혁

Ho/202502/5 전깃줄2.md
https://www.acmicpc.net/problem/2568
150분
엉켜있는 전깃줄을 풀기위해 제거해야하는 최소 값을 구하는 문제
LIS를 이용해서 최장 수열을 구한다.
이때 n^2 이아닌 nLogN 방식을 사용해야한다.
코테에서 뚜둘겨 맞고 nlogn 방식을 공부해서 풀었다.
다음에는 틀리지 말자
=> [20250205] BAJ/P5/전깃줄2/김득호

JaeIn/202502/03 PGM 이진 변환 반복하기.md, JaeIn/202502/04 PGM 단어 변환.md
https://school.programmers.co.kr/learn/courses/30/lessons/70129
20분
이진 변환의 횟수와 변환 과정에서 제거된 모든 0의 개수 구하기
구현
2진법으로 변환하는게 잘 떠오르지 않음..
=> [20250203] PGM / LV2 / 이진 변환 반복하기 / 이재인

JaeIn/202502/04 PGM 단어 변환.md, JaeIn/202502/05 PGM 여행경로.md
https://school.programmers.co.kr/learn/courses/30/lessons/43163
50분
두 개의 단어 begin, target과 단어의 집합 words가 있습니다. 아래와 같은 규칙을 이용하여 begin에서 target으로 변환하는 가장 짧은 변환 과정
bfs
예전에 풀었던건데 너무 오래걸림.. 예전에 풀었던 해설 참고..
=> [20250204] PGM / LV3 / 단어 변환 / 이재인

JaeIn/202502/05 PGM 여행경로.md
https://school.programmers.co.kr/learn/courses/30/lessons/43164
50분
방문하는 공항 경로를 배열에 담아 return 
dfs
시간은 비슷했는데 풀긴 풀었네 어렵다..
=> [20250205] PGM / LV3 / 여행 경로 / 이재인

JinHyeok/202502/07 BAJ 뮤탈리스크.md
https://www.acmicpc.net/problem/12869
50분
최적의 공격 횟수 구하기
BFS
=> [20250207] BAJ / 골드4 / 뮤탈리스크 / 양진혁

Ho/202502/7 게임.md
https://www.acmicpc.net/problem/1103
120분
(0,0)에서 시작해서 격자판에 적힌 숫자만큼 상,하,좌,우로 움직이면서 격자 내부에서
얼마나 오래 살아남을 수 있는지 구한다.
백트래킹을 이용한 DP를 구현하고 
사이클이 발생하지는 않는지 판단하는 것이 핵심
사이클...
=> [20250207] BAJ/G2/게임/김득호

JaeIn/202502/07 PGM 전력망을 둘로 나누기.md
https://school.programmers.co.kr/learn/courses/30/lessons/86971
55분
두 전력망이 가지고 있는 송전탑 개수의 차이를 return
dfs
풀었던건데 한참 걸리네.. 다시 풀어봐야될듯
=> [20250207] PGM / LV2 / 전력망을 둘로 나누기 / 이재인

kmj-99/202502/10 동전분배.md
https://www.acmicpc.net/problem/1943
200분
윤화와 준희는 솔선수범하여 쓰레기를 줍는 착한 일을 하였다. 원장선생님께서는 윤화와 준희를 칭찬하시고 과자나 사 먹으라고 하시며 동전 몇 개를 윤화와 준희에게 건네 주었다.
그런데 돈을 받은 윤화와 준희는 좋아하기보다 고민에 빠지고 말았다. 원장선생님께 받은 이 돈을 어떻게 나누어 할지 고민에 빠진 것이다. 두 사람 모두 상대방이 자기보다 1원이라도 더 받는 것은 도저히 인정할 수 없어 한다. 따라서 돈을 똑같이 둘로 나누어 가져야 두 사람이 모두 만족할 수 있게 된다.
하지만 두 사람에게 돈을 똑같이 나누는 것이 불가능한 경우도 있다. 예를 들어 500원짜리 1개와 50원짜리 1개를 받았다면, 이 돈을 두 사람이 똑같이 나누어 가질 수는 없다. 물론 동전을 반으로 잘라서 나누어 가질 수도 있겠지만 그러면 돈으로서의 가치를 잃기 때문에 그렇게 할 수는 없다.
이제 우리가 할 일은 다음과 같다. 원장 선생님께서 N가지 종류의 동전을 각각 몇 개씩 주셨을 때, 그 돈을 반으로 나눌 수 있는지 없는지 판단하는 것이다.
dp와 이분탐색을 혼합한 풀이
이분탐색까지 고려하니까 너무 어렵다.
=> [20250210]/BJ/골드2/동전분배/김민중

JaeIn/202502/10 PGM 퍼즐 게임 챌린지.md
https://school.programmers.co.kr/learn/courses/30/lessons/340212
50분
제한 시간 내에 퍼즐을 모두 해결하기 위한 숙련도의 최솟값을 정수로 return
이분탐색
이분탐색으로 풀어야되는게 감이 바로 안온다.. 어렵
=> [20250210] PGM / LV2 / 퍼즐 게임 챌린지 / 이재인

Ho/202502/10 계단수.md
https://www.acmicpc.net/problem/1562
500분
N자리에서 0~9를 최소 하나를  포함하는 계단수를 몇개 만들 수 있는가
비트마스킹을 통해 현재 사용한 숫자를 체크한다. 
마지막 자리를 0~9까지 바꾸면서 이전의 i-1번째, i+1 번째에서  올 수 있는 경우를 더하면서 풀이한다.
너무 어렵다 솔직히 아직 이해도 못했다.
다음에 이해해서 풀이하면 제대로 올려야지
=> [20250210] BAJ/G1/계단 수/김득호

Ho/202502/11 XOR.md
https://www.acmicpc.net/submit/12844/89920369
500분
느린 세그먼트 갱신 문제
풀이할 힘이 없다...
많이 풀면서 익숙하게 만들어야겠다...
=> [20250211] BAJ/P3/XOR/김득호

JinHyeok/202502/11 BAJ 물통.md
https://www.acmicpc.net/problem/2251
60분
경우의 수 구하기
BFS, DFS 둘다될듯
구현을 못했음 방법은 쉬운데
=> [20250211] BAJ / 골드4 / 물통 / 양진혁

JaeIn/202502/12 테이블 해시 함수.md
https://school.programmers.co.kr/learn/courses/30/lessons/147354?language=python3
30분
요구사항대로 정렬한 후 xor 연산하는 문제
구현
비트 연산을 어떻게 하는지 까먹어서 참고함
=> [20250212] PGM / LV2 / 테이블 해시 함수 / 이재인

kmj-99/202502/12 여행가자.md
https://www.acmicpc.net/problem/1976
120분
동혁이는 친구들과 함께 여행을 가려고 한다. 한국에는 도시가 N개 있고 임의의 두 도시 사이에 길이 있을 수도, 없을 수도 있다. 동혁이의 여행 일정이 주어졌을 때, 이 여행 경로가 가능한 것인지 알아보자. 물론 중간에 다른 도시를 경유해서 여행을 할 수도 있다. 예를 들어 도시가 5개 있고, A-B, B-C, A-D, B-D, E-A의 길이 있고, 동혁이의 여행 계획이 E C B C D 라면 E-A-B-C-B-C-B-D라는 여행경로를 통해 목적을 달성할 수 있다.
도시들의 개수와 도시들 간의 연결 여부가 주어져 있고, 동혁이의 여행 계획에 속한 도시들이 순서대로 주어졌을 때 가능한지 여부를 판별하는 프로그램을 작성하시오. 같은 도시를 여러 번 방문하는 것도 가능하다.
bfs를 활용해서 경로를 모두 탐색하여 가능한 경로인지 접근
유니온 파인드를 이용해서 같은 루트라면 서로 이동할 수 있다라는 식으로 접근하면 더 효율적으로 가능할 듯
유니온 파인드 한 번 적용해보자
=> [20250212]/BJ/골드4/여행가자/김민중

JinHyeok/202502/12 BAJ 탑.md
https://www.acmicpc.net/problem/2493
40분
=> [20250212] BAJ / 골드5 / 탑 / 양진혁

Ho/202502/11 XOR.md, Ho/202502/12 보호필름.md
https://swexpertacademy.com/main/code/problem/problemList.do?
120분
보호필름 안전검사 통과하는지 판단하는 문제
조합을 두번 구했음
구현 좀 연습하자
=> [20250212] SWEA/??/보호필름/김득호

Ho/202502/14 트리와쿼리2.md
https://www.acmicpc.net/problem/13511
120분
두개의 정점의 거리 구하기
두개의 정점에서 k번째 정점 위치 구하기
경로의 비용을 어떻게 출력? LCA를 구해서 둘의 LCA 까지 비용을 더해서 출력하면된다.LCA가 둘 중 하나인 경우 조심. 아니면 A -> A인 경우u -> v k번째 정점은 어떻게 구하죠?1.LCA 높이 맞춰주는 과정 연산2. 높이를 맞춘 이후 희소 배열을 이용해서 올라가는 과정에서 2 ^ i 씩 움직임1번 + 2 ^ i 가 k를 넘어가는 순간을 체크1. u -> LCA 까지 거리 구하고2. v -> LCA 까지 거리 구하고1 + 2 = A일때k가 u -> LCA = B인경우 B < k 라면A - (B + (K - B)) =C 를 구한다.v 에서 C만큼 떨어진 녀석이 k만큼 떨어진 정점이다.
더 빠르게 구현하고 잘 응요하기
=> [20250214] BAJ/P3/트리와 쿼리/김득호

kmj-99/202502/14 횡단보도.md
https://www.acmicpc.net/problem/24042
300분
당신은 집으로 가는 도중 복잡한 교차로를 만났다! 이 교차로에는 사람이 지나갈 수 있는 
$N$ 개의 지역이 있고 그 지역 사이를 잇는 몇 개의 횡단보도가 있다. 모든 지역은 횡단보도를 통해 직, 간접적으로 연결되어 있다. 편의상 
$N$ 개의 지역을 
$1$부터 
$N$까지로 번호를 붙이자.
당신은 이미 멀리서 교차로의 신호를 분석했기 때문에 횡단보도에 파란불이 들어오는 순서를 알고 있다. 횡단보도의 주기는 총 
$M$ 분이며 
$1$분마다 신호가 바뀐다. 각 주기의 
$1+i (0 \le i < M)$ 번째 신호는 
$i, M+i, 2M+i, 3M+i, \cdots$ 분에 시작해서 
$1$분 동안 
$A_i$번 지역과 
$B_i$번 지역을 잇는 횡단보도에 파란불이 들어오고, 다른 모든 횡단보도에는 빨간불이 들어온다. 한 주기 동안 같은 횡단보도에 파란불이 여러 번 들어올 수 있다.
횡단보도에 파란불이 들어오면 당신은 해당 횡단보도를 이용하여 반대편 지역으로 이동할 수 있으며 이동하는 데 
$1$분이 걸린다. 횡단보도를 건너는 도중에 신호가 빨간불이 되면 안되기 때문에 신호가 
$s \sim e$ 시간에 들어온다면 반드시 
$s \sim e-1$ 시간에 횡단보도를 건너기 시작해야 한다.
횡단보도와 신호의 정보가 주어질 때, 시간 
$0$분 에서 시작해서 
$1$번 지역에서 
$N$번 지역까지 가는 최소 시간을 구하는 프로그램을 작성하여라.
다익스트라를 응용해서 푼다. 다익스트라로 접근하되 cost를 더하는 부분을 문제에 나오는 …
=> [20250214]/BJ/골드1/횡단보도/김민중

JinHyeok/202502/14 BAJ 여행가자.md
https://www.acmicpc.net/problem/1976
60분
여행가능여부 구하기
유니온파인드
dfs도 되지만 유니온파인드로도 되고
요즘 비트마스킹 유니온파인드 쪽을 공부해야겠다;
=> [20250214] BAJ / 골드4 / 여행가자 / 양진혁

JaeIn/202502/ 14 스킬트리.md
https://school.programmers.co.kr/learn/courses/30/lessons/49993#fn1
20분
가능한 스킬트리 개수를 return
구현
간단한 문제였습니다.
=> [20250214] PGM / LV2 / 스킬트리 / 이재인

Ho/202502/17 프로세서 연결하기.md
https://swexpertacademy.com/main/code/problem/problemSubmitHistory.do?contestProbId=AV4suNtaXFEDFAUf
180분
직선으로 프로세서 연결하기
백트래킹, 완전탐색
... 빨리 풀수있도록 노력하자
=> [20250217] SWEA/??/프로세서 연결하기/김득호

kmj-99/202502/17 계단수
https://www.acmicpc.net/problem/1562
300분
45656이란 수를 보자.
이 수는 인접한 모든 자리의 차이가 1이다. 이런 수를 계단 수라고 한다.
N이 주어질 때, 길이가 N이면서 0부터 9까지 숫자가 모두 등장하는 계단 수가 총 몇 개 있는지 구하는 프로그램을 작성하시오. 0으로 시작하는 수는 계단수가 아니다.
비트마스킹을 이용해 풀이
비트마스킹 아직 어렵다.
=> [20250217]/BJ/골드1/계단수/김민중

JaeIn/202502/18 PGM N-Queen.md
=> [20250218] PGM / LV2 / N-Queen / 이재인

Ho/202502/18 키 순서.md
https://www.acmicpc.net/problem/2458
40분
키 순서를 비교하는 연산이 문제에서 m번 주어진다.
m번의 연산 후 자신이 정확히 반에서 몇번째인지 알 수 있는
사람이 몇명인가요?
키를 비교한 사람을 단방향 간선으로 연결해서 그래프를 만들었다.
각 사람을 정점으로 바라보고 나보다 큰사람은 OutPath로 관리하고
나보다 작은 사람은 InPath로 들어는 간선으로 연결했다.
InPath 간선을 반대로 연결해서 이동 가능한 정점을 탐색한다.
outPath는 정방향으로 탐색후 모든 정점을 방문했다면 자신이 몇번째인지 알 수 있다.
전역변수 관리 잘하기
그리고 풀이가 생각보다 늦게 떠올랐다 빠르게 생각하기
=> [20250218] BAJ/G4/키 순서/김득호

JinHyeok/202502/18 BAJ 골드5 CCW.md
https://www.acmicpc.net/problem/11758
분
CCW 알고리즘을 오랜만에 봐서 회상할 겸 풀이보고 익혔다.
=> [20250218] BAJ / 골드5 / CCW / 양진혁

Ho/202502/19 ladder2.md
https://swexpertacademy.com/main/code/problem/problemDetail.do?contestProbId=AV14BgD6AEECFAYh
30분
사다리타고 최단거리로 바닥에 내려가는 경우
단순 dfs
문제좀 꼼꼼히 읽자 ;;; 전역변수... 진짜
=> [20250219] SWEA/D4/LADDER2/김득호

JaeIn/202502/21 PGM 프렌즈4블록.md
https://school.programmers.co.kr/learn/courses/30/lessons/17679?
60분
지워지는 블록은 모두 몇 개인지 판단하는 프로그램
구현
구현은 역시 어려워...
=> [20250221] PGM / LV2 / 프렌즈4블록 / 이재인

Ho/202502/21 병사관리.md
https://swexpertacademy.com/main/solvingProblem/solvingProblem.do?contestProbId=AXxODdXKQAADFASZ&categoryId=AZTS_npqcGvHBINJ&categoryType=BATTLE
240분
병사를 고용하고 해고하면서
병사들이 가지고 있는 고유 점수를 업데이트한다.
이후 병사 점수가 높은 녀석을 출력한다.
연결리스트를 
팀과 점수별로 관리하면서 
update 할 때 똑 떼서 똑 붙여야겠다.
다시 풀면서 사고력 키우기
=> [20250221] SWEA/PRO/병사관리/김득호

JinHyeok/202502/21 PGM 압축.md
https://school.programmers.co.kr/learn/courses/30/lessons/17684
60분
예전에 못푼 문제 같았는데 아직 어렵다..
=> [20250221] PGM / LV2 / 압축 / 양진혁

kmj-99/202502/23 1의개수세기
https://www.acmicpc.net/problem/9527
300분
두 자연수 A, B가 주어졌을 때, A ≤ x ≤ B를 만족하는 모든 x에 대해 x를 이진수로 표현했을 때 1의 개수의 합을 구하는 프로그램을 작성하시오.
DP와 비트마스킹을 혼합해서 풀어야 한다. 
비트마스킹은 DP와 혼합해서 써야한다.
=> [20250223]/BJ/골드1/1의개수세기/김민중

kmj-99/202502/24 1의개수세기.md
https://www.acmicpc.net/problem/9527
분
두 자연수 A, B가 주어졌을 때, A ≤ x ≤ B를 만족하는 모든 x에 대해 x를 이진수로 표현했을 때 1의 개수의 합을 구하는 프로그램을 작성하시오.
즉, f(x) = x를 이진수로 표현 했을 때 1의 개수라고 정의하고, 아래 식의 결과를 구하자.
dp와 비트마스킹을 통해 해결
풀이보고 풀었던 거 다시 풀어봄.
=> [20250224]/BJ/골드2/1의개수세기/김민중

ShinHeeEul/202502/25 BAJ P5 부분 배열 고르기.md
https://www.acmicpc.net/problem/2104
120 분
크기가 N(1 ≤ N ≤ 100,000)인 1차원 배열 A[1], …, A[N]이 있다. 어떤 i, j(1 ≤ i ≤ j ≤ N)에 대한 점수는, (A[i] + … + A[j]) × min{A[i], …, A[j]}가 된다. 즉, i부터 j까지의 합에 i부터 j까지의 최솟값을 곱한 것이 점수가 된다.
배열이 주어졌을 때, 최대의 점수를 갖는 부분배열을 골라내는 프로그램을 작성하시오.
세그 트리에 최솟값과 최솟값을 갖는 인덱스를 함께 저장한다.
최솟값을 갖는 인덱스를 기준으로 구간을 분할하고, 해당 구간의 넓이를 계산한다.
해당 구간을 기준으로 다시 최솟값을 찾는 로직을 반복한다.
히스토그램이랑 같은 문젠데, 히스토그램 때도 못풀어서 해설 봤었는데 이번에도 보게 되었다.. 세그 트리에 업데이트 기준과 안의 값을 다르게 할 수 있음도 항시 염두해두자!
=> [20250225] BAJ / P5 / 부분 배열 고르기 / 신희을

Ho/202502/25 부분배열 구하기.md
https://www.acmicpc.net/problem/2104
120분
전 구간에서 가장 작은 값과 구간의 합의 곱중 가장 큰 값을구하기
세그먼트 트리에 저장하는 인덱스를 작은 값으로 갱신하고 
구간 범위를 작은 인덱스를 기준으로 왼쪽 오른쪽으로 분할히면서 구간 탐색
이전에도 풀이를 봤었는데 다시 봐도 생각하지 못하는건 자주 보라는거겟죠?
=> [20250225] BAJ/P5/부분배열 구하기/김득호

ShinHeeEul/202502/26 BAJ P5 찾기.md
https://www.acmicpc.net/problem/1786
40 분
입력으로 T와 P라는 문자열이 주어진다. 이때 T에서 P라는 문자열이 몇 번 출현 하는지와 출현하는 시작 위치를 출력하라.
KMP 기본 문제
KMP도 슬슬 익숙해져가는 것 같다. 오랜만에 풀어봤는데, 헤매긴 했는데 풀긴 하니까 뿌듯하더라.
=> [20250226] BAJ / P5 / 찾기 / 신희을

ShinHeeEul/202502/27 BAJ P5 한동이는 영업사원!.md
https://www.acmicpc.net/problem/8012
60 분
트리가 주어지고, 방문할 노드가 순서대로 주어진다. 순서대로 방문한다 할 때 전부 방문할 수 있는 최소 길이를 구하라.
현재 위치와 목적지를 LCA하면 LCA까지의 거리가 나오므로 * 2해서 누적하자.
전에 LCA 실수도 많이 했는데, 이번엔 한번에 통과해서 기분 좋다 ㅎ 실력이 성장한 것 같다.
=> [20250227] BAJ / P5 / 한동이는 영업사원! / 신희을

Ho/202502/28 불 켜기.md
https://www.acmicpc.net/problem/11967
60분
2차원에서 불이 켜져있는 방의 수를 찾는 문제
BFS로 방문하면서 늦게 불이 켜지는 방을 대비해서 이동가능한 경우를
체크해놓고 불이 켜지면 Q에 삽입한다.
오랜만에  BFS
=> [20250228] BAJ/G2/불 켜기/김득호

JinHyeok/202502/28 BAJ 합분해.md
https://www.acmicpc.net/problem/2225
30분
dp
=> [20250228] BAJ / 골드5 / 합분해 / 양진혁

JaeIn/202503/03 PGM 무인도 여행.md
https://school.programmers.co.kr/learn/courses/30/lessons/154540
50분
각 섬에서 최대 며칠씩 머무를 수 있는지 배열에 오름차순으로 담아 return
dfs
예전에 풀었지만 실패.. 다시 풀어보겠습니다
=> [20250303] PGM / LV2 / 무인도 여행 / 이재인

JinHyeok/202503/03 BAJ 이진 검색 트리.md
https://www.acmicpc.net/problem/5639
50분
이진 트리 순회하는 문제
BST
진짜 예전에 했던 방법인거 같은데 까먹었다....
=> [20250303] BAJ / 골드4 / 이진 검색 트리  / 양진혁

kmj-99/202503/4 1238.md
https://www.acmicpc.net/problem/1238
120분
N개의 숫자로 구분된 각각의 마을에 한 명의 학생이 살고 있다.
어느 날 이 N명의 학생이 X (1 ≤ X ≤ N)번 마을에 모여서 파티를 벌이기로 했다. 이 마을 사이에는 총 M개의 단방향 도로들이 있고 i번째 길을 지나는데 Ti(1 ≤ Ti ≤ 100)의 시간을 소비한다.
각각의 학생들은 파티에 참석하기 위해 걸어가서 다시 그들의 마을로 돌아와야 한다. 하지만 이 학생들은 워낙 게을러서 최단 시간에 오고 가기를 원한다.
이 도로들은 단방향이기 때문에 아마 그들이 오고 가는 길이 다를지도 모른다. N명의 학생들 중 오고 가는데 가장 많은 시간을 소비하는 학생은 누구일지 구하여라.
다익스트라를 정방향, 역방향으로 2번 적용해서 풀이
다익스트라 hard
=> [20250304]/BJ/골드3/1238/김민중

ShinHeeEul/202503/04 BAJ P4 순열.md
https://www.acmicpc.net/problem/1849
70 분
1부터 N까지의 수들이 한 번씩 쓰인 수열이 있다. 그 수열에서 i 앞에 있는 수 들 중, i보다 큰 수들의 개수를 A[i]라고 정의하자. A[i]가 주어져 있을 때, 원래 수열을 구하는 프로그램을 작성하여라. 
예를 들어 `5 0 1 2 1 2 0 0`이라는 값은 `2 7 3 5 4 1 8 6`에서 i 앞에 있는 수 중 i보다 큰 수들의 갯수이다.
즉 `2 7 3 5 4 1 8 6`에서 현재 위치의 값보다 앞에 있는 값들 중 나보다 더 큰 값이 몇 개인지를 센 것이 입력으로 주어진다는 것이다.
2보다 앞에 있는 것은 없으므로 A[2] = 0
7보다 앞에 있는 값은 2밖에 없으므로 A[7] = 0
3보다 앞에 있는 값들 중 7이 3보다 크므로 A[3] = 1
5보다 앞에 있는 값들 중 7이 5보다 크므로 A[5] = 1
4보다 앞에 있는 값들 중 5, 7이 4보다 크므로 A[4] = 2
....
이렇게 하고 A[1], A[2], A[3], A[4] ... 를 계산하면 `5 0 1 2 1 2 0 0`이 나온다. 이를 역으로 계산해서 `2 7 3 5 4 1 8 6`을 도출해내는게 문제이다.
세그먼트 트리의 리프 노드 값을 전부 비워둔다. 위 노드들은 해당 범위에 빈공간이 몇개가 있는 지를 저장한다.
1부터 N까지 순차적으로 값을 집어넣는다. 이때 탑 다운 방식으로 루트 노드부터 내려온다.
1) A[i]가 좌측 자식 노드(left)보다 값보다 크거나 같다면, 좌측 노드 범위만으로는 A[i]를 만족시킬 수 없다. 그렇기에 A[i] - …
=> [20250304] BAJ / P4 / 순열 / 신희을

JinHyeok/202503/04 BAJ Fly me to the Alpha Centauri.md
https://www.acmicpc.net/problem/1011
40분
=> [20250304] BAJ / 골드5 / Fly me to the Alpha Centauri / 양진혁

JaeIn/202503/05 PGM 교점에 뱔 만들기.md
https://school.programmers.co.kr/learn/courses/30/lessons/87377
40분
교점 사이에 별 찾아서 return
구현
막막하다가 밑에 참고보고 해결.. 잘 읽어봐야겠다
=> [20250305] PGM / LV2 / 교점에 별 만들기 / 이재인

JinHyeok/202503/05 BAJ 제곱수 찾기.md
https://www.acmicpc.net/problem/1025
50분
가장 큰 제곱수 찾기
브루트포스
조건찾는데 시간 걸림
=> [20250305] BAJ / 골드5 / 제곱수 찾기 / 양진혁

Ho/202503/5 나무 심기.md
https://swexpertacademy.com/main/code/userProblem/userProblemDetail.do?contestProbId=AYFofW8qpXYDFAR4
180분
일단 다시 작성할게여
=> [20250305] SWEA/D2/나무 심기/김득호

ShinHeeEul/202503/05 SWEA D5 무선 충전.md
https://swexpertacademy.com/main/code/problem/problemDetail.do?contestProbId=AWXRDL1aeugDFAUo
40 분
2명의 사람이 정해진 루트를 따라서 이동한다. 이동 중 무선 전파기 범위 안에 들어오면 초당 p의 에너지를 얻을 수 있다. 2명이 같은 전파기에서 에너지를 얻으면 에너지는 절반이 된다. 이때 최대한 많이 에너지를 모으는 방법은?
구현
생각보다 구현 능력이 올랐을지도..?
=> [20250305] SWEA / D5 / 무선 충전기 / 신희을

JaeIn/202503/07 PGM 입국심사.md
https://school.programmers.co.kr/learn/courses/30/lessons/43238
45분
모든 사람이 심사를 받는데 걸리는 시간의 최솟값
이분탐색
한쪽 심사대만 사용하도 된다는 것을 생각 못해서 오래 걸렸다.. 문제를 잘 이해하자..
=> [20250307] PGM / LV3 / 입국심사 / 이재인

ShinHeeEul/202503/10 BAJ G1 Balanced Lineup.md
https://www.acmicpc.net/problem/6213
30 분
기본 세그먼트 트리, 최대 세그 트리와 최소 세그 트리를 두고 조회를 한다. 혹은 클래스를 활용해 세그 트리 한 개로 구현할 수도 있다.
오랜만에 기본 세그 트리 문제 풀었다.
=> [20250310] BAJ / G1 / Balanced Lineup / 신희을

kmj-99/202503/10 10800.md
https://www.acmicpc.net/problem/10800
200분
지훈이가 최근에 즐기는 컴퓨터 게임이 있다. 이 게임은 여러 플레이어가 참여하며, 각 플레이어는 특정한 색과 크기를 가진 자기 공 하나를 조종하여 게임에 참여한다. 각 플레이어의 목표는 자기 공보다 크기가 작고 색이 다른 공을 사로잡아 그 공의 크기만큼의 점수를 얻는 것이다. 그리고 다른 공을 사로잡은 이후에도 본인의 공의 색과 크기는 변하지 않는다. 다음 예제는 네 개의 공이 있다. 편의상 색은 숫자로 표현한다.
이 경우, 2번 공은 다른 모든 공을 사로잡을 수 있다. 반면, 1번 공은 크기가 더 큰 2번 공과 색이 같은 3번 공은 잡을 수 없으며, 단지 4번 공만 잡을 수 있다. 
공들의 색과 크기가 주어졌을 때, 각 플레이어가 사로잡을 수 있는 모든 공들의 크기의 합을 출력하는 프로그램을 작성하시오. 
누적합을 이용해서 풀었다. 공들을 오름차순 하고 0~N까지의 공을 탐색하면서 누적합을 사용하여 값들을 갱신했다. 각 경우마다 정답을 도출할때는 각 색상의 합을 빼주었다. 이러면 같은 색상, 같은 사이즈 일 경우 모두 대응할 수 있다.
누적합에 대한 감이 잡힌 거 같다.
=> [20250310]/BJ/골드2/10800/김민중

JinHyeok/202503/10 BAJ 공약수.md
https://www.acmicpc.net/problem/2436
40분
최대공약수 최대공배수가 되는 값 구하기
=> [20250310] BAJ / 골드5 / 공약수 / 양진혁

Ho/202503/10 Balanced Lineup.md
https://www.acmicpc.net/problem/6213
30분
가장 큰 소랑 가작 작은 소의 키 차이를 구하는  문제
완전 기본세그
그래도 세그먼트니까 중~ 을 드릴게요!
근데 솔직히 구현하다 한번 버벅임 ...
=> [20250310] BAJ/G1/Balanced_LineUp/김득호

JinHyeok/202503/11 BAJ 보물섬.md
https://www.acmicpc.net/problem/2589
50분
최단거리 시간 구하는 문제
BFS
=> [20250311] BAJ / 골드5 / 보물섬 / 양진혁

JaeIn/202503/11 PGM 파일명 정렬.md
https://school.programmers.co.kr/learn/courses/30/lessons/17686
45분
파일명에 포함된 숫자를 반영한 정렬 기능을 저장소 관리 프로그램
정
isdigit같은 문자열 함수를 알지 못해서 다른 사람의 풀이를 참고 , 정렬에 대해서 더 풀어봐야겠다
=> [202503011] PGM / LV2 / 파일명 정렬/ 이재인

ShinHeeEul/202503/12 BAJ P5 순환 순열.md
https://www.acmicpc.net/problem/12104
30 분
두 바이너리 문자열 A와 B가 주어졌을 때, A와 XOR 했을 때, 0이 나오는 B의 순환 순열의 개수를 구하는 프로그램을 작성하시오.
순환 순열이란 순열 P = P0, P1, ..., PN-1이 있을 때, 왼쪽으로 k번 순환 이동시킨 순열이다. 즉, P를 k번 순환 이동 시키면, $P_i$ -> $P_{i + k mod n}$ 이 된다.
첫째 줄에 A와 XOR했을 때, 0이 나오는 B의 순환 순열의 개수를 출력한다.
A를 두 배로 늘려주고 마지막만 빼준다. 예를 들어 A가 101이라면 10110으로 만들어준다.
그리고 A와 B의 kmp를 구해 겹치는 만큼 세준다.
kmp 기본 문제다. 이제 슬슬 응용 문제도 연습해야지
=> [20250312] BAJ / P5 / 순환 순열 / 신희을

JaeIn/202503/12 BAJ 최단거리.md
https://www.acmicpc.net/problem/1753
50분
최단거리를 구하는 문제
다익스트라
우선순위 큐에 대해 복습겸
=> [20250312] BAJ / 골드4 / 최단거리 / 이재인

kmj-99/202503/12 13460.md
https://www.acmicpc.net/problem/13460
100분
스타트링크에서 판매하는 어린이용 장난감 중에서 가장 인기가 많은 제품은 구슬 탈출이다. 구슬 탈출은 직사각형 보드에 빨간 구슬과 파란 구슬을 하나씩 넣은 다음, 빨간 구슬을 구멍을 통해 빼내는 게임이다.
보드의 세로 크기는 N, 가로 크기는 M이고, 편의상 1×1크기의 칸으로 나누어져 있다. 가장 바깥 행과 열은 모두 막혀져 있고, 보드에는 구멍이 하나 있다. 빨간 구슬과 파란 구슬의 크기는 보드에서 1×1크기의 칸을 가득 채우는 사이즈이고, 각각 하나씩 들어가 있다. 게임의 목표는 빨간 구슬을 구멍을 통해서 빼내는 것이다. 이때, 파란 구슬이 구멍에 들어가면 안 된다.
이때, 구슬을 손으로 건드릴 수는 없고, 중력을 이용해서 이리 저리 굴려야 한다. 왼쪽으로 기울이기, 오른쪽으로 기울이기, 위쪽으로 기울이기, 아래쪽으로 기울이기와 같은 네 가지 동작이 가능하다.
각각의 동작에서 공은 동시에 움직인다. 빨간 구슬이 구멍에 빠지면 성공이지만, 파란 구슬이 구멍에 빠지면 실패이다. 빨간 구슬과 파란 구슬이 동시에 구멍에 빠져도 실패이다. 빨간 구슬과 파란 구슬은 동시에 같은 칸에 있을 수 없다. 또, 빨간 구슬과 파란 구슬의 크기는 한 칸을 모두 차지한다. 기울이는 동작을 그만하는 것은 더 이상 구슬이 움직이지 않을 때 까지이다.
보드의 상태가 주어졌을 때, 최소 몇 번 만에 빨간 구슬을 구멍을 통해 빼낼 수 있는지 구하는 프로그램을 작성하시오.
최단거리를 구하는 데 dfs보다 bfs가 더 효율적이라 bfs로 접근했다. bfs로 …
=> [20250312]/BJ/골드1/13460/김민중

JinHyeok/202503/12 BAJ 나머지합.md
https://www.acmicpc.net/problem/10986
50분
수학문제는 간단하면서 쉽지않은데 계속 해봐야되나 의문
=> [20250312] BAJ / 골드3 / 나머지합 / 양진혁

Ho/202503/13 예쁘게 소용돌이 만들기.md
https://www.acmicpc.net/problem/1022
150분
r1,c1 좌표부터 r2,c2 까지 규칙에 따라서 적혀있는 숫자를 출력한다.
모든 경우를 그려놓고 해당 부분만 잘라서 보여준다.
무지성 메모리 생각안하고 시간만 보고 풀이하면 안된다.
다음엔 수학적으로 풀기
=> [20250313] G3/BAJ/예쁘게 소용돌이 만들기/김득호

kmj-99/202503/13 12100.md
https://www.acmicpc.net/problem/12100
분
문제 링크 참고
최단거리로 최대값을 구해야 하기에 bfs를 이용한다. bfs를 이용해 게임규칙에 맞게 이동을 하고 모든 이동의 경우의 수를 구해서 최대 값을 구한다. n이 20이 최대이기에 전수 조사 가능하다. 
풀지는 못했다. 로직이 꼬인 거 같은데, 한 번 더 고민해 보면 풀릴 거 같다. 내일 풀어봐야지,,
=> [20250313]/BJ/골드1/12100/김민중

Ho/202503/14 내리막길.md
https://www.acmicpc.net/problem/1520
40분
0,0에서 숫자가 작아지는 타일로만 움직여서 N-1,M-1 좌표에 도달하기
DP + DFS
비트마스킹만 제외한 외판원 순회와 비슷한 개념같다.
비트가 빠지니까 생각보다 빨리 풀이해서 좋았음
더 성장하기
=> [20250314] BAJ/G3/내리막길/김득호

kmj-99/202503/14 913700.md
https://www.acmicpc.net/problem/12100
200분
2048 게임 구현
bfs를 사용해서 각 케이스 별로 게임을 수행했다.
로직을 좀 어렵게 생각해서 헤멨다.
=> [20250314]/BJ/골드1/913700/김민중

JinHyeok/202503/14 BAJ 이모티콘.md
https://www.acmicpc.net/problem/14226
50분
주어진 수만큼의 이모티콘을 만들수있는 최소 시간 구하기
BFS
=> [20250314] BAJ / 골드5 / 이모티콘 / 양진혁

JaeIn/202503/17 BAJ 수 이어쓰기.md
https://www.acmicpc.net/problem/1515
50분
남은 수를 이어 붙인 수가 주어질 때, N의 최솟값을 구하는 프로그램
그리디 ?
생각보다 풀이가 짧네.. 이해를 아직 못해서 더 봐야겠슴다..
=> [20250317] BAJ / 실버 3 / 수 이어쓰기 / 이재인

Ho/202503/17 공유기 설치.md
https://www.acmicpc.net/problem/2110
60분
도현이의 집 N개가 수직선 위에 있다. 각각의 집의 좌표는 x1, ..., xN이고, 집 여러개가 같은 좌표를 가지는 일은 없다.
도현이는 언제 어디서나 와이파이를 즐기기 위해서 집에 공유기 C개를 설치하려고 한다. 최대한 많은 곳에서 와이파이를 사용하려고 하기 때문에, 한 집에는 공유기를 하나만 설치할 수 있고, 가장 인접한 두 공유기 사이의 거리를 가능한 크게 하여 설치하려고 한다.
C개의 공유기를 N개의 집에 적당히 설치해서, 가장 인접한 두 공유기 사이의 거리를 최대로 하는 프로그램을 작성하시오.
전형적인 이분탐색
자주 풀어보면서 빨리 풀기
=> [20250317] BAJ/G4/공유기 설치/김득호

JinHyeok/202503/17 BAJ 고층 건물.md
https://www.acmicpc.net/problem/1027
50분
최대한 많이 보이는 건물의 수 구하기
구현
기울기를 통해 구하는 수학문제이다
=> [20250317] BAJ / 골드4 / 고층건물 / 양진혁

ShinHeeEul/202503/18 BAJ G1 Beads.md
https://www.acmicpc.net/problem/11143
60 분
빈 상자들에 구슬을 넣고 관리하는 게임이다.
특정 상자에 구슬을 추가하거나, 연속된 상자들의 구슬 개수를 조회할 수 있다.
이를 효율적으로 처리하는 프로그램을 작성해야 한다.
세그먼트 트리
기본 세그먼트 트리 연습문제이다.
=> [20250318] BAJ / G1 / Beads / 신희을

JaeIn/202503/18 BAJ 문자열 교환.md
https://www.acmicpc.net/problem/1522
45분
연속된 a를 만들기 위해 최소 교환 횟수 구하기
브루트포스
원형 문자열을 만들어서 테스트 하기  위한 방법이 신기했습니다. 쉽지 않네..
=> [20250318] BAJ / 실버 1 / 문자열 교환 / 이재인

JinHyeok/202503/18 BAJ 램프.md
https://www.acmicpc.net/problem/1034
50분
램프가 켜져있는 행의 개수 출력
완탐
=> [20250318] BAJ / 골드4 / 램프 / 양진혁

Ho/202503/18 통나무 옮기기.md
https://www.acmicpc.net/problem/1938
100분
BBB로 표현된 통나무를 2차원 배열내에서 EEE가 표기된 곳으로
옮길 수 있는지 체크한다.
구현, 시뮬레이션 ㄱㄱ
빡구현 문제들을 어떻게 하면 빠르게 디버깅 가능할지 고민해보자
자체 코드로 디버깅 포인트를 만드는 사람도 있는거 같은데 어떻게 하는걸까?
나만의 방식을 생각해보자
=> [20250318] BAJ/G2/통나무 옮기기/김득호

JaeIn/202503/19 BAJ 트리의 부모 찾기.md
https://www.acmicpc.net/problem/11725
40분
트리 부모 찾기
dfs
양방향 탐색 , 단방향 탐색에 대해 조금더 이해하게 되었습니다.
=> [20250319] BAJ / 실버 2 / 트리의 부모 찾기 / 이재인

JinHyeok/202503/19 BAJ 거짓말.md
https://www.acmicpc.net/problem/1043
60분
파티 개수의 최댓값을 구하기
유니온파인드
항상 유니온파인드 문제는 못푸는듯
=> [20250319] BAJ / 골드4 / 거짓말 / 양진혁

Ho/202503/19 친구 네트워크.md
https://www.acmicpc.net/problem/4195
40분
민혁이는 소셜 네트워크 사이트에서 친구를 만드는 것을 좋아하는 친구이다. 우표를 모으는 취미가 있듯이, 민혁이는 소셜 네트워크 사이트에서 친구를 모으는 것이 취미이다.
어떤 사이트의 친구 관계가 생긴 순서대로 주어졌을 때, 두 사람의 친구 네트워크에 몇 명이 있는지 구하는 프로그램을 작성하시오.
친구 네트워크란 친구 관계만으로 이동할 수 있는 사이를 말한다.
HashMap이랑 union-find을 사용하면 야미한데
여기에 친구 관계가 형성될 때 바로 저장하는 추가 배열이 필요함
G2인데 넘 맛있엇다.
=> [20250319] BAJ/G2/친구 네트워크/김득호

kmj-99/202503/19 14500
https://www.acmicpc.net/problem/14500
120분
폴리오미노란 크기가 1×1인 정사각형을 여러 개 이어서 붙인 도형이며, 다음과 같은 조건을 만족해야 한다.
정사각형은 서로 겹치면 안 된다.
도형은 모두 연결되어 있어야 한다.
정사각형의 변끼리 연결되어 있어야 한다. 즉, 꼭짓점과 꼭짓점만 맞닿아 있으면 안 된다.
정사각형 4개를 이어 붙인 폴리오미노는 테트로미노라고 하며, 다음과 같은 5가지가 있다.
아름이는 크기가 N×M인 종이 위에 테트로미노 하나를 놓으려고 한다. 종이는 1×1 크기의 칸으로 나누어져 있으며, 각각의 칸에는 정수가 하나 쓰여 있다.
테트로미노 하나를 적절히 놓아서 테트로미노가 놓인 칸에 쓰여 있는 수들의 합을 최대로 하는 프로그램을 작성하시오.
테트로미노는 반드시 한 정사각형이 정확히 하나의 칸을 포함하도록 놓아야 하며, 회전이나 대칭을 시켜도 된다.
dfs를 적용해서 모든 경우의 수를 구해서 최대값을 갱신시켰다.
soso
=> [20250319]/BJ/골드4/14500/김민중

Ho/202503/21 개미.md
https://www.acmicpc.net/problem/14942
60분
개미굴은 1번 부터 시작하고 각 굴에는 개미들이 있다.
사용가능한 에너지가 있는데 가용 에너지에서 가장 높이 올라갈 수 있는 곳은 어디인가
각각 구해야한다.
희소 배열이라는걸 썻다. 
LCA  문제라고 하는것보다는 희소 배영이라고 말하는게 맞을거 같은데
희소가 뭔지 아직모름 뭔가 뜻이 있겠지
그래도 오랜만에 풀었는데 풀 수 있어서 좋았음
=> [20250321] BAJ/P5/개미/김득호

JaeIn/202503/21 BAJ 로봇 조종하기.md
https://www.acmicpc.net/problem/2169
60+a 분
탐사한 지역들의 가치의 합이 최대가 되도록 하는 프로그램
dp
한 칸씩 내려오면서 각 행마다 좌측 , 우측의 임시 배열을 만들어 do값을 업데이트
방법은 비슷했지만 구현 능력 부족.. 쉽지 않구만
=> [20250321] BAJ / 골드 2 / 로봇 조종하기 / 이재인

JinHyeok/202503/21 BAJ 합.md
https://www.acmicpc.net/problem/1081
60분
합 구하기
구현
구현 쉽지 않네
=> [20250321] BAJ / 골드1 / 합 / 양진혁

JaeIn/202503/21 BAJ 기적의 매매법.md, JaeIn/202503/24 BAJ 배열 돌리기.md, JaeIn/202503/test.py
https://www.acmicpc.net/problem/17276
50분
배열 돌리기
구현
이렇게 배열에 대한 구현 문제에 약하다.. 연습이 많이 필요
규칙들이 있는거같은데 더 해봐야겠다
=> [20250324] BAJ / 실버 1 / 배열 돌리기 / 이재인

Ho/202503/24 2048(eazy).md
https://www.acmicpc.net/problem/12100
70분
2048 게임과 동일하다
처음 주어지는 값을 최대 5번 움직였을 때 
가장 크게 만들 수 있는 숫자는 무엇인가?
백트 + 시뮬레이션
그냥 빡구현
확실히 구현 문제는 문제에서 요구하는 요구사항을 명확하게 정리하고 
설계단계에서 꼼꼼하게 정리하고 시작하는게 가장 빠를거 같다.
같은 값은 또 합쳐지지 않는다는 조건을 읽고 까먹어서 한번에 못풀었다.
만약 실제 시험이었다면 틀렸음.
그리고 이런 문제는 어떻게 디버깅을 잘할 수 있을까?
=> [20250324] BAJ/G1/2048/김득호

kmj-99/202503/24 2240.md
https://www.acmicpc.net/problem/2240
200분
자두는 자두를 좋아한다. 그래서 집에 자두나무를 심어두고, 여기서 열리는 자두를 먹고는 한다. 하지만 자두는 키가 작아서 자두를 따먹지는 못하고, 자두가 떨어질 때까지 기다린 다음에 떨어지는 자두를 받아서 먹고는 한다. 자두를 잡을 때에는 자두가 허공에 있을 때 잡아야 하는데, 이는 자두가 말랑말랑하여 바닥에 떨어지면 못 먹을 정도로 뭉개지기 때문이다.
매 초마다, 두 개의 나무 중 하나의 나무에서 열매가 떨어지게 된다. 만약 열매가 떨어지는 순간, 자두가 그 나무의 아래에 서 있으면 자두는 그 열매를 받아먹을 수 있다. 두 개의 나무는 그다지 멀리 떨어져 있지 않기 때문에, 자두는 하나의 나무 아래에 서 있다가 다른 나무 아래로 빠르게(1초보다 훨씬 짧은 시간에) 움직일 수 있다. 하지만 자두는 체력이 그다지 좋지 못해서 많이 움직일 수는 없다.
자두는 T(1≤T≤1,000)초 동안 떨어지게 된다. 자두는 최대 W(1≤W≤30)번만 움직이고 싶어 한다. 매 초마다 어느 나무에서 자두가 떨어질지에 대한 정보가 주어졌을 때, 자두가 받을 수 있는 자두의 개수를 구해내는 프로그램을 작성하시오. 자두는 1번 자두나무 아래에 위치해 있다고 한다.
완전탐색으로 접근 할 경우 시간초과가 난다. 따라서 dp를 사용하였다. dp[i][j]는 i초에 자두가 떨어지고 j는 현재 위치를 뜻한다. 
1번도 안움직인 경우와 1번 이상 움직인 경우를 나눠서 생각한다. 그리고 1번 이상 움직인 경우에는 자두 위치와 내 위치가 일치한지 아닌지로 또 나눈다. …
=> [20250324]/BJ/골드5/2240/김민중

kmj-99/202503/25 28215.md
https://www.acmicpc.net/problem/28215
100분
KOI 마을의 집들의 위치와 설치할 대피소의 개수가 주어질 때, 대피소를 설치하는 모든 방법 중 가장 가까운 대피소와 집 사이의 거리 중 가장 큰 값이 가장 작을 때의 거리를 구해라.
대피소 개수가 3개가 최대이므로, 1개 2개 3개로 나누어서 for문으로 완탐 돌렸다.
알고리즘은 어렵지 않은데 태스크 통과를 못했다. 다시 한 번 해봐야겠다.
=> [20250325]/BJ/실버4/28215/김민중

JaeIn/202503/26 PGM 비밀 코드 해독.md
https://school.programmers.co.kr/learn/courses/30/lessons/388352
45분
비밀 코드로 가능한 정수 조합 개수를 return
구현
정답을 체크하는 조건으로 set을 사용해서 푸는 것이 신기했다. 이렇게도 생각할 수 있구나..
=> [20250326] PGM / lv2 / 비밀 코드 해독 / 이재인

Ho/202503/26 MMST.md
https://www.acmicpc.net/problem/25545
150분
최소, 최대 스패닝트리가 아닌
스패닝트리를 만들 수 있는 간선이 존재하는지 판단하고
해당 간선을 출력하기
풀이 실패.. 
푸는중
일단 최소, 최대 스패닝 간선을 찾고
여기에 포함되는 간선을 하나 제외하고
그 간선을 제외하면서 혼자 남은 정점을 
다른 정점과 연결해서 최소, 최대가 아닌지 판단하기
최소 스패닝 트리 알고리즘 공부해야겠음
=> [20250326] BAJ/G2/MMST/김득호

kmj-99/202503/27 28125.md
https://www.acmicpc.net/problem/28215
200분
KOI 마을의 집들의 위치와 설치할 대피소의 개수가 주어질 때, 대피소를 설치하는 모든 방법 중 가장 가까운 대피소와 집 사이의 거리 중 가장 큰 값이 가장 작을 때의 거리를 구해라.
N<=50이라 완탐으로 해도 시간복잡도가 50^4가 나와서 가능하다. K 별로 나누고 대피소를 지정해서 모든 집들을 돌면서 대피소와 가장 가까운 경우를 구하고, 모든 점들중 가장 긴 경우를 구해서, 최종적으로 가장 짧은 경우를 구한다.
어렵지는 않았는데, K를 구분하고 로직을 수행할 때 접근을 잘못한 거 같다.
=> [20250327]/BJ/실버4/28125/김민중

Ho/202503/28 마법사 상어와 파이어스톰.md
https://www.acmicpc.net/problem/20058
80분
2^k 만큼 주어지는 쿼리에 따라 90도 돌리고
각 칸에서 상하좌우로 3곳미만으로 인접하면 얼음 -1
그냥 구현
문제를 좀 잘 설명할 필요가 있다...
한국말인가 싶었다.
=> [20250328] BAJ/G3/마법사 상어와 파이어스톰/김득호

JinHyeok/202503/28 BAJ 문자열 폭발.md
https://www.acmicpc.net/problem/9935
40분
폭발이 끝난 후 남은 문자열을 출력한다.
스택이용해서 문자열 처리
=> [20250328] BAJ / 골드4 / 문자열 폭발 / 양진혁

Ho/202504/1 스도쿠.md
https://www.acmicpc.net/problem/2580
50분
스도쿠를 완성하는 코드를 작성해라
백트래킹 + 최적화
프루닝을 적당히 하면될 것 같았는데 생각보다 빡세게해야한다...
시험장에서 다 적용해서 처음부터 구현할 수 있을까?
=> [20250401] BAJ/G4/스도쿠/김득호

kmj-99/202404/1 9935.md
https://www.acmicpc.net/status?user_id=nex1223&problem_id=9935&from_mine=1
60분
상근이는 문자열에 폭발 문자열을 심어 놓았다. 폭발 문자열이 폭발하면 그 문자는 문자열에서 사라지며, 남은 문자열은 합쳐지게 된다.
폭발은 다음과 같은 과정으로 진행된다.
문자열이 폭발 문자열을 포함하고 있는 경우에, 모든 폭발 문자열이 폭발하게 된다. 남은 문자열을 순서대로 이어 붙여 새로운 문자열을 만든다.
새로 생긴 문자열에 폭발 문자열이 포함되어 있을 수도 있다.
폭발은 폭발 문자열이 문자열에 없을 때까지 계속된다.
상근이는 모든 폭발이 끝난 후에 어떤 문자열이 남는지 구해보려고 한다. 남아있는 문자가 없는 경우가 있다. 이때는 "FRULA"를 출력한다.
폭발 문자열은 같은 문자를 두 개 이상 포함하지 않는다.
문자열 replace 쓰면서 같은 문자를 삭제하고, 삭제한 지점부터 다시 탐색할 수 있도록 했다. 
출력초과가 뜨는데 아직 원인 파악 못함
=> [20250401]/BJ/골드4/9935/김민중

JinHyeok/202504/02 BAJ 1, 2, 3 더하기 4.md
https://www.acmicpc.net/problem/15989
40분
n을 1, 2, 3의 합으로 나타내는 방법의 수를 출력
DP
DP 기본문제
=> [20250402] BAJ / 골드5 / 1, 2, 3 더하기 4 / 양진혁

Ho/202504/2 마법사 상어와 블리자드.md
https://www.acmicpc.net/problem/21611
120분
달팽이 모양으로 주어진 길에 제공되는 
각 구슬을 규칙에 맞춰 제거하기
달팽이 모양 이동경로를 저장하고 
일차원 배열로 만들어서 최대한 실수 없이
구현할 수 있도록 함
구현 문제를 잘 설계하고 빠르게 풀 수 있도록하기..
=> [20250402] BAJ/G1/마법사 상어와 블리자드/김득호

Ho/202504/4 마법사 상어와 복제
https://www.acmicpc.net/problem/23290
300분
문제에서 제시한 순서대로 그냥 구현하면 되는 문제
요구사항은 최대한 잘게 쪼개서 의존성을 낮춘다.
그래야 문제 발생했을 때 수정하기 쉬움
막 가지치기하려고 하지말고 
조금 느리더라도 안전하고 완벽하게 구현하자
=> [20250404] BAJ/G1/마법사 상어와 복제/김득호

JinHyeok/202504/04 BAJ 센서.md
https://www.acmicpc.net/problem/2212
40분
수신 가능 영역의 길이의 합의 최솟값을 출력
그리디
기초문제
=> [20250404] BAJ / 골드5 / 센서 / 양진혁

kmj-99/202504/4 6998.md
https://www.acmicpc.net/problem/6998
200분
Bilbo meets the love of his life, Oblib, but she seems eerily familiar and he worries that they are related. They both know their ancestry, but can’t just compare their ancestry trees because Bilbo knows his ancestor names in the male form, and Oblib knows hers in the female form, and the two forms are not related. Even if they were brother and sister, the names they know their ancestors by would all be different!
Bilbo and Oblib have written out their family trees. Your task is to determine if the two trees are isomorphic, i.e., if there is a one-to-one mapping between the two, ignoring the names. Assume that the trees are rooted, i.e., their roots are fixed. As an example, the two trees on the left below are not isomorphic to each other – there …
=> [20250404]/BJ/골드3/6998/김민중

ShinHeeEul/202504/04 BAJ G4 파이프 옮기기2.md
https://www.acmicpc.net/problem/17069
30 분
- 크기 N×N의 격자판이 주어지고, 이곳에 벽이 있을 수 있다.
- 파이프는 항상 가로, 세로, 대각선의 세 가지 형태로 놓일 수 있다.
- 처음엔 (1,1)-(1,2) 위치에 가로 파이프가 놓여 있다.
- 파이프를 **(N, N)**으로 옮기는 경우의 수를 구하자.
3차원 DP를 두자. `dp[i][j][k]`에서 i와 j는 현재 위치를 뜻하고, k는 현재 방향을 뜻한다. 
현재 상태까지의 경우의 수를 다음 상태에 더해준다. 
dp[n][m]의 모든 값을 더하면 정답이다.
요즘 알태기 왔다. 왤케 문제 풀기가 싫지
=> [20250404] BAJ / G4 / 파이프 옮기기2 / 신희을

ShinHeeEul/202504/07 BAJ P3 수열과 쿼리1.md
https://www.acmicpc.net/problem/13537
100 분
길이가 N인 수열 A1, A2, ..., AN이 주어진다. 이때, 다음 쿼리를 수행하는 프로그램을 작성하시오.
i j k: Ai, Ai+1, ..., Aj로 이루어진 부분 수열 중에서 k보다 큰 원소의 개수를 출력한다.
다음과 같이 머지 소트 트리를 구성하고, 탐색 쿼리에서 이분 탐색을 하여, k보다 큰 수의 갯수를 반환한다.
머지 소트 트리 연습 문제. 벼르고 벼르다 드디어 풀었다.
=> [20250407] BAJ / P3 / 수열과 쿼리 1 / 신희을

Ho/202504/5 미지의 공간탈출.md
https://www.codetree.ai/ko/frequent-problems/problems/escape-unknown-space/description
216분
3차원 공간을 겉면을 이동하면서 탈출하고 2차원 평면에 있는 도착지점까지
최단거리로 도달해라 이때 최단거리는 얼마나 되는가
/*
* 0 : 도로
* 1 : 장애물
* 2 : 시작 위치
* 3 : 공간 표시
* 4 : 도착지 
* 
* 동, 서 , 남 , 북, 윗면으로 단면도가 주어진다.
* 
* 풀이방법
* 1. 시작 위치, 탈출 위치 찾기
* 1-1. 3차원에서 2차원으로 나갈 때 규칙 찾아 구현하기
* 2. 3차원 공간 이동 구현하기
* 3. 2차원 평면  시간 이상 현상 고려한 평면 구하기
*/
여러가지를 고려해서 구현하는데 왜 자꾸 실수가 발생할까?
시간이 오래걸리니까 최대한 실수 없이 한번에 구현하도록 하자
=> [20250407] CDT/기출/미지의 공간 탈출/김득호

JinHyeok/202504/07 PC방 요금.md
https://www.acmicpc.net/problem/9080
60분
PC방 요금 출력
구현
크아아아아악 쉽지않네
=> [20250407] BAJ / 골드4 / PC방 요금 / 양진혁

JaeIn/202504/PGM 주차요금계산.md
https://school.programmers.co.kr/learn/courses/30/lessons/92341
50분
차량 번호가 작은 자동차부터 청구할 주차 요금을 차례대로 정수 배열에 담아서 return
구현
전에 풀었던거지만 생각하는데 오래걸림..
=> [20250407] PGM / lv2 / 주차요금 계산 / 이재인

kmj-99/202504/7 베스트앨범.md
https://school.programmers.co.kr/learn/courses/30/lessons/42579
200분
스트리밍 사이트에서 장르 별로 가장 많이 재생된 노래를 두 개씩 모아 베스트 앨범을 출시하려 합니다. 노래는 고유 번호로 구분하며, 노래를 수록하는 기준은 다음과 같습니다.
속한 노래가 많이 재생된 장르를 먼저 수록합니다.
장르 내에서 많이 재생된 노래를 먼저 수록합니다.
장르 내에서 재생 횟수가 같은 노래 중에서는 고유 번호가 낮은 노래를 먼저 수록합니다.
노래의 장르를 나타내는 문자열 배열 genres와 노래별 재생 횟수를 나타내는 정수 배열 plays가 주어질 때, 베스트 앨범에 들어갈 노래의 고유 번호를 순서대로 return 하도록 solution 함수를 완성하세요.
해시를 사용하여 풀이
해시를 이용해서 sort를 하는 게 좀 까다롭다.
=> [20250407]/PGM/LV3/베스트앨범/김민중

ShinHeeEul/202504/08 BAJ G1 달이 차오른다, 가자.md
https://www.acmicpc.net/problem/1194
100 분
민식이는 지금 미로 속에 있다. 미로는 직사각형 모양이고, 여행길을 떠나기 위해 미로를 탈출하려고 한다. 미로는 다음과 같이 구성되어져있다.
- 빈 칸: 언제나 이동할 수 있다. ('.')
- 벽: 절대 이동할 수 없다. ('#')
- 열쇠: 언제나 이동할 수 있다. 이 곳에 처음 들어가면 열쇠를 집는다. ('a', 'b', 'c', 'd', 'e', 'f')
- 문: 대응하는 열쇠가 있을 때만 이동할 수 있다. ('A', 'B', 'C', 'D', 'E', 'F')
- 민식이의 현재 위치: 빈 곳이고, 민식이가 현재 서 있는 곳이다. ('0')
- 출구: 달이 차오르기 때문에, 민식이가 가야하는 곳이다. 이 곳에 오면 미로를 탈출한다. ('1')
민식이가 미로를 탈출하는데 걸리는 이동 횟수의 최솟값을 구하는 프로그램을 작성하시오.
BFS + 비트마스킹으로 방문 배열을 [i][j][가지고 있는 열쇠 비트]로 두어 방문 처리를 한다.
비트마스킹 익히기 좋은 문제
=> [20250408] BAJ / G1 / 달이 차오른다, 가자 / 신희을

JinHyeok/202504/08 BAJ 회문.md
https://www.acmicpc.net/problem/17609
50분
팰린드롬 문제임
문자열
오랜만에 해서 아리까리했음
=> [20250408] BAJ / 골드5 / 회문 / 양진혁

ShinHeeEul/202504/09 BAJ G3 개미굴.md
https://www.acmicpc.net/problem/14725
40 분
개미굴(트리 구조) 안에 있는 먹이 정보들을 로봇 개미가 탐색하여 층별로 보내줍니다.
각 줄은 로봇 개미가 지나간 먹이의 경로를 의미합니다.
우리는 이 정보를 가지고 개미굴의 트리 구조를 시각화해야 합니다.
첫 줄: N (로봇 개미가 보낸 먹이 정보의 개수)
다음 N줄:
각 줄의 첫 번째 숫자 K: 경로 길이
다음 K개 문자열: 로봇 개미가 지나온 방(먹이)들
예:
```
4  
2 KIWI BANANA  
2 KIWI APPLE  
2 APPLE APPLE  
3 APPLE BANANA KIWI
```
###📤 출력
각 층마다 --를 붙여서 깊이를 표현
같은 층에 여러 방이 있으면 사전 순서로 출력
같은 방 이름이 반복되어도 중복 없이 하나만 출력
출력 예:
```
APPLE  
--APPLE  
--BANANA  
----KIWI  
KIWI  
--APPLE  
--BANANA
```
Trie로 트리화 시킨다.
트리이 연습문제
=> [20250409] BAJ / G3 / 개미굴 / 신희을

Ho/202504/9 포탑 부수기.md
https://www.codetree.ai/ko/frequent-problems/problems/destroy-the-turret/submissions?page=1&page_size=20
120분
가장 약한 포탑이 가장 강한 포탑을 공격하는 게임
결국 최후의 승자 또는 K초후 가장 강한 포탑을 찾으시오
/*
* 경로 이동 구현하기
* 격자 밖을 나갔을 때 스무스하게 하는거
*/
/*
* [3] 공격
* 레이저 공격 시도하고 불가능하면 포탄 공격
* (레이저 공격) 공격력 만큼 피해를 준다.
* 1. 상하좌우 4개 방향 
* 2. 부서진 포탑이 있는 위치는 지날 수 없다.
* 3. 가장자리에서 막힌 방향으로 진행한 경우
* 	    반대편으로 나오게된다.
* 
* 공격 대상 포탑까지의 최단 경로로 공격한다.
* (해당 경로가 존재하지 않는 경우!)
* 최단 경로가 여러개인 경우 우/하/좌/상 순서로 한다.
* 
* (포탄 공격)
* 공격력 만큼 피해를 준다.
* 1. 공격 대상에 포탄을 던진다.
* 2. 추가적으로 8개의 방향에 있는 포탑도 피해를 입는다.
*	-> 이 경우는 절반 피해, 공격자는 피해를 받지 않는다.
*  -> 가장자리로 떨어지는 경우 M -> 0 으로 이동해서 공격
* 
* [4] 포탑 정비
* 공격이 끝났으면, 부서지지 않은 포탑 중 공격과 무관한 포탑은
* 공격력이 1씩 올라간다.
* 공격자도, 피해자도 아닌 포탑
* 
* 
*/
순서에 맞게 빡구현
문제를 정확하게 이해하고 
특이 케이스가 발생할 수 있는지? 
이런걸 고려해야할 것 같다.
일단 조금 시간 단축한다고 최적화하다가 …
=> [20250409] CDT/기출/포탑 부수기/김득호

kmj-99/202504/10가장먼노드.md
https://school.programmers.co.kr/learn/courses/30/lessons/49189
100분
n개의 노드가 있는 그래프가 있습니다. 각 노드는 1부터 n까지 번호가 적혀있습니다. 1번 노드에서 가장 멀리 떨어진 노드의 갯수를 구하려고 합니다. 가장 멀리 떨어진 노드란 최단경로로 이동했을 때 간선의 개수가 가장 많은 노드들을 의미합니다.
노드의 개수 n, 간선에 대한 정보가 담긴 2차원 배열 vertex가 매개변수로 주어질 때, 1번 노드로부터 가장 멀리 떨어진 노드가 몇 개인지를 return 하도록 solution 함수를 작성해주세요.
최단거리를 구하면 되므로 bfs로 노드를 돌면서 최단거리를 구하는 식으로 접근, 이때 visited 꼭 해줘야함
SOSO
=> [20250410]/PGM/LV3/가장먼노드/김민중

ShinHeeEul/202504/11 BAJ P2 하늘에서 떨어지는 1, 2, ..., R-L+1개의 별.md
https://www.acmicpc.net/problem/17353
100 분
욱제의 은밀한 취미 중 하나는 매일 밤하늘을 감상하는 것이다. 😓 욱제는 하늘의 별들이 다음과 같은 규칙들을 따르며 떨어지는 걸 관찰했다.
별이 떨어지는 위치는 N개의 점이다. 점은 순서대로 1, 2, ..., N의 번호를 갖는다.
매일 밤 별들은 1, 2, ..., N의 연속한 부분 구간 [L, R]에 떨어진다.
[L, R]에 별이 떨어지면, 각 점에는 순서대로 1, 2, ..., R-L+1개의 별이 떨어진다. 다시 말해, L에는 1개, L+1에는 2개, ..., R에는 R-L+1개의 별이 떨어진다.
욱제는 하늘에서 떨어지는 별들을 기록하다가 잠이 들어버렸다!! 혹시나 했지만 역시나, 여러분은 욱제를 대신해 아래의 쿼리를 수행해야 한다. (ㅎㅎ;; ㅈㅅ.. ㅋㅋ!!)
1 L R: [L, R]에 별이 떨어진다. (1 ≤ L ≤ R ≤ N)
2 X: 점 X에 떨어진 별의 개수의 합을 출력한다. (1 ≤ X ≤ N)
느리게 갱신 되는 세그먼트 트리 + 등차 수열 업데이트, 여러번 겹쳐진 경우에서 propagation하기 위해 몇번 겹처되었는지를 표현하는 repl 트리를 하나 더 두었다.
느리게 갱신 되는 세그먼트 트리만 알면 풀 수 있는 문제
=> [20250411] BAJ / P2 / 하늘에서 떨어지는 1, 2, ..., R-L+1개의 별  / 신희을

JinHyeok/202504/11 BAJ 행복유치원.md
https://www.acmicpc.net/problem/13164
40분
그리디
=> [20250411] BAJ / 골드5 / 행복유치원 / 양진혁

Ho/202504/11 최솟값.md
https://www.acmicpc.net/problem/10868
30분
특정 구간에서 가장 작은 값을 찾는 문제
세그먼트 트리
오랜만에 하니까 버벅이면서 구현했다.
그래도 예전보다는 빠른건 맞지만 오랜만에 하면 헷갈린다.
=> [20250411] BAJ/G1/최솟값/김득호

JaeIn/202504/PGM 프렌즈4블록.md
https://school.programmers.co.kr/learn/courses/30/lessons/17679
60분
아직 배열에 대한 문제에 너무 약하다.. 연습 필요..
=> [20250411] PGM / lv2 / 프렌즈4블록 / 이재인

JinHyeok/202504/14 BAJ 배.md
https://www.acmicpc.net/problem/1092
50분
모든 박스를 배로 옮기는데 드는 시간의 최솟값 구하기
그리디
=> [20250414] BAJ / 골드5 / 배 / 양진혁

ShinHeeEul/202504/15 BAJ P5 개미.md
https://www.acmicpc.net/problem/14942
60 분
개미집은 n개의 방으로 구성되어 있으며 n개의 방은 1번부터 n번 까지 번호가 부여되어 있다. 그 중에서 1번 방은 지면에 바로 연결되어 있는 방이다. 각 방들은 서로 굴을 통해 연결되어 있다. 각 굴을 이동하기 위해서는 굴의 길이만큼 에너지가 소모된다.
개미는 집짓기의 달인이기 때문에 불필요한 굴은 짓지 않는다. 그래서 굴을 타고 한 방에서 다른 방으로 갈 수 있는 경로는 항상 존재하며 유일하다. 임의의 두 방 사이의 거리는 두 개의 방을 연결하는 경로를 구성하는 굴의 길이의 합이다.
겨울잠을 자던 개미들은 겨울잠에서 깨어나 지면으로 올라가 햇살을 보고 싶어한다. 그렇기 때문에 지면과 연결된 1번 방으로 이동을 하려고 한다. 하지만 불행하게도 개미는 긴 겨울잠을 자느라 축적해 놓은 에너지가 적다. 그래서 개미는 에너지를 1번 방에 도달하기 전에 모두 소모 할 수도 있다. 이렇게 에너지가 0이 된 개미는 더 이상 움직일 수 없다. 또한 1번 방에 도착한 개미는 더 이상 움직이지 않는다.
현재 모든 방에는 개미가 한 마리씩 있고 각각의 개미는 각자 축적된 에너지를 가지고 있다. 잠에서 깨어난 모든 개미는 1번 방을 향해서 이동한다. 이때 각각의 개미에 대해 도달할 수 있는 방 중에서 가장 1번 방에 가까운 방의 번호를 출력하시오.
도로 네트워크처럼 희소 배열을 값을 저장하는 형식으로 구성하고, 각 개미들 마다 최대 얼마나 갈 수 있는지 logN씩 올라가보면서 구한다.
문제 자체를 읽었을 때 굴이 트리임을 파악하기도 어려웠고, 희소 …
=> [20250415] BAJ / P5 / 개미  / 신희을

JinHyeok/202504/15 BAJ 전구 상태 바꾸기.md
https://www.acmicpc.net/problem/30023
60분
세 전구의 상태를 바꾸는 과정을 최소 몇 번 수행
구현
=> [20250415] BAJ / 골드5 / 전구 상태 바꾸기 / 양진혁

JaeIn/202504/15 PGM 거리두기 확인하기.md
https://school.programmers.co.kr/learn/courses/30/lessons/81302
60분
각 대기실별로 거리두기를 지키고 있으면 1을, 한 명이라도 지키지 않고 있으면 0을 배열에 담아 return
구현
코드를 다시 보고 이해를 해야겠다.. 구현 어렵..
=> [20250416] PGM / lv2 / 거리두기 확인하기 / 이재인

ShinHeeEul/202504/17 BAJ G2 너 봄에는 캡사이신이 맛있단다.md
https://www.acmicpc.net/problem/15824
120 분
주헌이는 매운맛을 좋아한다. 정확히는, 매운맛을 먹음으로써 느낄 수 있는 고통에서 희열을 느끼는 진정한 '즐기는 자'다.
'스코빌 지수'란 고추류가 가진 매운맛의 원인인 캡사이신의 농도를 수치화 한 단위이다. 주헌이가 느끼는 매운 정도는 굉장히 독특한데, 먹고 있는 메뉴의 절대 수치가 아닌 음식과의 상대수치에 기반한다. 예를 들어 [5, 2, 8]의 스코빌 지수를 가진 음식을 먹을 때 주헌이가 느끼는 매운 정도는 가장 높은 수치인 8과 가장 낮은 수치인 2의 차이인 6만큼의 매운맛을 느낀다. 이처럼 메뉴들의 스코빌 지수가 있을 때 그 최댓값과 최솟값의 차이를 "주헌고통지수"라고 정의한다.
최근 주헌이에게 좋아하는 매운맛 전문점이 생겼다. 메뉴가 아주 다양한 이 음식점은 모든 메뉴의 스코빌 지수를 명시한 메뉴판을 제공한다. 주헌이의 목표는 이 음식점의 모든 음식 조합을 먹어보는 것이다. 하지만 주헌이는 까다로워서 한 번 먹어본 조합은 다시 먹지 않는다.
이 음식점의 모든 조합을 먹어 볼 때 주헌이가 즐길 수 있는 주헌고통지수의 합을 구해보자.
정렬 후, 해당 값이 최소로 사용되는 횟수는 $2 ^ i$이며 최대로 사용되는 횟수는 $2 ^ {N - i - 1}$이다.
$(최대 - 최소) * 현재값  % MOD$를 전부 더한 값이 정답
개 어렵다 진짜. 분할 정복 거듭 제곱 구할 때 전부 long으로 하자.
=> [20250417] BAJ / G2 / 너 봄에는 캡사이신이 맛있단다  / 신희을

ShinHeeEul/202504/18 BAJ P4 가장 높고 넓은 성.md
https://www.acmicpc.net/problem/17403
70 분
당신은 어마어마한 크기의 토지를 소유한 부자다. 평지에는 n개의 표지판이 있다. 당신은 지금부터 이 곳에 민성이를 위한 성을 지을 것이다. 성은 여러 개의 층으로 구성된 구조물이다.
1층은 평지 위에 지어지고, 2층은 1층 위에, 3층은 2층 위에, ..., n층은 n-1층 위에 지어진다.
각 층의 경계는 다각형이며, 각 층의 경계의 꼭짓점에는 표지판이 위치하여야 한다. 다시 말하면, 표지판 위에만 각 층의 경계의 꼭짓점을 세울 수 있다.
한 표지판은 여러 층의 경계의 꼭짓점에 동시에 사용될 수 없다. 그러나 한 표지판이 다른 층의 꼭짓점이 아닌 경계에 위치할 수는 있다.
넓이가 0인 층은 허용되지 않는다.
쓸모가 없는 표지판들은 버려도 된다.
민성이는 숙소를 고를 때 전망을 최우선으로 고려하므로, 당신이 성을 지을 때 고려해야 할 우선순위는 다음과 같다.
성의 높이를 가능한 한 제일 높게 지어야 한다.
성의 모든 층의 넓이의 합이 가능한 한 제일 크게 지어야 한다.
가능한 적은 수의 표지판을 사용하여야 한다.
당신은 성을 몇 층까지 지을 수 있으며, 그 때 각 층에 사용될 표지판들이 무슨 표지판인지 알아내야 한다.
볼록 껍질로 바깥 껍질 찾은 뒤, 해당 점들 제외하고 다시 찾음.
볼록 껍질 연습중..
=> [20250418] BAJ / P4 / 가장 높고 넓은 성  / 신희을

Ho/202504/18 수열의 합.md
https://www.acmicpc.net/problem/1024
60분
L개 이상의 연속된 수로 N을 만족하는 수열 찾기 
공차가 1인 등차 수열 공식을 이용
수학문제는 .. 진짜 ... 하
=> [20250418] S2/BAJ/수열의 합/김득호

JinHyeok/202504/18 BAJ 동전.md
https://www.acmicpc.net/problem/9084
40분
N가지 동전으로 금액 M을 만드는 모든 방법의 수
DP
=> [20250418] BAJ / 골드5 / 동전 / 양진혁

JaeIn/202504/18 PGM 입국심사.md
https://school.programmers.co.kr/learn/courses/30/lessons/43238
50분
이분탐색
이분탐색인지 파악을 못했음..
=> [20250418] PGM / lv3 / 입국심사 / 이재인

Ho/202504/21 달이 차오른다, 가자.md
https://www.acmicpc.net/problem/1194
50분
문제에서 주어지는 출발지점에서 
목적지까지 도달하는 문제
중간에 문이 존재하는데 상하좌우로 이동하면서 
열쇠를 획득하면 이동가능
BFS  + 비트마스킹
비트마스킹 문제인걸 알고 접근했지만
오랜만에 비트마스킹을 사용하려고해서 
어떻게 적용해야할지 고민했다.
다시 꾸준히 풀어보자
=> [20250421] BAJ/G1/달이 차오른다, 가자/김득호

kmj-99/202504/21 봉인된주문.md
https://school.programmers.co.kr/learn/courses/30/lessons/389481
200분
어느 날, 전설 속에 전해 내려오는 비밀 주문서가 세상에 다시 모습을 드러냈습니다. 이 주문서에는 마법 세계에서 사용되는 모든 주문이 적혀 있는데, 각 주문은 알파벳 소문자 11글자 이하로 구성되어 있습니다. 주문서에는 실제로 마법적 효과를 지니지 않는 의미 없는 주문들 즉, 알파벳 소문자 11글자 이하로 쓸 수 있는 모든 문자열이 고대의 규칙에 따라 아래와 같이 정렬되어 있습니다.
글자 수가 적은 주문부터 먼저 기록된다.
글자 수가 같다면, 사전 순서대로 기록된다.
예를 들어, 주문서의 시작 부분은 다음과 같이 구성됩니다.
"a"→"b"→"c"→"d"→"e"→"f"→...→"z"
→"aa"→"ab"→...→"az"→"ba"→...→"by"→"bz"→"ca"→...→"zz"
→"aaa"→"aab"→...→"aaz"→"aba"→...→"azz"→"baa"→...→"zzz"
→"aaaa"→...→"aazz"→"abaa"→...→"czzz"→"daaa"→...→"zzzz"
→"aaaaa"→...
하지만 이 주문서에는 오래전 봉인된 저주받은 주문들이 숨겨져 있었고, 이를 악용하려는 자들을 막기 위해 마법사들이 몇몇 주문을 주문서에서 삭제했습니다. 당신은 삭제가 완료된 주문서에서 n번째 주문을 찾아내야 합니다.
예를 들어, 주문서에서 "d", "e", "bb", "aa", "ae" 5개의 주문을 지웠을 때, 주문서에서 30번째 주문을 찾으려고 합니다.
1~3번째 주문은 "a", "b", "c" …
=> [20250421]/PGM/LV3/봉인된주문/김민중

JinHyeok/202504/21 BAJ ⚾.md
https://www.acmicpc.net/problem/17281
60분
아인타팀이 얻을 수 있는 최대 점수를 출력
구현
next_permutation 아직 쓰기 어렵네 ;
=> [20250421] BAJ / 골드4 / ⚾ / 양진혁

ShinHeeEul/202504/22 BAJ G5 물통.md
https://www.acmicpc.net/problem/1052
30 분
지민이는 N개의 물병을 가지고 있다. 각 물병에는 물을 무한대로 부을 수 있다. 처음에 모든 물병에는 물이 1리터씩 들어있다. 지민이는 이 물병을 또 다른 장소로 옮기려고 한다. 지민이는 한 번에 K개의 물병을 옮길 수 있다. 하지만, 지민이는 물을 낭비하기는 싫고, 이동을 한 번보다 많이 하기는 싫다. 따라서, 지민이는 물병의 물을 적절히 재분배해서, K개를 넘지 않는 비어있지 않은 물병을 만들려고 한다.
물은 다음과 같이 재분배 한다.
먼저 같은 양의 물이 들어있는 물병 두 개를 고른다. 그 다음에 한 개의 물병에 다른 한 쪽에 있는 물을 모두 붓는다. 이 방법을 필요한 만큼 계속 한다.
이런 제약 때문에, N개로 K개를 넘지않는 비어있지 않은 물병을 만드는 것이 불가능할 수도 있다. 다행히도, 새로운 물병을 살 수 있다. 상점에서 사는 물병은 물이 1리터 들어있다.
예를 들어, N=3이고, K=1일 때를 보면, 물병 3개로 1개를 만드는 것이 불가능하다. 한 병을 또다른 병에 부으면, 2리터가 들어있는 물병 하나와, 1리터가 들어있는 물병 하나가 남는다. 만약 상점에서 한 개의 물병을 산다면, 2리터가 들어있는 물병 두 개를 만들 수 있고, 마지막으로 4리터가 들어있는 물병 한 개를 만들 수 있다.
세그 트리 쿼리 테크닉을 이용해서 억지로 풀었다.. N부터 MAX까지의 구간 합을 구할 때 몇 개의 노드를 거쳐야 되는지를 계산해서 반환했다. 정해는 그리디더라..
머리가 돌아가지 않는다..
=> [20250422] BAJ / G5 / 물통  / 신희을

JaeIn/202504/22 나 잡아봐라.md
60분
연인 코니와 브라운은 광활한 들판에서 ‘나 잡아 봐라’ 게임을 한다. 
이 게임은 브라운이 코니를 잡거나, 코니가 너무 멀리 달아나면 끝난다. 
게임이 끝나는데 걸리는 최소 시간을 구하시오.
bfs
그리디라고 생각했는데, bfs로 풀 수 있었다.
이렇게 모든 경우의 탐색하고 비교해야할 경우 -> bfs 떠올리기
각 키 값에 여러값이 들어갈 경우 -> dict  떠올리기
=> [20250422] / 나 잡아봐라 / 이재인

JinHyeok/202504/22 BAJ 되돌리기.md
https://www.acmicpc.net/problem/1360
60분
모든 명령을 수행한 후에 남아있는 텍스트를 출력
구현
=> [20250422] BAJ / 골드5 / 되돌리기 / 양진혁

ShinHeeEul/202504/23 BAJ P1 연속합과 쿼리.md
https://www.acmicpc.net/problem/16993
120+ 분
길이가 N인 수열 A1, A2, ..., AN이 주어진다. 이때, 다음 쿼리를 수행하는 프로그램을 작성하시오.
i j : Ai, Ai+1, ..., Aj에서 가장 큰 연속합을 출력한다. (1 ≤ i ≤ j ≤ N)
수열의 인덱스는 1부터 시작한다.
연속합은 연속된 몇 개의 수를 선택해서 구할 수 있는 합 중 가장 큰 합이며, 수는 한 개 이상 선택해야 한다.
금광 세그 테크닉을 이용한 세그먼트 트리
인생 첫 P1!
=> [20250423] BAJ / P1 / 연속합과 쿼리 / 신희을

JaeIn/202504/23 PGM 문자열 압축.md
https://school.programmers.co.kr/learn/courses/30/lessons/60057
50분
구현
문자열에 대한 문제가 아직 어렵다.. ㅜ
=> [20250423] PGM / lv2 / 문자열 압축 / 이재인

Ho/202504/23 같이 눈사람 만들래?.md
https://www.acmicpc.net/submit/20366/93494034
60분
두사람이 각자 만드는 눈사람의 키 차이가
최소가 되도록 눈덩이를 선택하기
고정 포인터와 투 포인터를 적절히 사용한다.
문제에서 주어지는 크기를 보고 투포인터를 생각하는게
쉽지 않다..
=> [20250423] BAJ/G3/같이 눈사람 만들래?/김득호

JinHyeok/202504/23 BAJ 카드섞기.md
https://www.acmicpc.net/problem/1091
60분
첫째 줄에 몇 번 섞어야 하는지 출력한다
구현
ㅅㅂ
=> [20250423] BAJ / 골드4 / 카드섞기 / 양진혁

Ho/202504/28 계보 복원가 호석.md
https://www.acmicpc.net/problem/21276
70분
호석이 마을 족보를 복원해보도록하자
위상정렬을 꺼꾸로한다.
문제를 잘 읽고 해결하자!
=> [20250428] BAJ/G2/계보 복원가 호석/김득호

JaeIn/202504/28 나 잡아봐라.md
45분
연인 코니와 브라운은 광활한 들판에서 ‘나 잡아 봐라’ 게임을 한다. 
이 게임은 브라운이 코니를 잡거나, 코니가 너무 멀리 달아나면 끝난다. 
게임이 끝나는데 걸리는 최소 시간을 구하시오.
bfs
다시 한 번 풀어보니 전보다는 그래도 시간이 빨라진것 같다.
=> [20250428] / 나 잡아봐라 / 이재인

JaeIn/202504/29 PGM 괄호 변환.md
https://school.programmers.co.kr/learn/courses/30/lessons/60058
50분
구현
되게 막막하게 느껴져서 풀지 못했지만
하나씩 봐보니 생각보다는 쉬운 문제였네요..  요구사항을 정확히 이해하고 푸는 연습 필요
=> [20250429] PGM / lv2 / 괄호 변환 / 이재인

JaeIn/202504/30 PGM 문자열 압축.md
https://school.programmers.co.kr/learn/courses/30/lessons/60057
50분
쪼갠 문자열을 어떻게 현재 , 다음과 비교하면서 할지 몰라서 구현을 못했다..
쪼갠 문자열을 배열을 통해 전체 저장하고 한번에 압축시키면 쉽게 가능했다
=> [20250430] PGM / lv2 / 문자열 압축 / 이재인

JaeIn/202505/02 BAJ 숫자 야구.md
https://www.acmicpc.net/problem/2503
40분
완전탐색
풀었던건데 구현이 느리고 잘 안된다..
=> [20250502] BAG / 실버2 / 숫자 야구 / 이재인

JaeIn/202505/07 BAJ 도영이가 만든 맛있는 음식.md
https://www.acmicpc.net/problem/2961
40분
완탐 , dfs
모든 경우를 보기 위해서 dfs를 이용했습니다
=> [20250507] BAJ / 실버2 / 도영이가 만든 음식 / 이재인

JinHyeok/202505/07 BAJ 로마 숫자.md
https://www.acmicpc.net/problem/2608
60분
- [X ] 중
=> [20250507] BAJ / 골드5 / 로마 숫자 / 양진혁

JaeIn/202505/12 BAJ 기적의 매매법.md
https://www.acmicpc.net/problem/20546
40분
구현
문제 조건을 잘 읽자
=> [20250512] BAJ / 실버5 / 기적의 매매법 / 이재인

JaeIn/202505/20 올바른 괄호 만들기.md
=> [20250520] / 올바른 괄호 만들기 / 이재인

JinHyeok/202506/16 BAJ 0 만들기.md
https://www.acmicpc.net/problem/7490
50분
수열에서 결과가 0이되는 모든 수식 출력
구현
야호
=> [20250616] BAJ / 골드5 / 0 만들기 / 양진혁

Ho/202506/16 세 용액.md
https://www.acmicpc.net/problem/2473
60분
세 용액을 적절히 섞어서 0에 가장 가까운 조합 찾기
조합 + 이분 탐색
아직푸는중...
=> [20250616] BAJ/G3/세 용액/김득호

JaeIn/202506/17 PGM 과제 진행하기.md
https://school.programmers.co.kr/learn/courses/30/lessons/176962
50분
구현은 역시 쉽지 않네..
=> [20250617] PGM / lv2 / 과제 진행하기 / 이재인

JinHyeok/202506/17 BAJ 세용액.md
https://www.acmicpc.net/problem/2473
60분
합쳐서 0에 가까운 용액 세개 찾기
투포인터
진짜 비슷하게 풀었었는데 아쉽다.
=> [20250617] BAJ / 골드3 / 세 용액 / 양진혁

18 두 배열의 합.md
https://www.acmicpc.net/problem/2143
50분
배열 A,B의 연속된 원소의 합이 T가 되는 경우의 수 구하기
각 배열 구간 합 구하고 B배열은 구간합 값을 Map으로 관리해서 완탐
이붙탐색으로 풀려고했는데 오늘도 실패 
왜 다른 풀이가 항상 먼저 보이지?
=> [20250618] BAJ/G3/두 배열의 합/김득호

JaeIn/202506/18 PGM 광물 캐기.md
https://school.programmers.co.kr/learn/courses/30/lessons/172927
50분
5개씩 분리해서 개수를 각각 체크하고 정렬을 하는 과정까지 생각이 조금 길었음..
=> [20250618] PGM / lv2 / 광물 캐기 / 이재인

JaeIn/202506/22 PGM 무인도 여행.md, JaeIn/202506/22 PGM 호텔 대실.md
분
가장 빨리 사용 가능한 방을 생각하지 못해서 오답..
=> [20250623] PGM / lv2 / 호텔 대실 / 이재인

ShinHeeEul/202506/20 BAJ G1 The Tree.java
https://www.acmicpc.net/problem/27185
60 분
You are given an infinite binary tree. The tree has the root and infinitely many vertices, each vertex has left son and right son, each vertex except the root has a parent.
Every vertex can be painted in one of 
$c$ colors or be colorless. Initially, all vertices are colorless.
You need to process two types of requests:
color($u$, $x$) You are given a vertex $u$, paint vertex $u$ with color $x$, and then call color($L$, $(x + 1) \bmod c$) for its left son $L$ and color($R$, $(x - 1 + c) \bmod c$) for its right son $R$. Note that this operation repaints the entire (infinite) set of vertices in the subtree of the vertex $u$. Here $\bmod$ is the operation of taking a division remainder. If the vertex has already been painted, then its color changes …
=> [20250618] BAJ / G1 / The Tree / 신희을

ShinHeeEul/202506/27 BAJ P5 중앙값.md
https://www.acmicpc.net/problem/1572
60 분
중앙값이란, 수열을 정렬했고, 그 크기가 N일 때, 1부터 시작해서 (N+1)/2번째 있는 원소가 그 수열의 중앙값이다. 예를 들어, {1, 2, 6, 5, 4, 3}에서는 3이고, {11, 13, 12, 15, 14}에서는 13이다.
오세준은 1초에 온도를 하나씩 재는 온도계를 만들었다. 이 온도계에는 작은 디스플레이 창이 하나 있는데, 이 창에는 지금부터 최근 K초 까지 온도의 중앙값을 표시해 준다. (온도를 재기시작한지 K초부터 표시한다. 그 전에는 아무것도 출력되지 않는다.)
오세준은 온도를 N초동안 쟀다. 그 시간 동안 온도계의 디스플레이 창에 뜨는 숫자의 합을 구하는 프로그램을 작성하시오.
다른 말로 하면, 길이가 N인 수열이 주어진다. 이 수열은 N-K+1 개의 길이가 K인 연속된 부분 수열이 존재한다. 이 부분 수열의 중앙값의 합을 출력하는 프로그램을 작성하시오.
입력
첫째 줄에 N과 K가 주어진다. N은 250,000보다 작거나 같은 자연수이고, K는 5,000보다 작거나 같은 자연수이다. N은 항상 K보다 크거나 같다. 둘째 줄부터 N개의 수가 한 줄에 하나씩 주어진다. 입력으로 주어지는 수는 65536보다 작거나 같은 자연수 또는 0이다.
입력이 65536인 것에서 아이디어를 착안해보자. 65536은 $2^16$이다. 즉, 0부터 65536까지 전부 세그트리의 리프노드로 두어도 공간복잡도가 그렇게 크지 않다.
입력으로 들어오는 i번째 리프노드에 +1을 해주고 위로 전파해준다.
그리고 루트부터 내려오면서 좌측 노드가 …
=> [20250627] BAJ / P5 / 중앙값 / 신희을

Ho/202506/30 미생물 연구.md
https://www.codetree.ai/ko/frequent-problems/samsung-sw/problems/microbial-research/description
80+분
삼성 기출문제 빡 구현 시뮬레이션 문제
문제에서 제시한 기능을 잘게 나눠 쉽게 구현할 수 있도록하기
2번째 다시 풀어보는 문제 처음보도 속도가 빨라졌지만
아직도 부족한 부분이 있다.
미생물을 비교하는 검증 로직과 시작과 끝점을 비교하는 테크닉을 익숙하게 만들자
=> [20250630] CDT/삼성/미생물 연구/김득호

JaeIn/202507/01 BAJ 새로운 게임2.md, JaeIn/202507/01 BAJ 창고 다각형.md
분
그냥 구현문제..  배열 방향에 관련한 문제 더 풀어볼 예정
=> [20250701] BAJ / 골드2 / 새로운 게임2 / 이재인

Ho/202506/30 미생물 연구.md, Ho/202507/1 퍼즐 맞추기.md
없음
80분
문제에서 제시하는 기능 3개 구현
규칙에 맞게 주어지는 퍼즐을 중복된 위치를 피해서 
퍼즐을 맞춰야한다.
처음 init 단계에서 문제에서 제공하는 5가지의 퍼즐 모양대로
위치할 수 있는 공간을 미리 저장해둔다.
이후 퍼즐이 주어졌을 때 init 단계에서 미리 전처리 해둔 좌표를 찾아
퍼즐을 위치시킨다.
이 과정에서 가장 중요한거는 퍼즐을 모양별로 분류하고, 퍼즐의 특성에 맞게
해싱해서 Key 값을 만들어 저장해두는 것이 중요하다.
해당 방법을 생각한다면 나머지 구현은 크게 어렵지 않다.
문제에서 제시하는 제약조건을 참고해서 어떤 방식이 가장 효율적이고 
빠른지 찾는 것이 중요한 것 같다.
=> [20250701] SWEA/PRO/퍼즐 맞추기/김득호

Ho/202507/7 도서관.md
https://www.acmicpc.net/problem/1461
40분
세준이는 도서관에서 일한다. 도서관의 개방시간이 끝나서 세준이는 사람들이 마구 놓은 책을 다시 가져다 놓아야 한다. 세준이는 현재 0에 있고, 사람들이 마구 놓은 책도 전부 0에 있다. 각 책들의 원래 위치가 주어질 때, 책을 모두 제자리에 놔둘 때 드는 최소 걸음 수를 계산하는 프로그램을 작성하시오. 세준이는 한 걸음에 좌표 1칸씩 가며, 책의 원래 위치는 정수 좌표이다. 책을 모두 제자리에 놔둔 후에는 다시 0으로 돌아올 필요는 없다. 그리고 세준이는 한 번에 최대 M권의 책을 들 수 있다.
음수, 양수를 구분하고 절대값을 비교해서 가장 큰 경우만 1번 다녀오는 방식
가장 큰수를 제외하고는 M개씩 정리한다.
분명 더 쉽게 구현하는 방법이 있을텐데..
=> [20250707] BAJ/G4/도서관/김득호

kmj-99/202507/9 145000.md
https://www.acmicpc.net/problem/14500
180분
폴리오미노란 크기가 1×1인 정사각형을 여러 개 이어서 붙인 도형이며, 다음과 같은 조건을 만족해야 한다.
정사각형은 서로 겹치면 안 된다.
도형은 모두 연결되어 있어야 한다.
정사각형의 변끼리 연결되어 있어야 한다. 즉, 꼭짓점과 꼭짓점만 맞닿아 있으면 안 된다.
정사각형 4개를 이어 붙인 폴리오미노는 테트로미노라고 하며, 다음과 같은 5가지가 있다.
아름이는 크기가 N×M인 종이 위에 테트로미노 하나를 놓으려고 한다. 종이는 1×1 크기의 칸으로 나누어져 있으며, 각각의 칸에는 정수가 하나 쓰여 있다.
테트로미노 하나를 적절히 놓아서 테트로미노가 놓인 칸에 쓰여 있는 수들의 합을 최대로 하는 프로그램을 작성하시오.
테트로미노는 반드시 한 정사각형이 정확히 하나의 칸을 포함하도록 놓아야 하며, 회전이나 대칭을 시켜도 된다.
DFS로 테트로미트 배치 경우의 수를 찾고 ㅗㅜㅏㅓ와 같이 DFS로 처리가 안되는 모양은 따로 예외처리 해준다.
알고리즘은 무난했는데, 구현이 빡세다.
=> [20250708] BAJ / 골드2 / 145000 / 김민중

JinHyeok/202507/09 BAJ 차트.md
https://www.acmicpc.net/problem/1239
50분
DFS
=> [20250709] BAJ / 골드5 / 차트 / 양진혁

Ho/202507/10 소트.md
https://www.acmicpc.net/problem/1083
60분
크기가 N인 배열 A가 있다. 배열에 있는 모든 수는 서로 다르다. 이 배열을 소트할 때, 연속된 두 개의 원소만 교환할 수 있다. 그리고, 교환은 많아봐야 S번 할 수 있다. 이때, 소트한 결과가 사전순으로 가장 뒷서는 것을 출력한다
앞에서부터 s거리 이내에 있는 가장 큰수를 앞으로 가져오기
함정에 낚이기 쉬운문제 반례가 없었다면 틀렷을거같
=> [20250711] BAJ/G4/소트/김득호

JinHyeok/202507/14 BAJ 벽장문의 이동.md
https://www.acmicpc.net/problem/2666
50분
DP
=> [20250714] BAJ / 골드5 / 벽장문의이동 / 양진혁

kmj-99/202507/16 15685.md
https://www.acmicpc.net/problem/15685
240분
드래곤 커브는 다음과 같은 세 가지 속성으로 이루어져 있으며, 이차원 좌표 평면 위에서 정의된다. 좌표 평면의 x축은 → 방향, y축은 ↓ 방향이다.
시작 점
시작 방향
세대
0세대 드래곤 커브는 아래 그림과 같은 길이가 1인 선분이다. 아래 그림은 (0, 0)에서 시작하고, 시작 방향은 오른쪽인 0세대 드래곤 커브이다.
1세대 드래곤 커브는 0세대 드래곤 커브를 끝 점을 기준으로 시계 방향으로 90도 회전시킨 다음 0세대 드래곤 커브의 끝 점에 붙인 것이다. 끝 점이란 시작 점에서 선분을 타고 이동했을 때, 가장 먼 거리에 있는 점을 의미한다.
2세대 드래곤 커브도 1세대를 만든 방법을 이용해서 만들 수 있다. (파란색 선분은 새로 추가된 선분을 나타낸다)
3세대 드래곤 커브도 2세대 드래곤 커브를 이용해 만들 수 있다. 아래 그림은 3세대 드래곤 커브이다.
즉, K(K > 1)세대 드래곤 커브는 K-1세대 드래곤 커브를 끝 점을 기준으로 90도 시계 방향 회전 시킨 다음, 그것을 끝 점에 붙인 것이다.
크기가 100×100인 격자 위에 드래곤 커브가 N개 있다. 이때, 크기가 1×1인 정사각형의 네 꼭짓점이 모두 드래곤 커브의 일부인 정사각형의 개수를 구하는 프로그램을 작성하시오. 격자의 좌표는 (x, y)로 나타내며, 0 ≤ x ≤ 100, 0 ≤ y ≤ 100만 유효한 좌표이다.
문제 요구사항대로 구현하면된다. 근데 구현이 너무 어려움
구현이 어렵다 드래곤 커브를 어떻게 로테이션 돌릴건지, 방향은 어떻게 바꿀건지에 대해 …
=> [20250716] BAJ / 골드3 / 15685 / 김민중

JaeIn/202507/18 이중 우선순위 큐.md, JaeIn/202507/test.py
60분
삭제 부분에서 시간복잡도 -> 딕셔너리 활용
다시 한 번 풀어보겠슴다
=> [20250718] BAJ / 골드4 / 이중 우선순위 큐 / 이재인

Ho/202507/18 좋다.md
https://www.acmicpc.net/problem/1253
30분
N개의 수 중에서 어떤 수가 다른 수 두 개의 합으로 나타낼 수 있다면 그 수를 “좋다(GOOD)”고 한다.
N개의 수가 주어지면 그 중에서 좋은 수의 개수는 몇 개인지 출력하라.
수의 위치가 다르면 값이 같아도 다른 수이다.
투 포인터를 이용해서 n개 인덱스를 방문하고 각 n번 탐색으로 
"좋다" 를 만족하는 수인지 판단한다.
현재 판단하고자 하는 수 i번째 수를 비교할 때 
투포인터로 조회할 때 i랑 Left, right 인덱스랑 겹치면 안된다.
=> [20250718] BAJ/G4/좋다/김득호

JinHyeok/202507/21 BAJ 상범빌딩.md
https://www.acmicpc.net/problem/6593
60분
BFS
=> [20250721] BAJ / 골드5 / 상범빌딩 / 양진혁

JinHyeok/202507/22 선긋기.md
https://www.acmicpc.net/problem/2170
40분
=> [20250722] BAJ / 골드5 / 선긋기 / 양진혁

JinHyeok/202507/25 BAJ 좋다.md
https://www.acmicpc.net/problem/1253
50분
=> [20250725] BAJ / 골드4 / 좋다 / 양진혁

Ho/202507/25 계산 게임.md
180+분
계속 추가되는 카드 뭉치속에서  문제에서 제시하는 순서에 맞는 카드 합 구하기
매턴 마다 조커 값이 변경되는 경우가 발생하기 때문에 효율적으로 작성해야한다.
더 많이 풀어보기
=> [20250725] SEA/Pro/계산게임/김득호

JinHyeok/202507/29 BAJ 조짜기.md
https://www.acmicpc.net/problem/2229
40분
=> [20250729] BAJ / 골드5 / 조짜기 / 양진혁

JaeIn/202507/31 BAJ 빗물.md
분
모든 열에 대해 고려해서 생각하긴 했지만 아이디어를 생각하지 못함..
각 열에 대해 왼쪽 , 오른쪽의 최대값을 찾은 뒤 그 중 작은 값과 현재 값을 뺀게 각 열의 남은 양
=> [20250731] BAJ / 골드5 / 빗물 / 이재인

JinHyeok/202508/01 BAJ 저울.md
https://www.acmicpc.net/problem/10159
50분
=> [20250801] BAJ / 골드4 / 저울 / 양진혁
