Kang/202409/25 PRG 이모티콘 할인행사.md
https://school.programmers.co.kr/learn/courses/30/lessons/150368
90분
이상한 반례들로 인해 힘들었다
1. python에서 전역 리스트 접근
2. 결론<나눗셈 연산은 최대한 나중에 하자‼️> 이유는 부동소수점 연산하는데 오차가 존재하기 때문에 최대한 정확도를 높이려면 나눗셈 연산을 최대한 나중에 해야하는 것 같다.
```python
min_cost += int((e[i] * (100 - percents[i])) / 100) # 정답
min_cost += int(e[i] * ((100 - percents[i]) / 100)) # 오답
```
문제 좀 빨리 읽자...
구현 좀 빨리 하자...
=> [20240925] PRG / lv2 / 이모티콘 할인행사 / 강경민

Kang/202409/26 BAJ 숨바꼭질 4.md
https://www.acmicpc.net/problem/13913
60분
bfs로 최단 거리를 찾는 문제인데
지나온 경로를 체크해줘야하는 문제이다.
지나온 경로를 노드별로 갖고 있게 했더니 메모리 초과가 나서
방문한 노드는 방문하지 않게 했더니 틀렸다
>풀이
>- dp배열에 지나온 경로에 이전 부모 노드를 기록해 놓으면 되는 문제였다.
항상 이 경로 체크 문제가 나오면 바보처럼 풀지를 못하는데 이런 문제 더 풀어야 한다ㅠ
=> [20240926] BAJ / 골드4 / 숨바꼭질 4 / 강경민

kmj-99/202409/27 수 묶기.md
https://www.acmicpc.net/problem/1744
40분
- [] 상
- [] 하
수열에 있는 2개의 수를 임의로 묶어서 수열의 합을 최대로 만들어야한다.
음수와 양수로 나누고 각각 내림차순, 오름차순 정렬을 하여 두 개의 수를 묶어서 더해주는 식으로 풀이
양수와 음수로 나누고 각각 최적의 해를 찾는다는 점에서 그리디의 느낌을 잘 느낄 수 있었다.
=> [20240927] BAJ / 골드3 / 수 묶기 / 김민중

ShinHeeEul/202410/04 BAJ 멀티탭 스케줄링.md
[링크](https://www.acmicpc.net/problem/1700)
60 분
- 가장 교체가 덜 될 수 있도록 캐싱 전략을 구현해라
- 그리디
- 캐시에 들어있는 값들 중, 그 다음에 나오는 값이 가장 먼 친구를 캐시에서 제외하기
- 득호형 없으면 못 풀었다. 완전 잘못된 풀이 방법을 가져가고 있었다.
=> [20241004] BAJ / 골드1 / 멀티탭 스케줄링 / 신희을

Ho/202410/8 BAJ 줄세우기.md
90분
LIS를 활용한 문제
LIS를 사용해서 최장 수열 길이를 구하고 전체길이에서 빼준다.
많이 연습해서 구현속도를 높여야한다.
=> [20241008] BAJ / 골드4/줄세우기/김득호

kmj-99/202410/10 두큐합같게만들기.md
https://school.programmers.co.kr/learn/courses/30/lessons/118667
30분
두 개의 큐가 주어졌을 때 각 큐의 합이 서로 같도록 하는 최소의 pop,push 연산 수를 구하는 문제
최대 연산 횟수는 두 개의 큐의 사이즈 합이기 때문에, 연산을 다 돌면서 합이 큰 값에서 합이 작은 값으로 원소를 옮겨서 합을 맞추는 식으로 접근
SoSo했다.
=> [20241010]/프로그래머스/레벨2/두큐합같게만들기

JinHyeok/202410/14 BAJ 이차원 배열과 연산.md
https://www.acmicpc.net/problem/17140
60분
- [] 상
R,C,K와 배열을 주고 
배열의 [R][C]가 K가 되기 위한 연산의 최소시간 구하기
(
board는 2차원 배열, freq는 빈도수 배열이며, R 연산이 기준)
1. 현재 행(i)을 확인한다. 
i행의 각 열(j)을 확인하고, freq[board[i][j]]를 증가시킨다.
빈도수 배열을 순회하며 {빈도수 배열의 인덱스, 해당 인덱스의 빈도수}를 벡터에 넣는다.
벡터를 정렬 기준에 따라 정렬한다. (수의 등장 횟수가 커지는 순, 그러한 것이 여러가지면 수가 커지는 순으로 정렬)
정렬된 벡터를 다시 board에 기록한다.
2. (i + 1) 행을 확인한다. (단, 마지막 행이라면 3번을 진행한다.)
3. 마지막 행의 크기에 맞춰 나머지 부분을 0으로 채운다.
⚠️ 주의할 점
빈도수 배열의 크기 (숫자 100도 빈도수 배열에 들어갈 수 있어야 함)
행의 크기가 100보다 크다면, 100까지만 기록하고, 행의 크기가 최대 100이 되도록 해주어야 함.
숫자 0, 빈도수가 0인 수는 무시해야 함.
방법이 떠오르질 않았다.. 구현은 더 열심히해야될듯
=> [20241014] BAJ / 골드4 / 이차원 배열과 연산 / 양진혁

JaeIn/202410/14 BAJ 로봇 청소기.md
https://www.acmicpc.net/problem/14503
55분
청소를 할 수 있는 칸의 수를 세는 문제
bfs로 청소를 할 때마다 count를 증가시킴
왼쪽 이동,  오른쪽 이동시키는데 아직 어렵.. 연습이 필요 ㅜ
=> [20241014] BAJ / 골드5 / 로봇 청소기 / 이재인

kmj-99/15 BJ2133.md
https://www.acmicpc.net/problem/2133
30분
3*N의 타일을 2*1, 1*2 타일로 채울 수 있는 경우의 수
N-2, N-4일 때 모양이 계속 반복이 되기 때문에 이걸 이용해서 점화식을 세워서 접근
점화식만 잘 세우면 쉽게 풀리는 거 같다.
=> [202401015] BAJ / 골드3 / 타일채우기 / 김민중

kmj-99/202410/22 1890.md
https://www.acmicpc.net/problem/1890
60분
최대 100*100인 맵에서 (0,0)에서 (99,99)까지 가는 경우의 수를 구하는 문제
완전탐색으로 접근하려 했지만 경우의 수가 10최소 50!이상이 나와서 DP로 접근해서 풀었다. dp[x][y]는 현재 좌표까지 오는 경우의 수를 뜻한다
DP가 좀 더 익숙해지고 있어서 좋은 거 같다. 시간초과 떠서 Queue사용을 할 때는 대충 리스트로 하지말고 내장된 Queue를 쓰자!
=> [20241019] BAJ / 실버1 / 점프 / 김민중

JaeIn/202410/22 BAJ 점프.md
https://www.acmicpc.net/problem/1890
65분
가장 왼쪽 위를 시작으로 오른쪽 아래 지점에 도달할 수 있는 경로의 수 구하기
dp
처음에는 bfs로 갈 수 있는 경우를 구하고 그 경우일때 queue에  + 1를 하면서 풀었는데 메모리 초과 발생..
이후에도 시간초과가 나서 실패..
풀이를 보니까 쉽게 이해.. 연습이 더 필요
=> [20241022] BAJ / 실버1 / 점프 / 이재인

JaeIn/202410/28 절대값 힙.md
https://www.acmicpc.net/problem/11286
20분
숫자를 하나씩 넣고 0이 나오는 순간 가장 작은 수를 찾아서 결과값에 추가하는 문제
우선순위 큐
우선순위 큐일 경우 앞에 수를 기준으로 판단하기 때문에 이럴 경우 튜플을 사용한다.
입출력 많아 sys를 쓰지 않으면 시간초과 발생
=> [20241028] BAJ / 실버1 / 절댓값 힙 / 이재인

kmj-99/202410/29 1890.md
https://www.acmicpc.net/status?from_mine=1&problem_id=1890&user_id=nex1223
30분
점프로 갈수 있는 경우의 수를 구하는 
모든 좌표를 돌면서 이전 새로운 좌표로 이동시 이전 좌표 값을 더하는 식으로 접근
완전탐색이랑 DP 구분을 잘 해야겠다.
=> [20241029]/BAJ/1890/골드 5/ 김민중

kmj-99/202411/8 이모티콘할인행사.md
https://school.programmers.co.kr/learn/courses/30/lessons/150368
120분
모든 유저가 이모티콘을 구매하는 최적의 경우를 구하는 문제. 단, 다음과 같은 우선순위를 고려 1. 이모티콘 구독 서비스 가입자 수 2. 이모티콘 판매량
DFS를 사용해서 모든 경우의 수를 구해서 최적회 경우를 찾는 식으로 접근
0.9,0.8이런식으로 계산하니까 1개의 테스트 케이스가 통과가 안되었다. 그래서 (100-10)*0.01, (100-80)*0.01 이런식으로 바꿨더니 통과가 됐다. 아마 소수점 계산이 조금 엇갈려서 그런 거 같다.
=> [20241108]/PGM/LV2/이모티콘할인행사/김민중

Ho/202411/12 BAJ RGB거리2.md, Ho/202411/13 BAJ 도시 분할 계획.md
https://www.acmicpc.net/problem/1647
30분
마을 내부에 길을 최소, 최적으로 만들고 
2개의 마을로 분리했을때 최소 비용으로 마을 유지하기
먼저 최소 스패닝트리를 구하고 
제일 비싼 간선을 분리해서 마을을 나눈다.
=> [20241114] BAJ / 골드4 / 도시 분할 계획 / 김득호

Ho/202501/15 광고.md
https://www.acmicpc.net/problem/1305
20분
문제에서 제시하는 광고를 출력하기 위한 최소 글자 수는 몇인가?
KMP의 실패 함수를 이용해서 접두사와 접미사랑 겹치는 최대 거리만큼 
광고판에서 빼주면 된다.
꾸준히 풀면서 해당 유형 빠르게 풀기
=> [20250115] BAJ/플레4/광고/김득호

JinHyeok/202501/17 BAJ 가장 긴 바이토닉 부분수열.md
https://www.acmicpc.net/problem/11054
30분
가장 긴 바이토닉 부분 수열의 길이를 구하는 문제
DP
그냥 DP 배열을 두개써서 나중에 합치면된다
=> [20250117] BAJ / 골드4 / 가장 긴 바이토닉 부분 수열 / 양진혁

kmj-99/202501/31 벽부수고이동하기.md
https://www.acmicpc.net/problem/2206
120분
N×M의 행렬로 표현되는 맵이 있다. 맵에서 0은 이동할 수 있는 곳을 나타내고, 1은 이동할 수 없는 벽이 있는 곳을 나타낸다. 당신은 (1, 1)에서 (N, M)의 위치까지 이동하려 하는데, 이때 최단 경로로 이동하려 한다. 최단경로는 맵에서 가장 적은 개수의 칸을 지나는 경로를 말하는데, 이때 시작하는 칸과 끝나는 칸도 포함해서 센다.
만약에 이동하는 도중에 한 개의 벽을 부수고 이동하는 것이 좀 더 경로가 짧아진다면, 벽을 한 개 까지 부수고 이동하여도 된다.
한 칸에서 이동할 수 있는 칸은 상하좌우로 인접한 칸이다.
맵이 주어졌을 때, 최단 경로를 구해 내는 프로그램을 작성하시오.
처음에 dfs로 접근했다가 시간초과가 나서 bfs로 풀었다. 벽을 부순 상태와 벽을 부수지 않는 상태를 구분해서 가야한다는 점이 생각하기 어려웠다. 벽을 부순 상태에서 가다가 마지막에 벽이 있으면 결국 도착지로 못간다. 벽을 안부순상태에서 가면 도착지로 갈 수 있지만 이미 벽을 부순상태에서 간 길이 visited = true이기에 도착지에 도달하지 못한다. 이때문에 visited[N][M][2] 이런식으로 3차원 배열을 사용해서 벽을 부순 상태와 그렇지 않은 상태로 구분해서 접근을 해야한다.
분기를 나누는 게 쉽지 않았다.
=> [20250131]/BJ/골드3/벽부수고이동하기

JinHyeok/202502/04 BAJ 줄세우기.md
https://www.acmicpc.net/problem/2631
30분
차례대로 줄 세우는 최소 횟수
부분 수열 구하기
자리를 바꾸는게 아니라 한명씩 옮기는 것이므로
차례대로 올라가는 가장 큰 부분 수열을 구하면 끝
=> [20250204] BAJ / 골드4 / 줄세우기 / 양진혁

kmj-99/202502/4 축제.md
https://softeer.ai/app/assessment/index.html?xid=359663&xsrfToken=3b7BmwSA3MISmmhoE9UUYNB2hWErEVeG&testType=practice
200분
자연을 사랑하는 요정 깐프들은 거대한 나무, 세계수에 산다. 세계수는 N개의 정점으로 이루어진 트리로 표현할 수 있다. 정점에는 1에서 N까지 번호가 붙어 있으며, 처음에 i번 정점에는 Gi​명의 깐프들이 살고 있다.
두 정점은 하나의 가지로 연결되어 있어 깐프들은 가지를 따라 정점 사이를 양방향으로 이동할 수 있다. 가지는 총 N−1개 있으며, 임의의 두 정점 사이 이동이 가능하도록 연결되어 있다. 가지에도 1에서 N−1까지의 번호가 붙어 있으며, i번 가지는 Xi​번 정점과 Yi​번 정점을 연결하는 길이가 Li​인 가지이다.
수명이 긴 깐프들에게 앞으로 Q번의 이벤트가 일어난다. i번째 이벤트는 다음 2 종류 중 하나와 같다.
vi​번 정점에서 세계수에 사는 모든 깐프들이 모이는 축제를 연다.
vi​번 정점에 새로운 깐프가 gi​명 더 태어나 살게 된다.
1번 종류의 이벤트에서 깐프들은 수가 매우 많기 때문에, 모든 깐프들이 세계수의 가지를 따라 이동하는 과정에서 세계수에 많은 부담이 간다. 하지만 축제에는 모든 깐프가 참여해야 하기에, 어느 정도 부담이 가는지 미리 계산해서 적절히 세계수를 관리하고자 한다.
축제가 일어나 깐프들이 이동할 때, 세계수에 가해지는 부담은 각 정점에 사는 모든 깐프들이 vi​번 정점으로 이동한 거리들의 합으로 계산한다. 깐프들은 세계수에 부담을 최소화하기 위해 …
=> [20250204]/Softeer/LV5/축제

ShinHeeEul/202502/05 BAJ P4 시저 암호.md
https://www.acmicpc.net/problem/1893
90 분
알파벳 순서 A, 원문 W, 시저 암호화된 문자열 S가 있다. 암호화된 문자열 S는 특정 문자열의 문자들을 알파벳 순서에 따라 X 만큼 밀어서 만든 문자열이다. 암호화 되기 전의 문자열에 원문 W가 단 1번만 등장하는 X를 오름차순으로 출력하라.
원문으로 실패 배열을 만들고, 암호화된 문자열을 하나씩 밀면서 문자열과 원문을 KMP로 단 한번만 등장하는 지를 체크한다.
연휴 내내 푹 쉬어서 까먹었을까봐 걱정했는데, 다행히 까먹진 않았더라
=> [20250205] BAJ / P4 / 시저 암호 / 신희을

kmj-99/202502/5 축제.md
https://softeer.ai/practice/11005/history?questionType=ALGORITHM
500분
자연을 사랑하는 요정 깐프들은 거대한 나무, 세계수에 산다. 세계수는 N개의 정점으로 이루어진 트리로 표현할 수 있다. 정점에는 1에서 N까지 번호가 붙어 있으며, 처음에 i번 정점에는 Gi​명의 깐프들이 살고 있다.
두 정점은 하나의 가지로 연결되어 있어 깐프들은 가지를 따라 정점 사이를 양방향으로 이동할 수 있다. 가지는 총 N−1개 있으며, 임의의 두 정점 사이 이동이 가능하도록 연결되어 있다. 가지에도 1에서 N−1까지의 번호가 붙어 있으며, i번 가지는 Xi​번 정점과 Yi​번 정점을 연결하는 길이가 Li​인 가지이다.
수명이 긴 깐프들에게 앞으로 Q번의 이벤트가 일어난다. i번째 이벤트는 다음 2 종류 중 하나와 같다.
vi​번 정점에서 세계수에 사는 모든 깐프들이 모이는 축제를 연다.
vi​번 정점에 새로운 깐프가 gi​명 더 태어나 살게 된다.
1번 종류의 이벤트에서 깐프들은 수가 매우 많기 때문에, 모든 깐프들이 세계수의 가지를 따라 이동하는 과정에서 세계수에 많은 부담이 간다. 하지만 축제에는 모든 깐프가 참여해야 하기에, 어느 정도 부담이 가는지 미리 계산해서 적절히 세계수를 관리하고자 한다.
축제가 일어나 깐프들이 이동할 때, 세계수에 가해지는 부담은 각 정점에 사는 모든 깐프들이 vi​번 정점으로 이동한 거리들의 합으로 계산한다. 깐프들은 세계수에 부담을 최소화하기 위해 자신이 사는 정점에서 다른 정점으로 이동할 때 항상 최단 거리로 이동한다.
추가로 1번 …
=> [20250205]/Softeer/LV5/축제

ShinHeeEul/202502/10 BAJ G1 계단 수.md
https://www.acmicpc.net/problem/1562
540 분
45656이란 수를 보자.
이 수는 인접한 모든 자리의 차이가 1이다. 이런 수를 계단 수라고 한다.
N이 주어질 때, 길이가 N이면서 0부터 9까지 숫자가 모두 등장하는 계단 수가 총 몇 개 있는지 구하는 프로그램을 작성하시오. 0으로 시작하는 수는 계단수가 아니다.
3차원 DP + 비트 마스킹
dp[길이][마지막 수][이제까지 나온 수 비트 마스킹] 으로 두고
`dp[i][j][k | j] += dp[i-1][j+1][k] + dp[i][j-1][k]`을 점화식으로 세운다. dp 배열을 다 채운 후, 길이가 N이면서 0~9까지 모두 나온 값들을 전부 더해서 구해준다.
앞에서부터 차근차근 쌓아가도 되었는데, 중간에서 시작해 양쪽으로 확장하면서 비교하려고 한게 화근이었다. 중복을 잡을 수가 없더라. 그리고 이제껏 백트래킹을 이용한 비트마스킹만 풀어왔는데, 그렇지 않은 문제도 있다는 것을 알게 되었다.
=> [20250210] BAJ / G1 / 계단 수 / 신희을

ShinHeeEul/202502/11 BAJ P3 XOR.md
https://www.acmicpc.net/problem/12844
60 분
크기가 N인 수열 A0, A1, ..., AN-1이 주어졌을 때, 다음 두 종류의 쿼리를 수행해보자.
1 i j k: Ai, Ai+1, ..., Aj에 k를 xor한다.
2 i j: Ai, Ai+1, ..., Aj를 모두 xor한 다음 출력한다.
느리게 갱신되는 세그먼트 트리에 XOR로 더해가는 방식이다. XOR 특성 상 짝수 번 XOR 되면 안 한 것과 같다. 그러므로 **updateLazy 함수**에서 현재 범위를 업데이트해야 한다 하면, 범위가 홀수인지 체크하고, 홀수라면 업데이트한다. 그리고 홀수 여부를 **부모 updateLazy 함수**에게 반환해준다.
반환 받은 **부모 updateLazy 함수**에서 자식들의 반환값을 XOR하고(만약 둘 다 True를 반환한다면 현재 위치에서는 짝수번 업데이트 된다는 것으로 업데이트 할 필요가 없다!) True인 경우 다시 현재 노드에 업데이트, 아니라면 False를 그 부모에게 전달한다.
좀 성장한듯 ㅎ
=> [20250211] BAJ / P3 / XOR / 신희을

kmj-99/202502/16 막대기
https://www.acmicpc.net/problem/1094
30분
지민이는 길이가 64cm인 막대를 가지고 있다. 어느 날, 그는 길이가 Xcm인 막대가 가지고 싶어졌다. 지민이는 원래 가지고 있던 막대를 더 작은 막대로 자른다음에, 풀로 붙여서 길이가 Xcm인 막대를 만들려고 한다.
막대를 자르는 가장 쉬운 방법은 절반으로 자르는 것이다. 지민이는 아래와 같은 과정을 거쳐서 막대를 자르려고 한다.
지민이가 가지고 있는 막대의 길이를 모두 더한다. 처음에는 64cm 막대 하나만 가지고 있다. 이때, 합이 X보다 크다면, 아래와 같은 과정을 반복한다.
가지고 있는 막대 중 길이가 가장 짧은 것을 절반으로 자른다.
만약, 위에서 자른 막대의 절반 중 하나를 버리고 남아있는 막대의 길이의 합이 X보다 크거나 같다면, 위에서 자른 막대의 절반 중 하나를 버린다.
이제, 남아있는 모든 막대를 풀로 붙여서 Xcm를 만든다.
X가 주어졌을 때, 위의 과정을 거친다면, 몇 개의 막대를 풀로 붙여서 Xcm를 만들 수 있는지 구하는 프로그램을 작성하시오. 
비트마스킹을 적용하여 x를 이진수로 바꾸고 1의 개수만큼 막대기가 필요하므로 1의 개수가 곧 답이뵌다.
비트마스킹을 통해 푸는 방법이 신박하다.
=> [20250216]/BJ/실버5/막대기/김민중

kmj-99/202502/22 줄세우기
https://www.acmicpc.net/problem/2631
60분
KOI 어린이집에는 N명의 아이들이 있다. 오늘은 소풍을 가는 날이다. 선생님은 1번부터 N번까지 번호가 적혀있는 번호표를 아이들의 가슴에 붙여주었다. 선생님은 아이들을 효과적으로 보호하기 위해 목적지까지 번호순서대로 일렬로 서서 걸어가도록 하였다. 이동 도중에 보니 아이들의 번호순서가 바뀌었다. 그래서 선생님은 다시 번호 순서대로 줄을 세우기 위해서 아이들의 위치를 옮기려고 한다. 그리고 아이들이 혼란스러워하지 않도록 하기 위해 위치를 옮기는 아이들의 수를 최소로 하려고 한다.
예를 들어, 7명의 아이들이 다음과 같은 순서대로 줄을 서 있다고 하자.
3 7 5 2 6 1 4
아이들을 순서대로 줄을 세우기 위해, 먼저 4번 아이를 7번 아이의 뒤로 옮겨보자. 그러면 다음과 같은 순서가 된다.
3 7 4 5 2 6 1
이제, 7번 아이를 맨 뒤로 옮긴다.
3 4 5 2 6 1 7
다음 1번 아이를 맨 앞으로 옮긴다.
1 3 4 5 2 6 7
마지막으로 2번 아이를 1번 아이의 뒤로 옮기면 번호 순서대로 배치된다.
1 2 3 4 5 6 7
위의 방법으로 모두 4명의 아이를 옮겨 번호 순서대로 줄을 세운다. 위의 예에서 3명의 아이만을 옮겨서는 순서대로 배치할 수가 없다. 따라서, 4명을 옮기는 것이 가장 적은 수의 아이를 옮기는 것이다.
N명의 아이들이 임의의 순서로 줄을 서 있을 때, 번호 순서대로 배치하기 위해 옮겨지는 아이의 최소 수를 구하는 프로그램을 작성하시오.
최대 증가하는 부분수열의 길이를 전체 길이에서 빼면 된다. 그러면 …
=> [20250222]/BJ/골드4/줄세우기/김민중

kmj-99/202502/28 1027
https://www.acmicpc.net/problem/1027
60분
세준시에는 고층 빌딩이 많다. 세준시의 서민 김지민은 가장 많은 고층 빌딩이 보이는 고층 빌딩을 찾으려고 한다. 빌딩은 총 N개가 있는데, 빌딩은 선분으로 나타낸다. i번째 빌딩 (1부터 시작)은 (i,0)부터 (i,높이)의 선분으로 나타낼 수 있다. 고층 빌딩 A에서 다른 고층 빌딩 B가 볼 수 있는 빌딩이 되려면, 두 지붕을 잇는 선분이 A와 B를 제외한 다른 고층 빌딩을 지나거나 접하지 않아야 한다. 가장 많은 고층 빌딩이 보이는 빌딩을 구하고, 거기서 보이는 빌딩의 수를 출력하는 프로그램을 작성하시오.
기울기 구해서 양쪽으로 비교하면 된다.
쉽다.
=> [20250228]/BJ/골드4/1027/김민중

Ho/202503/4 곡선 자르기.md
https://www.acmicpc.net/problem/14865
300분
x축을 기준으로 잘랐을 떄 봉우리를 포함하고 있는 봉우리 개수와 어떤 봉우리도 
포함하지 않고 있는 봉우리 개수를 출력하시오.
문제에 입력 값은 제시한 패턴을 기준으로 주어진다. 반시계방향으로 주어지기 떄문에
맨 왼쪽 아래 점을 잡고 모든 음수에서 양수로 변경하는 x1 좌표  양수 -> 음수로 변경되는 x2 좌표
이 구간이 봉우리다.
이렇게 구한 봉우리를 x1을 기준으로 정렬한다. 
이때부터는 스택 "(" , ")"  넣고 빼고하는 문제랑 같이 x1 과 x2가 작은 것부터 배열에 넣어서 
정렬한걸 기준으로 스택을 이용한다. 
너무 구현을 더럽게했다 그리고ㅓ
진짜 오래걸렸다 구현 문제는 깔끔하게 정리하고 코드도 잘 정리해서 풀기
=> [20250304] BAJ/P5/곡선 자르기/김득호

kmj-99/202503/5 22251.md
https://www.acmicpc.net/problem/22251
60분
빌런 호석은 치르보기 빌딩의 엘리베이터 디스플레이의 LED 중에서 최소 
$1$개, 최대 
$P$개를 반전시킬 계획을 세우고 있다. 반전이란 켜진 부분은 끄고, 꺼진 부분은 켜는 것을 의미한다. 예를 들어 숫자 
$1$을 
$2$로 바꾸려면 총 5개의 LED를 반전시켜야 한다. 또한 반전 이후에 디스플레이에 올바른 수가 보여지면서 
$1$ 이상 
$N$ 이하가 되도록 바꿔서 사람들을 헷갈리게 할 예정이다. 치르보기를 사랑하는 모임의 회원인 당신은 호석 빌런의 행동을 미리 파악해서 혼쭐을 내주고자 한다. 현재 엘리베이터가 실제로는 
$X$층에 멈춰있을 때, 호석이가 반전시킬 LED를 고를 수 있는 경우의 수를 계산해보자.
표시등에 대한 정보를 미리 입력해 둔다.
현재 층을 디스플레이 정보로 변환해 준다.
1 ~ N 중에 P개 이내의 표시등을 반전시켜 해당 수를 만들 수 있는지 확인한다.
SOSO
=> [20250305]/BJ/골드5/22251/김민중

kmj-99/11 13460.md
https://www.acmicpc.net/problem/13460
200분
스타트링크에서 판매하는 어린이용 장난감 중에서 가장 인기가 많은 제품은 구슬 탈출이다. 구슬 탈출은 직사각형 보드에 빨간 구슬과 파란 구슬을 하나씩 넣은 다음, 빨간 구슬을 구멍을 통해 빼내는 게임이다.
보드의 세로 크기는 N, 가로 크기는 M이고, 편의상 1×1크기의 칸으로 나누어져 있다. 가장 바깥 행과 열은 모두 막혀져 있고, 보드에는 구멍이 하나 있다. 빨간 구슬과 파란 구슬의 크기는 보드에서 1×1크기의 칸을 가득 채우는 사이즈이고, 각각 하나씩 들어가 있다. 게임의 목표는 빨간 구슬을 구멍을 통해서 빼내는 것이다. 이때, 파란 구슬이 구멍에 들어가면 안 된다.
이때, 구슬을 손으로 건드릴 수는 없고, 중력을 이용해서 이리 저리 굴려야 한다. 왼쪽으로 기울이기, 오른쪽으로 기울이기, 위쪽으로 기울이기, 아래쪽으로 기울이기와 같은 네 가지 동작이 가능하다.
각각의 동작에서 공은 동시에 움직인다. 빨간 구슬이 구멍에 빠지면 성공이지만, 파란 구슬이 구멍에 빠지면 실패이다. 빨간 구슬과 파란 구슬이 동시에 구멍에 빠져도 실패이다. 빨간 구슬과 파란 구슬은 동시에 같은 칸에 있을 수 없다. 또, 빨간 구슬과 파란 구슬의 크기는 한 칸을 모두 차지한다. 기울이는 동작을 그만하는 것은 더 이상 구슬이 움직이지 않을 때 까지이다.
보드의 상태가 주어졌을 때, 최소 몇 번 만에 빨간 구슬을 구멍을 통해 빼낼 수 있는지 구하는 프로그램을 작성하시오.
빨간, 파란공이 '#'으로 이동한다고 가정을 하고, 빨간공이 '0'에 도착한다면 정답을 …
=> [20250311]/BJ/골드1/13460/김민중

Ho/202503/12 순환순열.md
분
문자열 A,B 가 있고 B는 순환하는데 XOR 해서 0 이나오는 경우 구하기
/*
최대 10만 자리라 2중 for문은 안된다.
문자열 A를 AA 형태로 붙여서 만든다.
이후 len(B) 만큼 인덱스르 0부터 len(A)까지 이동하면서 비교한다.
모두 일치하는 경우가 XOR 0이 나오는 경우임
*/
KMP를 이해하고 정리하고 적용하고 해도 맨날 같은 부분에서 헷갈린다. 
f[] 배열은 0부터 i번째까지 접두/접미가 몇개 일치하는지  기록하는 배열이다.
만약 j랑 i 번 째가 다르면 
나는 j = f[j] 라고 했다 하지만 j = f[j - 1]을 해야한다.
무한루프를 도는 경우가 발생한다. 
왜일까?
일단 f[j]로 돌아간다는건 0부터 j 길이만큼 접두/접미가 몇개 일치하는지 기록되어있다.
이때 비교하는 문자가 처음부터 (i == 1, j == 0) 그리고 (i == 2, j == 1) 두 경우가 모두 일치하게 
증가한다면 무한루프를 발생시킨다.
EX) 
P = AAAB 일떄 
f =  {0, 1, 2, 0} 으로 만들어져야한다.
KMP 특성상 위 배열을 만들 때 
첫번째
A A A B
A   
위 처럼 비교해서 1을 채운다.
두번째
A A A B
A A
이렇게 비교해서 2를 채운다.
세번째 
A  A  A B
A  A  A
이렇게 되어서 불일치하게되는데 이때 i = 3이다
f[3]은 0부터 3번째 인덱스까지 선택한 문자열의 접두 접미 길이를 의미하는데
이 값을 구해가는 과정은 
3 - 1
A A A B
A A
3 - 2
A A A B
A
위 두과정을 거쳐서 일치하는게 없다는것을 확인하고 0이라는 값이 …
=> [20250312] P5/BAJ/순환 순열/김득호

ShinHeeEul/202503/13 BAJ G3 소용돌이 이쁘게 출력하기.md
https://www.acmicpc.net/problem/1022
100 분
크기가 무한인 정사각형 모눈종이가 있다. 모눈종이의 각 정사각형은 행과 열의 쌍으로 표현할 수 있다.
이 모눈종이 전체를 양의 정수의 소용돌이 모양으로 채울 것이다. 일단 숫자 1을 0행 0열에 쓴다. 그리고 나서 0행 1열에 숫자 2를 쓴다. 거기서 부터 소용돌이는 반시계 방향으로 시작된다. 다음 숫자는 다음과 같이 채우면 된다.
```
-3 -2 -1  0  1  2  3
--------------------
-3 |37 36 35 34 33 32 31
-2 |38 17 16 15 14 13 30
-1 |39 18  5  4  3 12 29
0 |40 19  6  1  2 11 28
1 |41 20  7  8  9 10 27
2 |42 21 22 23 24 25 26
3 |43 44 45 46 47 48 49
```
이 문제는 위와 같이 채운 것을 예쁘게 출력하면 된다. r1, c1, r2, c2가 입력으로 주어진다. r1, c1은 가장 왼쪽 위 칸이고, r2, c2는 가장 오른쪽 아래 칸이다.
예쁘게 출력한다는 것은 다음과 같이 출력하는 것이다.
출력은 r1행부터 r2행까지 차례대로 출력한다.
각 원소는 공백으로 구분한다.
모든 행은 같은 길이를 가져야 한다.
공백의 길이는 최소로 해야 한다.
모든 숫자의 길이(앞에 붙는 공백을 포함)는 같아야 한다.
만약 수의 길이가 가장 길이가 긴 수보다 작다면, 왼쪽에서부터 공백을 삽입해 길이를 맞춘다.
소용돌이를 돌면서 범위 안에 들어온다면 정답 배열에 추가해준다. 이후 배열을 …
=> [20250313] BAJ / G3 / 소용돌이 이쁘게 출력하기 / 신희을

kmj-99/202503/21 2169
https://www.acmicpc.net/problem/2169
200분
NASA에서는 화성 탐사를 위해 화성에 무선 조종 로봇을 보냈다. 실제 화성의 모습은 굉장히 복잡하지만, 로봇의 메모리가 얼마 안 되기 때문에 지형을 N×M 배열로 단순화 하여 생각하기로 한다.
지형의 고저차의 특성상, 로봇은 움직일 때 배열에서 왼쪽, 오른쪽, 아래쪽으로 이동할 수 있지만, 위쪽으로는 이동할 수 없다. 또한 한 번 탐사한 지역(배열에서 하나의 칸)은 탐사하지 않기로 한다.
각각의 지역은 탐사 가치가 있는데, 로봇을 배열의 왼쪽 위 (1, 1)에서 출발시켜 오른쪽 아래 (N, M)으로 보내려고 한다. 이때, 위의 조건을 만족하면서, 탐사한 지역들의 가치의 합이 최대가 되도록 하는 프로그램을 작성하시오.
완전 탐색으로 접근할 경우 시간초과가 나서, dp 로 접근해서 풀이
첫 번째 줄은 값을 도출할 수 있다는 것이 트리거이다.
dp 가 슬슬 익숙해 진다.
=> [20250321]/BJ/골드2/2169/김민중

Ho/202503/31 분포표만들기.md
https://www.acmicpc.net/problem/14919
40분
0과 1사이의 실수 a1, a2, ..., aN이 입력으로 주어졌다고 하자.  구간 [0,1)을 다음과 같이 m개의 길이 L=1/m인 부분구간으로 나누자. 각 구간은 순서대로 b1, b2, ..., bm이다.
b1: 0 ≤ x < L,
b2: L ≤ x < 2L,
...
bm: (m-1)L ≤ x < 1.
입력된 실수중, 각 구간 b1, b2, ..., bm에 포함되는 수의 개수를 출력하시오.
1/m 으로 나누어진 구간 중 어디에 해당하는 지 찾아야하는데 
이때 주어진 수에 m를 곱하고 (int)롤 변환해서 인덱스를 찾도록했다.
근데 부동 소수점 문제가 발생해서 문제가 틀렸다고 나왔고
아주작은 1e-8의 값을 더해주면 해결할 수 있다.
은근 부동소수점 이슈가 나중에 많이 생길텐데 알고 주의하자
=> [20250331] BAJ/S2/분포표 만들기/김득호

kmj-99/202504/2 9935.
https://www.acmicpc.net/problem/9935
1000분
상근이는 문자열에 폭발 문자열을 심어 놓았다. 폭발 문자열이 폭발하면 그 문자는 문자열에서 사라지며, 남은 문자열은 합쳐지게 된다.
폭발은 다음과 같은 과정으로 진행된다.
문자열이 폭발 문자열을 포함하고 있는 경우에, 모든 폭발 문자열이 폭발하게 된다. 남은 문자열을 순서대로 이어 붙여 새로운 문자열을 만든다.
새로 생긴 문자열에 폭발 문자열이 포함되어 있을 수도 있다.
폭발은 폭발 문자열이 문자열에 없을 때까지 계속된다.
상근이는 모든 폭발이 끝난 후에 어떤 문자열이 남는지 구해보려고 한다. 남아있는 문자가 없는 경우가 있다. 이때는 "FRULA"를 출력한다.
폭발 문자열은 같은 문자를 두 개 이상 포함하지 않는다.
replace를 쓰니까 시간초과가 났다. 그래서 stack에 한 문자씩 담은다음에 stack의 크기가 폭발문자열 크기보다 크다면 폭발문자열 크기만큼 stack에 있는 문자열을 검사하는 식으로 접근했다. 이렇게 하니까 시간복잡도가 1,000,000*36이 나와서 시간초과를 면했다.
시간복잡도 계산을 정확하게 하는 게 중요하다.
=> [202504]/BJ/골드4/9935/김민중

ShinHeeEul/202504/29 BAJ P1 바이러스 시뮬레이터.md
120+ 분
2123년 봄, 드디어 '바이러스 시뮬레이터'가 출시되었다.
바이러스 시뮬레이터는 사람들의 면역력과 바이러스의 생명력 등을 설정하여 직접 시뮬레이션을 진행하는 프로그램으로, 훗날 바이러스가 창궐할 때를 대비하여 만든 프로그램이다.
이 시뮬레이터에는 초기에 $N$명의 사람들이 $1$번부터 $N$번까지 번호 순서대로 배치되어 있고, $i$번째 사람의 면역력은 $A_i$이다.
여기에 한 번 이상의 행동을 할 수 있으며, 행동의 종류는 바이러스 침투, 백신 접종, 그룹 면역력 측정 총 3가지가 있다. 각 행동은 입력으로 아래와 같이 주어진다.
 
$1$ $i$ $x$: 바이러스 침투 - 생명력이 $x$인 바이러스가 $i$번 사람에게 침투한다. 바이러스는 생명력을 $1$만큼 소모하여 감염자의 면역력을 $1$ 감소시킨다. 이때 침투한 바이러스가 죽기 전에 감염자의 면역력이 없거나(즉, 면역력이 $0$이거나) 없어지게 된다면, 바이러스는 현재 위치한 감염자의 번호보다 큰 번호를 가진 사람 중 가장 면역력이 높은 사람에게 전이되며, 생명력이 $0$이 되어 죽거나 더 이상 전이될 사람이 없을 때까지 반복된다. 전이 조건과 일치하는 사람이 여러 명일 경우, 그중 번호가 가장 작은 사람에게 전이된다. $(1 \le i \le N;1 \le x \le 10^{9})$ 
 
$2$ $i$ $x$: 백신 접종 - $i$번 사람에게 효력이 $x$인 백신을 접종하여 면역력이 $x$만큼 오른다. $(1 \le i \le N;1 \le x \le 10^{9})$ 
 
$3$ $l$ $r$: 그룹 면역력 측정 - $l$번부터 …
=> [20250429] BAJ / P1 / 바이러스 시뮬레이터 / 신희을

ShinHeeEul/202505/07 BAJ D5 Strike Zone.md
https://www.acmicpc.net/problem/17975
120+ 분
이 문제에서는 두 점 집합 P1(스트라이크)과 P2(볼), 그리고 상수 c1, c2가 주어집니다.
축에 평행한 직사각형 R을 정의할 때, eval(R) = c1 × s - c2 × b (R 안의 P1 점 개수는 보상, P2 점 개수는 벌점)를 최대화하는 R을 찾아야 합니다.
즉, 가능한 많은 스트라이크를 포함하고 가능한 적은 볼을 포함하는 최적의 스트라이크 존을 구하는 문제입니다.
기본 금광 세그 문제다.
x좌표를 기준으로 정렬 후, 세그먼트 트리 리프 노드의 인덱스를 매긴다. (x좌표가 같다면 같은 인덱스를 부여한다)
다시 y좌표 기준으로 정렬 후,
바닥부터 꼭대기까지 올라가면서 update 한 후, 전 범위 연속합 최대를 구해주고
바닥을 제외한 y좌표부터 꼭대기까지 올라가면서 update 한 후, 전 범위 연속합 최대를 구해주고
다시 그 다음 y좌표부터 꼭대기까지 올라가면서 update 한 후, 전 범위 연속합 최대를 구해주고...
이 모든 값의 max를 구하면 정답!
(연속합 최대를 구할 때는 금광 세그먼트 트릭을 활용해 연속합을 구한다.)
비트 단위 입력으로 받으니 안되고, BufferedReader로 입력받으니까 통과되더라. 테스트 케이스에 탭이 섞여있나보다.
=> [20250507] BAJ / D5 / Strike Zone  / 신희을

kmj-99/202505/1937.md
https://www.acmicpc.net/problem/1937
60분
n × n의 크기의 대나무 숲이 있다. 욕심쟁이 판다는 어떤 지역에서 대나무를 먹기 시작한다. 그리고 그 곳의 대나무를 다 먹어 치우면 상, 하, 좌, 우 중 한 곳으로 이동을 한다. 그리고 또 그곳에서 대나무를 먹는다. 그런데 단 조건이 있다. 이 판다는 매우 욕심이 많아서 대나무를 먹고 자리를 옮기면 그 옮긴 지역에 그 전 지역보다 대나무가 많이 있어야 한다.
이 판다의 사육사는 이런 판다를 대나무 숲에 풀어 놓아야 하는데, 어떤 지점에 처음에 풀어 놓아야 하고, 어떤 곳으로 이동을 시켜야 판다가 최대한 많은 칸을 방문할 수 있는지 고민에 빠져 있다. 우리의 임무는 이 사육사를 도와주는 것이다. n × n 크기의 대나무 숲이 주어져 있을 때, 이 판다가 최대한 많은 칸을 이동하려면 어떤 경로를 통하여 움직여야 하는지 구하여라.
dfs를 돌면서 dp 계산
좌표 다룰때 X,Y변수명 신경쓰자,,
=> [20250508] BAJ / 골드3 / 욕심쟁이 판다 / 김민중

Ho/202506/25 흙길 보수하기.md, Ho/202506/27 카드 정렬하기.md
https://www.acmicpc.net/problem/1715
20분
정렬된 두 묶음의 숫자 카드가 있다고 하자. 각 묶음의 카드의 수를 A, B라 하면 보통 두 묶음을 합쳐서 하나로 만드는 데에는 A+B 번의 비교를 해야 한다. 이를테면, 20장의 숫자 카드 묶음과 30장의 숫자 카드 묶음을 합치려면 50번의 비교가 필요하다.
매우 많은 숫자 카드 묶음이 책상 위에 놓여 있다. 이들을 두 묶음씩 골라 서로 합쳐나간다면, 고르는 순서에 따라서 비교 횟수가 매우 달라진다. 예를 들어 10장, 20장, 40장의 묶음이 있다면 10장과 20장을 합친 뒤, 합친 30장 묶음과 40장을 합친다면 (10 + 20) + (30 + 40) = 100번의 비교가 필요하다. 그러나 10장과 40장을 합친 뒤, 합친 50장 묶음과 20장을 합친다면 (10 + 40) + (50 + 20) = 120 번의 비교가 필요하므로 덜 효율적인 방법이다.
N개의 숫자 카드 묶음의 각각의 크기가 주어질 때, 최소한 몇 번의 비교가 필요한지를 구하는 프로그램을 작성하시오.
우선 순위큐를 사용해서 작은 단위부터 비교한다.
=> [20250627] BAJ/G4/카드 정렬하기/김득호

Ho/202507/2 물류창고.md
80분
물류 운송에 필요한 최소시간 구하기
주어지는 간선과 물류창고르 다익스트라를 이용해서 푼다.
이 때 주어지는 간선을 역방향으로 설계하면 모든 정점이 허브로 접근하는 
최소 시간을 구할 수 있기 때문에 이를 적용해야 최적의 시간을 구할 수 있다.
같은 유형을 자주 풀어보고 빠르게 설계하고 풀이하기
해설 강의을 들었기 때문에 다시 풀어보기
=> [20250702] SEA/PRO/물류창고/김득호

ShinHeeEul/202507/02 BAJ G4 카드 정렬하기.md
https://www.acmicpc.net/problem/1715
30 분
정렬된 두 묶음의 숫자 카드가 있다고 하자. 각 묶음의 카드의 수를 A, B라 하면 보통 두 묶음을 합쳐서 하나로 만드는 데에는 A+B 번의 비교를 해야 한다. 이를테면, 20장의 숫자 카드 묶음과 30장의 숫자 카드 묶음을 합치려면 50번의 비교가 필요하다.
매우 많은 숫자 카드 묶음이 책상 위에 놓여 있다. 이들을 두 묶음씩 골라 서로 합쳐나간다면, 고르는 순서에 따라서 비교 횟수가 매우 달라진다. 예를 들어 10장, 20장, 40장의 묶음이 있다면 10장과 20장을 합친 뒤, 합친 30장 묶음과 40장을 합친다면 (10 + 20) + (30 + 40) = 100번의 비교가 필요하다. 그러나 10장과 40장을 합친 뒤, 합친 50장 묶음과 20장을 합친다면 (10 + 40) + (50 + 20) = 120 번의 비교가 필요하므로 덜 효율적인 방법이다.
N개의 숫자 카드 묶음의 각각의 크기가 주어질 때, 최소한 몇 번의 비교가 필요한지를 구하는 프로그램을 작성하시오.
그리디 + pq
N == 1일때 주의하자
=> [20250702] BAJ / G4 / 카드 정렬하기 / 신희을

kmj-99/202507/7 17136
https://www.acmicpc.net/problem/17136
120분
<그림 1>과 같이 정사각형 모양을 한 다섯 종류의 색종이가 있다. 색종이의 크기는 1×1, 2×2, 3×3, 4×4, 5×5로 총 다섯 종류가 있으며, 각 종류의 색종이는 5개씩 가지고 있다.
<그림 1>
색종이를 크기가 10×10인 종이 위에 붙이려고 한다. 종이는 1×1 크기의 칸으로 나누어져 있으며, 각각의 칸에는 0 또는 1이 적혀 있다. 1이 적힌 칸은 모두 색종이로 덮여져야 한다. 색종이를 붙일 때는 종이의 경계 밖으로 나가서는 안되고, 겹쳐도 안 된다. 또, 칸의 경계와 일치하게 붙여야 한다. 0이 적힌 칸에는 색종이가 있으면 안 된다.
종이가 주어졌을 때, 1이 적힌 모든 칸을 붙이는데 필요한 색종이의 최소 개수를 구해보자.
완전탐색을 돌리면서 색종이 별로 모든 경우의 수를 살펴봤다.
구현이 좀 까다롭다.
=> [20250707] BAJ / 골드2 / 색종이 붙이기 / 김민중

Ho/202507/23.섬 지키키.md
https://swexpertacademy.com/main/code/codeBattle/problemDetail.do?contestProbId=AYH1wsXKpYUDFATO&categoryId=AZTS_npqcGvHBINJ&categoryType=BATTLE&battleMainPageIndex=3
180+분
설명하기 너무길다..
문제에서 제시하는 구조물을 2차원 배열에  놓을 수 있는 곳을 
미리 init() 단계에서 전처리 후 빠르게 연산할 수 있도록한다.
자주 연습해서 오래 걸렸던 부분을 빠르게 할 수 있도록하자..
=> [20250723] SWEA/PRO/섬 지키기/김득호

Ho/202507/25 계산 게임.md
https://swexpertacademy.com/main/code/codeBattle/problemDetail.do?contestProbId=AXxO73i6WGcDFASZ&categoryId=AZTS_npqcGvHBINJ&categoryType=BATTLE&battleMainPageIndex=3
180+분
N대의 AI 로봇들과 트레이닝 센터가 있다.
각 로봇은 1번부터 N번까지 서로 다른 번호가 부여되어 있다. 이를 고유 번호라고 한다.
로봇에는 지능지수가 있다.
로봇이 센터에 있을 때 트레이닝이 되어 로봇의 지능지수는 1 시간마다 1씩 증가한다.
예로, 시각 10일 때 지능지수가 3이면 시각 15일 때 지능지수는 8이 된다.
로봇의 지능지수는 무한히 증가할 수 있다.
로봇은 작업에 투입될 수 있다.
작업에 로봇을 투입하는 방식에는 다음과 같이 2가지가 있다.
① 높은 지능 우선 방식 : 센터에 있는 로봇들 중 지능지수가 가장 높은 로봇부터 차례대로 투입한다. 만약, 지능지수가 같은 경우 고유 번호가 가장 작은 로봇을 투입한다.
② 낮은 지능 우선 방식 : 센터에 있는 로봇들 중 지능지수가 가장 낮은 로봇부터 차례대로 투입한다. 만약, 지능지수가 같은 경우 고유 번호가 가장 작은 로봇을 투입한다.
만약, 센터에 로봇 1, 2, 3, 4, 5가 있고 로봇의 지능지수가 각각 10, 9, 10, 15, 7이라고 생각하자.
높은 지능 우선 방식으로 2대의 로봇을 작업에 투입하고자 한다면 로봇 4, 1이 투입된다.
낮은 지능 우선 방식으로 3대의 로봇을 작업에 투입하고자 한다면 로봇 5, 2, 1이 투입된다.
작업 …
=>  [20250730] SWA/Pro/AI 로봇/김득호

kmj-99/202509/18428.md
https://www.acmicpc.net/problem/18428
60분
NxN 크기의 복도가 있다. 복도는 1x1 크기의 칸으로 나누어지며, 특정한 위치에는 선생님, 학생, 혹은 장애물이 위치할 수 있다. 현재 몇 명의 학생들은 수업시간에 몰래 복도로 빠져나왔는데, 복도로 빠져나온 학생들은 선생님의 감시에 들키지 않는 것이 목표이다.
각 선생님들은 자신의 위치에서 상, 하, 좌, 우 4가지 방향으로 감시를 진행한다. 단, 복도에 장애물이 위치한 경우, 선생님은 장애물 뒤편에 숨어 있는 학생들은 볼 수 없다. 또한 선생님은 상, 하, 좌, 우 4가지 방향에 대하여, 아무리 멀리 있더라도 장애물로 막히기 전까지의 학생들은 모두 볼 수 있다고 가정하자.
다음과 같이 3x3 크기의 복도의 정보가 주어진 상황을 확인해보자. 본 문제에서 위치 값을 나타낼 때는 (행,열)의 형태로 표현한다. 선생님이 존재하는 칸은 T, 학생이 존재하는 칸은 S, 장애물이 존재하는 칸은 O로 표시하였다. 아래 그림과 같이 (3,1)의 위치에는 선생님이 존재하며 (1,1), (2,1), (3,3)의 위치에는 학생이 존재한다. 그리고 (1,2), (2,2), (3,2)의 위치에는 장애물이 존재한다. 
이 때 (3,3)의 위치에 존재하는 학생은 장애물 뒤편에 숨어 있기 때문에 감시를 피할 수 있다. 하지만 (1,1)과 (2,1)의 위치에 존재하는 학생은 선생님에게 들키게 된다.
학생들은 복도의 빈 칸 중에서 장애물을 설치할 위치를 골라, 정확히 3개의 장애물을 설치해야 한다. 결과적으로 3개의 장애물을 설치하여 모든 학생들을 감시로부터 …
=> [20250909] BAJ / 골드5 / 감시피하기 / 김민중
